### ISSUE TITLE
Base games show, usb drive ignored?

### ISSUE THREAD

**Issue by manchos2** [pathartl/BleemSync#1]
Followed the steps but my USB isn't being detected and it just shows the base system games on startup.
Used a FAT32 usb named 'SONY' in port 2 and have done plug-remove startup. Using a PAL PS Classic (if relevant)

Thanks

**Comment by jaricma** [comment]
The same thing happens to me

**Comment by pathartl** [comment]
@manchos2 can you see if the console flashes orange when the first Sony logo is shown?

**Comment by manchos2** [comment]
> @manchos2 can you see if the console flashes orange when the first Sony logo is shown?

Nah, it stays green

**Comment by pathartl** [comment]
That means that the lolhack payload isn't executing. Make sure you have the `lolhack` and `028c18a9-ec4b-4632-b2cf-d4e20f252e8f` directories from the ZIP file.

**Comment by manchos2** [comment]
![image](https://user-images.githubusercontent.com/15345236/49689515-1ed81800-fb1a-11e8-800e-beb3d1b054aa.png)
I have those directories.

Drive is a Kingston data traveller USB. I'll try another stick

**Comment by manchos2** [comment]
Tried a Samsung 64gb USB and it works with that. Guess it just didn't like the Kingston one

**Comment by pathartl** [comment]
Marking this as closed, issue was incompatible USB drive.

I started a compatibility list here:
https://docs.google.com/spreadsheets/d/1saluXC8jfWhOVT9-JXj1Kd62hL2WGtCX6zErY6AElco/edit#gid=0

**Comment by SilverRush88** [comment]
I’ve used a couple different usb drives and have gotten nothing at all the light on the usb flashes that it’s being read by the console but won’t show anything but the factory default games

**Comment by saschagehlich** [comment]
@SilverRush88 Same for me until I got a stick from the list @pathartl posted. Try that.
