### ISSUE TITLE
OSX 0.4.1 bleemsync.exe

### ISSUE THREAD

**Issue by aznlilboy88** [pathartl/BleemSync#100]
please help me eveytime I try to run bleemsync.exe on my MacBook it have an error message can someone helm me in detail please I'm not good with computer so don't use any advance word please help me step by step please and thank you

**Comment by DefKorns** [comment]
@aznlilboy88 
On OSX there's no exe. just run `BleemSync`. 
```
cd BleemSync
./BleemSync
```

**Comment by aznlilboy88** [comment]
Defkorns can you explain to me how to do it please?

**Comment by pathartl** [comment]
You have to run it through Terminal. I am going to recommend you wait until we have a UI.
