### ISSUE TITLE
Bleemsync doesn't generate system folder for me!

### ISSUE THREAD

**Issue by hamadoo14** [pathartl/BleemSync#104]
Hey dude..
few days ago I posted the same problem and you closed it, giving me the solution that wasn't helpful unfortunately.

I'm 100% sure that I did everything correctly I just can't know what's causing this problem. I've almost done everything to get it to work. it just doesn't want to generate the damn file for me. I've already extracted the files, tried to rename the folder, tried to work off the desktop and usb, run it as administrator. but no hope. pls help me I need to fix this.
thank you

**Comment by wolfrin** [comment]
Go into the bleemsync folder and run bleemsync.exe it should create the system folder

**Comment by hamadoo14** [comment]
I already did! almost tried everything available. when I run bleemsync.exe it just closes instantly. it doesn't do anything at all.

**Comment by pathartl** [comment]
Please provide a screenshot of how everything is on your flash drive

**Comment by hamadoo14** [comment]
> Please provide a screenshot of how everything is on your flash drive

I have a video showing everything if I may send it to you on twitter or something. I tried to send it here but GitHub doesn't support mp4.

**Comment by pathartl** [comment]
Put it on YouTube or something

**Comment by hamadoo14** [comment]
> Put it on YouTube or something

Here you go

https://www.youtube.com/watch?v=PX1tbZfREQo&feature=youtu.be

**Comment by pathartl** [comment]
Where BleemSync is located, go into the address bar and type `cmd` and then got enter. Command prompt will open in the current folder. Now type `BleemSync`. It should run and keep the output open.

**Comment by hamadoo14** [comment]
> Where BleemSync is located, go into the address bar and type `cmd` and then got enter. Command prompt will open in the current folder. Now type `BleemSync`. It should run and keep the output open.

it appears that this is the problem.
![capture](https://user-images.githubusercontent.com/39157374/50300883-cb10eb80-0496-11e9-82ee-fdad899441f6.PNG)

**Comment by pathartl** [comment]
From reading [this](https://github.com/dotnet/cli/issues/3907) it sounds like you need to run Windows updates. [Direct link to the specific update](https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot)
