### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by wolfrin** [pathartl/BleemSync#106]
I got a 64 SanDisk Fit USB Drive which I noticed two comments that people are using it just fine and I cannot get BleemSync to load it just keeps going straight to stock firmware and I dont know where I am going wrong I have downloaded the latest version and formatted the drive to FAT32 and ran the BleemSync app so any suggestions

**Comment by pathartl** [comment]
Make sure the volume name is SONY and the 028c18a9-ec4b-4632-b2cf-d4e20f252e8f exists. Also make sure the light on the front blinks.

**Comment by wolfrin** [comment]
The USB Drive is named Sony and the folder you listed is correct and the light on the USB drive just continuously blinks can it maybe have somthing to do with the adapter that connects the power cord to the wall?
________________________________

**Comment by wolfrin** [comment]
Either that or maybe something is wrong with my system if those two other people didnt have problems

**Comment by FyreAnt** [comment]
If you think its a power adapter problem, try another adapter. I am using one of the little white iphone bricks (the smaller ones). Works great.

**Comment by wolfrin** [comment]
I tried the brick that came with the nes classic and a phone brick I don't think it's because of the power cord
________________________________

**Comment by pathartl** [comment]
It has to be named SONY all caps. The light of the system should blink. If it's not, you did not install the payload correctly. Please review the readme.
