### ISSUE TITLE
Error message appearing when running BleemSync

### ISSUE THREAD

**Issue by liamgriffintest** [pathartl/BleemSync#109]
Hi!

After I've set up the game `bin` and `cue` files, and go to run BleemSync- I'm seeing an error appearing: "Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'BleemSync.Config.json' was not found and is not optional."

Here are the actions I'm taking:

![bsynch-issue-liam](https://user-images.githubusercontent.com/39333737/50254415-d7893b80-03e5-11e9-80de-8873e4057ec5.gif)

This is the command line error message:

![bsync-error-message](https://user-images.githubusercontent.com/39333737/50254503-2636d580-03e6-11e9-863c-97ec34b7ca8e.jpg)

Any advice welcome! And thanks for building this tool :)

**Comment by pathartl** [comment]
You have to run BleemSync from the directory the config is located in. Open Terminal, `cd /Volumes/SONY/BleemSync;./BleemSync`
