### ISSUE TITLE
Problem loading BleemSync

### ISSUE THREAD

**Issue by wolfrin** [pathartl/BleemSync#110]
![screenshot 8](https://user-images.githubusercontent.com/46005364/50256946-7732d380-03be-11e9-8107-c338f28516c8.png)
![screenshot 9](https://user-images.githubusercontent.com/46005364/50257014-dbee2e00-03be-11e9-8764-1b85cf4aa98c.png)
Everything is right and I followed the instructions do you think my playstation is defective I am in the return window to get another one

**Comment by wolfrin** [comment]
The light on the USB hub blinks on and off showing it is being read but the light on the console does not blink at all

**Comment by pathartl** [comment]
The folders have to be at the root of your flash drive. You have them in a BleemSync-0.4.1-win7-x86 folder.

**Comment by wolfrin** [comment]
what do you mean the root?
________________________________
