### ISSUE TITLE
4 Player Support through USB Hub

### ISSUE THREAD

**Issue by MaxLempira** [pathartl/BleemSync#112]
If could... Add Four Controller Support through USB Hub for games like Crash Team Racing, Crash Bash etc...

**Comment by whip28** [comment]
No

**Comment by MaxLempira** [comment]
yeah, I tried too with no result. But as far as I know, PCSX ReARMed support 4 Players, so I hope the PSC support it too

**Comment by mtrivs** [comment]
According to the link below, only the latest version of lr-pcsx-rearmed supports multitap functionality and is also reliant on RetroArch for it to work correctly.  Specifically, the ability to configure game-specific core options, as games which do not support the multitap will not detect _any_ input while the feature is enabled. The process described entails enabling multitap for the lr-pcsx-rearmed core and saving it as a game-specific core option.  Thus, when you restart the game from RetroArch, the multitap is 'detected'.

[https://github.com/retropie/retropie-setup/wiki/Playstation-1#multitap-3-8-player](https://github.com/retropie/retropie-setup/wiki/Playstation-1#multitap-3-8-player)

**Comment by swingflip** [comment]
Technically this is now possible in 1.0 with the inclsuion of RetroArch PCSX and a USB hub. 

Closing as feature is now supported
