### ISSUE TITLE
Games that Come with BleemSync Wont Start

### ISSUE THREAD

**Issue by wolfrin** [pathartl/BleemSync#113]
BleemSync is now working but when it loads it shows the two games that come with downlaoding the file Metal Gear Solid and Tony Hawks Pro Skater 2 but when I click to launch the games it makes the infamous sony startup noise but gets stuck at the playstation logo I can still access the menu and exit but I have tried multiple times loading the games but they wont load and the cover art is not showing for them either

**Comment by FyreAnt** [comment]
Those are not actually included games. They are just sample files with no actual game in them. You will need to furnish your own games for BleemSync to work.

**Comment by swingflip** [comment]
lol.

**Comment by rick2890** [comment]
Dude...wym it's not working?! LUL

**Comment by rick2890** [comment]
Follow the steps in GitHub, that's it!
