### ISSUE TITLE
Scrollable/smaller font/line wrapping for title text

### ISSUE THREAD

**Issue by khenzel** [pathartl/BleemSync#119]
For some titles with longer names it is impossible to tell what i'm selecting by title text. I.E. "Arcade's Greatest Hits - The Atari Collection vol 1" gets cut off at ""Arcade's Greatest Hits - The Atari Collec". I'm unable to distinguish between vol 1/2/3. 

Yes i have box art that can help here, but would be nice to some how be able to see the full text. Any of the 3 options in the title would correct this.

Considered "nice to have".

**Comment by pathartl** [comment]
You can try putting a newline character in the name `\n` otherwise there's not much we can do without trying to patch the ui_menu binary.

**Comment by khenzel** [comment]
Good idea. I'll give it a go on my next load and will report back the results here shortly.

**Comment by khenzel** [comment]
Negative. \n is showing up in the string. Sony must have set this as a verbatim string literal for title text.

I guess we are out of luck for this issue. We can re-open this later if something new emerges.

**Comment by harvestry-of-ghosts** [comment]
Just signed in to see if this had already been requested. Any updates? Was said to possibly work on 1.0.1 but it's not working on 1.1 & there's been nothing more said for 6 months. Would love to see this working, if possible. :)
