### ISSUE TITLE
Reset from controller combination?

### ISSUE THREAD

**Issue by Edjuh82** [pathartl/BleemSync#120]
Previous one was closed but to be honest entering the emulation settings isn't the same a button combination to get back to the game select screen so you can easily add a savestate to that UI. 

I find exiting the game via the emulation menu doesn't save the correct state to the save states. It saves a grey screen which crashes/ doesn't load the game if you load it (pressing the reset button on the PSC sets you back to the game select screen).

Is it possible that in a future build of bleemsync we can map a button combination that simulate the reset button of the PSC? Just like Hakchi2 (CE) has with their (S)NESC hack.

Perhaps this is already possible by adding some lines to a config file?

**Comment by PattonPlays** [comment]
This is being implemented in future releases.
