### ISSUE TITLE
System shuts down when pressing reset or going to any screen memory card etc.

### ISSUE THREAD

**Issue by Player1Login** [pathartl/BleemSync#121]
Pathartl is this being addressed? Really my only complaint can’t use save states or exit games without shutdown. 64gb San dusk cruzer glide 100+ 2.0 Keep up the great work! I used ps classic tool btw

**Comment by BoscoTheMan82** [comment]
Its related to your boxart, the images are too big. Scale them down to 226x226 then compress the png's using PNGGauntlet or PNGyu. This quickens up boot time as well.

**Comment by Player1Login** [comment]
You sir are amazing! I hope this is accurate I’ll report back after checking

**Comment by Player1Login** [comment]
Took several hours and I’m even using several 500x500 cover art photos but no longer getting the system shut down. Still is a slow boot since I didn’t compress all box art photos like you suggested but since it resets and puts resume spots flawlessly I’m content. Thank you Bosco! Merry Christmas
