### ISSUE TITLE
where is the almighty bleemsync.exe ...nowhere

### ISSUE THREAD

**Issue by mlpope** [pathartl/BleemSync#124]
i have turned off virus protection in case it is deleting bleemsync.exe but i still cannot find it in 0.4.0 or 0.4.1 or 0.3.2 or whatever version download i cant find it....as a matter of fact the folder that is described in tutorial videos and text tutorials where bleemsync.exe also has a bunch of other files in the same folder which i also do not see each time i redownload...i wish someone would help me out...im downloading using two different cell phones, (no wired or land line internet) but that shouldnt matter...im able to get everything except for the exe file

**Comment by mlpope** [comment]
am i somehow supposed to run this hack with out the exe file because it seems to be eluding me

**Comment by FyreAnt** [comment]
You’re using cell phones just for internet and tethering to a desktop PC right? I’m afraid your AV is likely still blocking it from what it sounds like. You should get a file that has to be extracted and there is a folder inside with all the files. If you are extracting the folder and still don’t see everything them it’s definitely your AV.

**Comment by mlpope** [comment]
no i am not tethering. ..using the browser on the cell phone

**Comment by mlpope** [comment]
no only downloading files straigt to the download folder on my cellphone and then i connect it to pc to drag and drop and then i try to use the bleemsync files utilizing my pc...i am able to do everything except run bleemsync.exe...i know how to use bin/cue and all the emulation goodness...i will double check to see if i have AV on my pc or not

**Comment by FyreAnt** [comment]
Don’t download to your phone. Tether your pc and download direct.

**Comment by mlpope** [comment]
sorry about multiple posts....just to be clear, i did everything except run bleemsync.exe...i figured i would try my flashdrive anyway and when plugged in to the classic and when it is turninv on it does the blinking light and all that goodness just that it goes to the regular screen with the pre packed 20 games instead of the 1 or 2 that i put on the flashdrive

**Comment by mlpope** [comment]
ive never tethered b4 but i will try it and also my pc/laptop is old and i hope it will ge ablevto use tethered internet connection because it is using windows vista so it may not ...idk...thank you i will try

**Comment by mlpope** [comment]
actually the cellphone i am using has no internet on it i am pulling wifi from my neighbor so i supposed i should just pull the wifi using the laptop

**Comment by mlpope** [comment]
i went to tags right beside the releases and then i downloaded a verion release from there...sorry to sound likecim a noob bug i thought i knew wherr to look...check the releases tsb right then look through them..x. each release has its own notes of what has been added/updated...the download links i dont see in the releases but when i check the tags i see the numbered version releases...and those are the sources which dont have what or al of what i needed, example being the exe file

**Comment by mlpope** [comment]
ok...WOW...i am an idiot...i just clicked on assests and voila!...ive been so close by it if it were a snake, i wouldve been bitten already...lol

**Comment by mlpope** [comment]
thanks for helping me out...ha
