### ISSUE TITLE
Games Not Starting: SONY Logo/Message Corrupted

### ISSUE THREAD

**Issue by MassimilianoCiccarelli** [pathartl/BleemSync#125]
First of all, many thanks for multiple joysticks on unique USB port support: now it works fine also for me, and it solved my corresponding pull request. Thanks !

I am currently running latest version of BleemSync, namely 0.4.1, and for some games, see below my list - I experienced the following scenarios.

The SONY log correctly appears once you select corresponding game from the main menu, but then - differently from other games that works fine instead - the screen remains freezes and you notice that the famous SONY sentence under logo image "Licensed by Sony Computer Entertainment America" now it appears fragmented, not well formatted, and sometimes even not on the same line as it should instead be.

At that time, as anticipated, the game is not starting and you are forced to shutdown/turn off the PS as you can not even go back to the main view/menu and try another game.

Here it is the (current) list of these "not working" games downloaded from sites like https://emulator.games and https://romsmania.cc.

FIFA 2002 [SLUS-01408].rar
FIFA Soccer 2005 [SLUS-01585].rar
Gran Turismo 2 - Arcade Mode [SCUS-94455].rar
Mortal Kombat 4 [SLUS-00605].7z
Spiderman [SLUS-00875].rar
Tomb Raider 2 [SLUS-00437].7z
Duke Nukem - Time to Kill [SLUS-00583].7z
Metal Slug X [SLUS-01212].7z

and this is the list of my tools, running on Mac OS, I use for creating the above games packages.

unecm - to uncompress typically files .img made available as .img.ecm
ccd2iso - to convert games made available as .img , .ccd , .sub and .cue into a unique .iso file
power2iso - to covert the .iso into .bin/.cue files which represent the accepted format

To be noted that none of the above tools, when executed on above games, produces error/warning messages.

Any idea/suggestion ?

Many thanks in advance :-)

**Comment by FyreAnt** [comment]
I had this issue with Gran Turismo 1. I re-downloaded the rom and tried again and it was fine. Check out the site CoolRoms. Also, I had several files that didn’t work once converted from img. So, try to download from a placs that provides them in bin/cue already (like the one mentioned above).

**Comment by MassimilianoCiccarelli** [comment]
Hi FyreAnt, many thanks. 

I will give it a try, and back to you later on accordingly

Thanks !

**Comment by iRyanKGT** [comment]
I would also venture to say it's the ROM itself that's bad.

I can confirm that both Spiderman and Mortal Kombat 4 boot up and work fine on my classic.

**Comment by pathartl** [comment]
If there's an issue starting the game and the text under the PS logo, it's usually due to bad dumps. BleemSync only deals with being able to launch the games from the UI and this is not in scope of the project.

**Comment by panaphobic** [comment]
I also am having this issue. I believe it's from any PS1 game that I have converted from an .iso or .img file to .bin/.cue and I can't seem to find a program that will convert them properly. I've tried PowerISO, WinISO, ImgBurn and AnyBurn. All seem to result in the same thing. The PlayStation logo when first booting the game pops up, but the "Licensed by Sony Computer Entertainment America" wording is messed up.

![20190101_095643](https://user-images.githubusercontent.com/46224783/50576829-5324b880-0de8-11e9-8289-81f3fe67b430.jpg)

Every single game I've tested that doesn't work, had it like this. I can still hit Select & ▲ to get the PCSX menu to show up and to exit the game, but it never loads them. The one I really want is Breath of Fire 3, but I can't seem to get that to work. The files I've found for it online comes with 2 .bin files (track 1 and track 2) plus a single .cue file that references both of them. The game itself is just 1 disc, and I own it (see the pic below). I just can't seem to get that working properly. Anyone know how to get it working right?

![20190101_171327](https://user-images.githubusercontent.com/46224783/50576845-ca5a4c80-0de8-11e9-9ed3-f17e4c28d147.jpg)

Also, what is everyone using for a converter to convert .img/.iso files to .bin/.cue files and actually have them work on the PSC?

**Comment by FyreAnt** [comment]
> I also am having this issue. I believe it's from any PS1 game that I have converted from an .iso or .img file to .bin/.cue and I can't seem to find a program that will convert them properly. I've tried PowerISO, WinISO, ImgBurn and AnyBurn. All seem to result in the same thing. The PlayStation logo when first booting the game pops up, but the "Licensed by Sony Computer Entertainment America" wording is messed up.
> 
> ![20190101_095643](https://user-images.githubusercontent.com/46224783/50576829-5324b880-0de8-11e9-8289-81f3fe67b430.jpg)
> 
> Every single game I've tested that doesn't work, had it like this. I can still hit Select & ▲ to get the PCSX menu to show up and to exit the game, but it never loads them. The one I really want is Breath of Fire 3, but I can't seem to get that to work. The files I've found for it online comes with 2 .bin files (track 1 and track 2) plus a single .cue file that references both of them. The game itself is just 1 disc, and I own it (see the pic below). I just can't seem to get that working properly. Anyone know how to get it working right?
> 
> ![20190101_171327](https://user-images.githubusercontent.com/46224783/50576845-ca5a4c80-0de8-11e9-9ed3-f17e4c28d147.jpg)
> 
> Also, what is everyone using for a converter to convert .img/.iso files to .bin/.cue files and actually have them work on the PSC?
> 
> _**Edit: I also cannot seem to make my own iso from it as my computer does not recognize the disc as even being in the DVD drive. I tried a few different programs suggested on the internet, but nothing works for this disc.**_

Every single time I ran into this, it was because the game files are damaged. Where are you getting your games from?
