### ISSUE TITLE
/media/lolhack umount: can't unmount /data: Device or resource busy

### ISSUE THREAD

**Issue by pwasem** [pathartl/BleemSync#127]
After booting with my usb stick (64GB) inserted the "default ui / games" are loading and shown shortly.
Then the console shuts down / crashes (orange led).

During boot the led is blinking green and orange (as expected).
Though there seems to be a delay before the led starts blinking.
(With other usb sticks it started flashing immediately)

lolhack.log has this content
```
killall: showLogo: no process killed
...
Successfully inserted 25 games
/media/lolhack
umount: can't unmount /data: Device or resource busy
```
It seems like the script is being executed too late and therefore crashing as default games / ui have already been loaded
Maybe mounting / loading the usb stick takes to long.

**Comment by elbundz** [comment]
I face the same issue.
After testing with several other USB sticks, I noticed that this issue happens at my newer/bigger sized USB sticks, but it did not happen at the old sticks.

**Comment by GMMan** [comment]
The boot script needs to `cd` to somewhere outside `/media` before it leaves.

**Comment by PattonPlays** [comment]
Hey @pwasem   if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
