### ISSUE TITLE
Titles only no working game.

### ISSUE THREAD

**Issue by DevilTechStudios** [pathartl/BleemSync#129]
So I have gotten the games to load on the USB drive. They appear in on the screen but no image and when I click on them they don't do anything. The name shows along with the company and year. Any help would be great. I honestly bought the Classic just because we can hack it now and add all the games we want to play right to it. I know we can use other emulators to do this but it makes it easy for me and my little sister to play when we can just plug it in the tv and that's it. 
![img_20181224_131159](https://user-images.githubusercontent.com/46112950/50406698-3f40dd00-077e-11e9-9dd9-9e420c5b8613.jpg)

**Comment by safetychief8** [comment]
Save the images as .PNG files and name them the same name as the.CUE file in the GameData folder, and make sure the .BIN file name also matches the .CUE file. Also, make sure the "discs" line in the game file name also matches the .CUE file name

**Comment by safetychief8** [comment]
PlayStation database website has the correct info for every game including pics

**Comment by DevilTechStudios** [comment]
I've done that with the pics and the picture provided is what it's showing me. I've done everything step by step including making sure the pictures are png and I've even scaled them all down to 226x226 as well. Sadly all my other USB sticks do not work except this one. I can always take a picture of how I got the files set up and see if that can help solve this.

**Comment by FyreAnt** [comment]
Did you rename any of the files from when you downloaded them? I would guess the Cue file contents are referring to a different name. What I mean is if you downloaded "Twisted Metal 2 (USA) (1.1).bin" did you rename it to something like "Twisted Metal 2.bin". If you do this, the Cue file you have will be broken unless you edit it in Notepad and fix the reference to the BIN file..

**Comment by DevilTechStudios** [comment]
I don't think I did but I will try and see if that fixes the problem

**Comment by hofabass** [comment]
I had the same problem. It was the USB stick - when I changed it, then everything worked.

**Comment by DevilTechStudios** [comment]
What stick are you using now then? The only one of mine I got to work was the SanDisk Cruzer 4GB.

**Comment by hofabass** [comment]
Transcend JetFlash 810 16 GB USB 3.0 Flash Drive TS16GJF810 look here for PlayStation Classic Compatible USB Storage Devices https://docs.google.com/spreadsheets/d/1saluXC8jfWhOVT9-JXj1Kd62hL2WGtCX6zErY6AElco/edit#gid=0

**Comment by DevilTechStudios** [comment]
Yeah I used the list. Though all of mine are not on the list and as it's still not 100% I've seen others say sticks that aren't supposed to work do for them. So I am looking at grabbing another new stick. Though I think I am going to still stick with trying the 2.0 since all my 3.0's didn't work. The one that did slightly work as shown in my picture is a 2.0 I believe.

**Comment by safetychief8** [comment]
I'm using a 128gb SanDisk micro SD card with a USB Adapter.

**Comment by DevilTechStudios** [comment]
So it wasn't the Cue files like was suggested to me. It turns out that all my USB's 2.0 and 3.0's all needed the USB hub to be plugged in. Now everything works so I thank you all for the support you gave me.

**Comment by 1984doubledragon** [comment]
>           So it wasn't the Cue files like was suggested to me. It turns out that all my USB's 2.0 and 3.0's all needed the USB hub to be plugged in. Now everything works so I thank you all for the support you gave me.

**Comment by 1984doubledragon** [comment]
DevilTechStudios I am having the same issue. I have watched countless tutorials and keep landing on this same problem. I noticed my computer doesn't label it as Game.ini but only Game and and everyone keeps saying its suppose to say Bleemsync.exe while mine only says Bleemsync so I keep thinking this is the issue. What exactly did you do different to get the game to load ? Any help would be appreciated as this has been driving me nuts because  I know its a stupid issue.

**Comment by pathartl** [comment]
Please post images of your file structures. Describing the issue only goes so far. I'm still convinced this is a configuration issue and not an actual bug with the application.

**Comment by DevilTechStudios** [comment]
The Game.ini file was found in the GameData folder. the Bleemsync.exe is in the bleemsync folder just have to scroll down a little bit to find it. I can post some pics here in a minute of where both are located if needed. When you add a game to the folders you add them to the folders marked 1 and 2 you add new ones past that and need to have the GameData folders in them as well.

**Comment by DevilTechStudios** [comment]
Well 2 things. 1 I have followed everything you posted to do when putting them on the USB. I have 3 out of my 6 games working. I am not saying its a bug but there might need to be some further explanation of how to handle games like Brave Fencer Musashi or Parasite Eve. I am having issues with games like that and  Future Cop LAPD. they show up on the screen well just the names and publisher and year no pic and when clicked on the game does not load. Yes I have the cover art and yes it's 226x226PNG so I know that's not it. 2, I have 3 out of 6 games working Diablo, Tomba!, and Medievil. All work great with no errors. It makes no sense to me that I can get 3 to work but not all 6.

**Comment by pathartl** [comment]
I simply don't have the time to test the support for various games. In order to properly give you an answer I need a look at the structure on your USB device and some samples of the Game.ini for games that are not working.

**Comment by DevilTechStudios** [comment]
I will be posting a few pics here in one second. Just an FYI for how they look in the photos this is like my 20th attempt on trying different ways of labeling the discs. I have even tried doing their SCUS and SLUS codes and nothing worked.

**Comment by 1984doubledragon** [comment]
I am trying silent hill for example and have tried it 2 different ways.
Game
pcsx.cfg
SLUS-00707.bin
SLUS-00707.cue
SLUS-00707.png
And 
Game 
pcsx.cfg
SilentHill.bin
SilentHill.cue
SilentHill.png

**Comment by pathartl** [comment]
> I am trying silent hill for example and have tried it 2 different ways.
> Game
> pcsx.cfg
> SLUS-00707.bin
> SLUS-00707.cue
> SLUS-00707.png
> And
> Game
> pcsx.cfg
> SilentHill.bin
> SilentHill.cue
> SilentHill.png

Again, I need screenshots and Game.ini samples.

**Comment by FyreAnt** [comment]
Deviltech, I can help you since Pat is a bit busy (hopefully working on 5.0! Lol)

Ok, one issue at a time. First, multi game discs like parasite eve - Do you have one bin file and one cue file for disc one as well as one bin file and one cue file for disc two? If so, please copy and paste the file names in a post. 

Second, lets get you’re cover art fixed. In order for the cover art to display correctly, it MUST be labelled the EXACT same as the Disc 1 files. So if its ParasiteEveD1.bin and ParasiteEveD1.cue then the PNG needs to be named ParasiteEveD1.png. Example, If you have that exact name and the P isn’t capital in the png name but is capital in the bin/cue files, it will NOT work.

**Comment by FyreAnt** [comment]
1984doubledragon, I know what your issues is. Your files likely have double filename extensions on them. What version of windows are you on? I’ll tell you how to show the file extensions so you can see what I mean

**Comment by DevilTechStudios** [comment]
>           Deviltech, I can help you since Pat is a bit busy (hopefully working on 5.0! Lol)
> Ok, one issue at a time. First, multi game discs like parasite eve - Do you have one bin file and one cue file for disc one as well as one bin file and one cue file for disc two? If so, please copy and paste the file names in a post.
> Second, lets get you’re cover art fixed. In order for the cover art to display correctly, it MUST be labelled the EXACT same as the Disc 1 files. So if its ParasiteEveD1.bin and ParasiteEveD1.cue then the PNG needs to be named ParasiteEveD1.png. Example, If you have that exact name and the P isn’t capital in the png name but is capital in the bin/cue files, it will NOT work.

I got Parasite Eve to work don't know how. Which also I had already did all that beforehand and it did not work. I do not know what I did differently to get it to work now but I will post the pics here in a bit just trying out Parasite Eve seeing if there is any issues also trying to find a save point lol.

**Comment by 1984doubledragon** [comment]
When i click in the GameData folder mine does not says Game not Game.ini and the same thing with the Bleemsync application located in the Bleemsync folder it only says BleemSync not BleemSync.exe. Im runing windows and have downloaded the windows package and rhis is what it gives me. I even went as far and tried linux and the osx one as well.

**Comment by 1984doubledragon** [comment]
FyreAnt Widows 10

**Comment by pathartl** [comment]
If you are not going to provide the materials I am asking for, I'm afraid I cannot help you and will ask you to stop requesting help until you can produce what I'm expecting.

**Comment by FyreAnt** [comment]
1984doubledragon, Go the the screen where you see your files, go to the “View” tab up top, (or press Alt+V) towards the right, check the box for “File name extensions”. Now you will see the full file name with the .ini, etc.

**Comment by 1984doubledragon** [comment]
What files are we talking about exactly?

**Comment by FyreAnt** [comment]
Any folder really. You can go to the bleemsync folder, or the folder where you bin files are. The change will effect ALL folders when you make it so doesn’t matter where you are as long as you are in a folder

**Comment by 1984doubledragon** [comment]
Sorry man bare with me im new to doing this

**Comment by 1984doubledragon** [comment]
Got it thanks man for the help, I would have never of thought of that. Is there anything else I need to do or do you think this should fix it the entire problem ?

**Comment by FyreAnt** [comment]
That will not “fix” anything. It will simply allow you to see the part of the file mame that was “hidden” but actually present all along. Now, go check your file names. I’m willing to bet yiu have some that are like SilentHill.bin.bin that need to be fixed.

**Comment by DevilTechStudios** [comment]
![img_20181228_180923](https://user-images.githubusercontent.com/46112950/50532798-8a872280-0ad3-11e9-98c4-3a4a1d92ce9e.jpg)
![img_20181228_180944](https://user-images.githubusercontent.com/46112950/50532799-8b1fb900-0ad3-11e9-97ec-10e947ea99a6.jpg)
![img_20181228_180953](https://user-images.githubusercontent.com/46112950/50532800-8b1fb900-0ad3-11e9-939e-d971adb4b41d.jpg)
![img_20181228_185627](https://user-images.githubusercontent.com/46112950/50532801-8b1fb900-0ad3-11e9-933d-08851baf54bf.jpg)
![img_20181224_131159](https://user-images.githubusercontent.com/46112950/50532802-8b1fb900-0ad3-11e9-825b-17d5d5fb80e5.jpg)
![img_20181228_180834](https://user-images.githubusercontent.com/46112950/50532803-8bb84f80-0ad3-11e9-9179-afcd88d48780.jpg)
![img_20181228_180854](https://user-images.githubusercontent.com/46112950/50532804-8bb84f80-0ad3-11e9-83e9-b5ca37a4ea97.jpg)
![img_20181228_180902](https://user-images.githubusercontent.com/46112950/50532805-8bb84f80-0ad3-11e9-8292-435b24e9eaee.jpg)
![img_20181228_180915](https://user-images.githubusercontent.com/46112950/50532806-8c50e600-0ad3-11e9-9ed9-51c0a0ef0b0f.jpg)
So as I said Parasite Eve works now but the others still don't. I changed out Future Cop for Dino Crisis and it doesn't work either. As for Parasite Eve's PNG I will see if I can edit again to fix it so it shows up now. As for the Brave Fencer Musashi I still do not know what is wrong and as for Dino Crisis same thing as Brave Fencer its multi track. This would also help knowing so I could add Twisted Metal 3 as its has a ton of track bin files.

**Comment by DevilTechStudios** [comment]
So ignore the photo showing the broken Tomba! game that was from the older post some how it got in there.

**Comment by FyreAnt** [comment]
DevilTech, you should download a program call CDMage, and meege your multi “track” bin files into one file. It will save you a lot of headache.

**Comment by 1984doubledragon** [comment]
Gotcha I will check again

**Comment by DevilTechStudios** [comment]
Sweet will do because yeah Twisted Metal Is nuts for that and it might help with the other games as well. As for Future Cop LAPD could it be because the CUE and BIN file have it as Future Cop L.A.P.D. and being that BleemSync can't have you using the . in the disc titles I don't think. This would also help me solve Dino Crisis as well I feel as the game is filed under Dino Crisis (v1.1)

**Comment by DevilTechStudios** [comment]
Hey FyreAnt how do you use CDMage to combine all the bins? When I try to open them in it, it says wrong file type when I open the cue file it works but it just shows me the tracks that are on it. How do you make the bins into one file from there? Or do I need PowerISO for it?

**Comment by DevilTechStudios** [comment]
Wait I think I figured it all out lol.

**Comment by FyreAnt** [comment]
Yes, you select the cue file. Follow this guide: http://www.ps2-home.com/forum/viewtopic.php?t=41

**Comment by 1984doubledragon** [comment]
Lol i managed to get the Resident Evil 1.5 hack up and runing. I guess game hacks and translations are now in the equation !

**Comment by ShadowHunter69** [comment]
With games that have multiple tracks the .CUE file has to also say (Track 01) at the end I've noticed in that picture of Brave fencer yours doesn't I had this issue with Mortal Kombat Trilogy but when I renamed the .CUE file to Mortal Kombat Trilogy (Track 01).cue the game loaded fine and also just to make sure double check in the cue file has all the tracks listed with in which it should or the game won't work hope this is a help.

**Comment by ShadowHunter69** [comment]
Just track 1 your folder should look something like this 

Brave Fencer Mushashi (Track 1).bin
Brave Fencer Mushashi (Track 1).cue
Brave Fencer Mushashi (Track 1).png
Brave Fencer Mushashi (Track 2).bin
Brave Fencer Mushashi (Track 3).bin
Brave Fencer Mushashi (Track 4).bin
Game
pcsx
