### ISSUE TITLE
which usb stick should i use?

### ISSUE THREAD

**Issue by joran373** [pathartl/BleemSync#130]
i just got my ps1 classic and tried to hack it through bleemsync. But it seems the usb sticks i have at home arent compatible.  Now im looking to buy one that would work. But im not sure which one i would go for. Preferably a cheap one.  Could someone post a name and a pic off a usb stick that works? I know there is a spreadsheet but im pretty bad with technology and it would be a bummer if i buy one that doenst work. Thx in advance.

**Comment by mikewolfskin** [comment]
I can confirm that a Micro Center USB 3.0 branded 16GB Thumb Drive works. You can buy them on Amazon or in store at Micro Center. I assume the bigger once work to but have yet to confirm this. They rang from $9.99 to $34.99.  Hope that helps.

**Comment by joran373** [comment]
Thanks for the tip :)

**Comment by hofabass** [comment]
https://docs.google.com/spreadsheets/d/1saluXC8jfWhOVT9-JXj1Kd62hL2WGtCX6zErY6AElco/edit#gid=0 this is the list of PlayStation Classic Compatible USB Storage Devices
