### ISSUE TITLE
Playstation com puter entertain ment system won't show properly and system freezes

### ISSUE THREAD

**Issue by Matamorte** [pathartl/BleemSync#131]
Hi, I have currently have 5 games installed on my USB stick and only one does not work and it is Dragon Warrior VII : the only multidisc game that I have in my library. The letters of the Playstation logo are spread with random spaces and after this the system freezes. I changed the names of both disc : should I have kept the serial names of the discs... or is it something else? Thanks in advance!

**Comment by mikewolfskin** [comment]
This is just a wild guess here but based on own research on the matter this tends to mean that your ROM file is corrupted or faulty. I highly recommend downloading the same Emulator PCSX-Reloaded on your PC and testing the same file on the PC. If the ROM file also does not work on your PC the file is likely the fault.  If it works on the PC but not the PlayStation Classic something is wrong with the way you wrote the code. Remember BIn and Cue files need to be the same name and are letter sensitive.  So for a 4 Disc game set the BIN and Cue need to be the same for Disc 1, then the Bin and Cue most be named the same as what you called em for Disc 2. An example

(Disc 1)
Bin:Example Disc 1
Cue:Example Disc 1
Picture (Cover Art) Example Disc 1 (PNG)

(Disc 2)
Bin:Example Disc 2
Cue:Example Disc 2

(Disc 3)
Bin:Example Disc 3
Cue:Example Disc 3

(Disc 4)
Bin:Example Disc 4 
Cue:Example Disc 4

Don't forget to Edit the labeled Game.ini file to say

[Game]
Discs=Example Disc 1,Example Disc 2,Example Disc 3,Example Disc 4
Title=Example Game
Publisher= Just An Example
Players=1
Year=Today?

File save

and last but not lest run BleemSync.exe

(As a note with multi Disc games I'd test each Disc ROM on PCSX on your PC first before ruining em on PS1 Classic.) Hope that helps.
