### ISSUE TITLE
having trouble running bleemsync.exe

### ISSUE THREAD

**Issue by mlpope** [pathartl/BleemSync#132]
ive all the folders/files in the root of my usb drive and tried opening bleemsync.exe and i get this message...
Entry point not found, the procedure entry point RaiseFailFastException could not be located in the dynamic link library KERNAL32.dll...

Now, just for the record i am running a 10 year old laptop with windows vista ;i sure wish i was running at least windows 7.  is it possible i am missing a certain.dll file or if i do have that file maybe it is an older one which hasnt been updated...idk...oh the bleemsync.exe app has to be on the flashdrive when i execute open up that file, correct?...thanks for all u fellas are doing

**Comment by mlpope** [comment]
is it possible that i may have to use command prompt to open up the bleemsync.exe once i get the KERNAL32.dll issue resolved?...like before, thanks again ...i really cant wait to get this working, yall are doing great things here...i understand some code, but not enough to write programs...and i think i am pretty decent getting around

**Comment by pathartl** [comment]
Windows Vista and earlier is unsupported, sorry.
