### ISSUE TITLE
Multi track bin games

### ISSUE THREAD

**Issue by Ricajin** [pathartl/BleemSync#133]
Hello I'm having somewhat of an issue trying to figure out how can a multi track bin game be configured in the game data folder any tips are gladly appreciated thanks!

**Comment by Rion-Kaneshiro** [comment]
I have several games with multiple tracks and if the cue file properly contains them, you only need to enter the first track as the disc in the config file.

**Comment by Gab-75** [comment]
As far as I know, the "Discs" name in the "Game.ini" file refers to cue file, so (as Rion-Kaneshiro wrote), if the cue file has been filled in correctly, no complications should arise...
in any case, if you don't like too many files in a single folder, you can convert the multi track iso in a single "bin" with CDmage! ;)
https://www.videohelp.com/software/CDMage

**Comment by Ricajin** [comment]
Many thanks! I will work and test both options out
