### ISSUE TITLE
Analog Support

### ISSUE THREAD

**Issue by abelogan** [pathartl/BleemSync#134]
Is there any way to change the controller config file to support analog controllers (perhaps with a CronusMax PLUS) ??

**Comment by jzodieru118** [comment]
Yes I’m interested in this too! I added twisted metal 3 finally got it working but hard to play without my analog!

**Comment by jzodieru118** [comment]
I got a couple controllers that are usb wireless that have analog so they would plug right in if the console would respond to it

**Comment by abelogan** [comment]
Anyone know if one of these will give us right analog stick support?

https://www.amazon.com/Wireless-Bluetooth-Adapter-PlayStation-Classic-Controller/dp/B07L334WXC/ref=sr_1_2?ie=UTF8&qid=1546292430&sr=8-2&keywords=8bitdo+playstation+classic

**Comment by PattonPlays** [comment]
This is being implemented in future releases.
