### ISSUE TITLE
Game files can't have commas in the filename

### ISSUE THREAD

**Issue by pathartl** [pathartl/BleemSync#135]
This line needs to be fixed I think https://github.com/pathartl/BleemSync/blob/master/BleemSync.Services/GameService.cs#L74

**Comment by pathartl** [comment]
Should be using .StringValueArray instead of .StringValue probably. It'd allow `DiscIds="Disc, The"` and multi-discs would look like `DiscIds="Disc, The", "Disc 2, The"`

**Comment by MaxLempira** [comment]
same happening with ® & ™ characters

**Comment by pathartl** [comment]
Shouldn't be an issue with 1.0.0 anymore.
