### ISSUE TITLE
Issue when launching game from classic menu using bleemsync hack

### ISSUE THREAD

**Issue by Stephen7700** [pathartl/BleemSync#137]
Hi When I launch a game from the classic menu using hack created bye bleem sync I get a 5second pause and then nothing happens.

Please someone tell me what I am doing wrong and how I can fix it.

From: Stephen

**Comment by alexandrubb23** [comment]
Hey Stephen,

Could you please tell us which game you are trying to run?

**Comment by Stephen7700** [comment]
Spiderman ps1

**Comment by alexandrubb23** [comment]
> Spiderman ps1

I suppose you have a black screen... Did you tried different game?

**Comment by Stephen7700** [comment]
No I dont have a black screen it loads up to playstation classic menu and
then click x to start game and I get a 5second waititme and then nothing
happenes.

**Comment by alexandrubb23** [comment]
Ok. Be sure you spiderman.cue file has the same name with the .bin file

**Comment by Stephen7700** [comment]
ok should it be Spider-Man.bin in the cue file or it be Spider-Man

**Comment by alexandrubb23** [comment]
Do you have a .cue fie for that game?

**Comment by Stephen7700** [comment]
yes
![capture---1](https://user-images.githubusercontent.com/46170751/50459200-20397b00-0937-11e9-830f-589daa6d4908.JPG)

**Comment by alexandrubb23** [comment]
Should work...

**Comment by Stephen7700** [comment]
Ok I will test now and let you know soon if doesn't thanks again for your help.

**Comment by alexandrubb23** [comment]
When your test was failed, did you have the .cue file?

**Comment by Stephen7700** [comment]
yes

**Comment by Stephen7700** [comment]
but not inside the cue file it was Spider-Man not Spider-Man.cue inside the cue file

**Comment by alexandrubb23** [comment]
And, how is it now?

**Comment by Stephen7700** [comment]
the problem that occurs when pressing x to launch just tested now

**Comment by Stephen7700** [comment]
I have also tried with crash bandicoot and the same issue

**Comment by alexandrubb23** [comment]
Let me test the same game on my own PS1. brb...

**Comment by Stephen7700** [comment]
ok thanks

**Comment by alexandrubb23** [comment]
Did you format your USB stick as they says? (FAT32/SONY label)

**Comment by Stephen7700** [comment]
No every game ive tried same issue do you have anyway for me to send you video of thye problem

**Comment by alexandrubb23** [comment]
I just contacted you on skype...

**Comment by Stephen7700** [comment]
no skpe but I will email you the video

**Comment by alexandrubb23** [comment]
> no skpe but I will email you the video

Do you have my email address?

**Comment by Stephen7700** [comment]
no

**Comment by alexandrubb23** [comment]
give me yours

**Comment by Stephen7700** [comment]
Hay can u help me fix this so I can play the games

**Comment by Stephen7700** [comment]
HI thank you I will test it thanks again and why did you block my email.

**Comment by pathartl** [comment]
Closing this. There's no actual bug related to this, is a user issue, and should be handled through some other medium.
