### ISSUE TITLE
Start button on controllers not working with USB mounted

### ISSUE THREAD

**Issue by brianhammerhand** [pathartl/BleemSync#140]
Weird issue where the controller's START button won't register only when USB drive is mounted (with 3 games only to be safe). Games load and run fine and fast when USB is mounted.  I tried 3 completely different games with the same result. Interesting thing is that the directional controls do actually work in-game, allowing me to select "NEW" or "LOAD" game for example for games on the USB drive.  However the START button won't work/register on any game.  I changed controllers to be sure it was not an issue with one of them (it was not), and also confirmed the START button works perfectly fine with the games included on the internal memory.  So this seems to be limited to the mounted USB/Bleemsync setup.

**Comment by MadBobUK** [comment]
I have experienced the same issue, using retroarch to load same content allows start button.

Also Select+Triangle does not work for config menu. I have the bootmenu retroarch/BleemSync! setup

**Comment by brianhammerhand** [comment]
Thanks I heard about retroarch but it's not in the basic Bleemsync! setup so I'll look into it.

**Comment by elbundz** [comment]
I faced this issue also with version 0.4.1.
After having a look into the log-files, I noticed some issue with this file "pcsx.cfg" in every game.
So I found the following workaround:
I copied the file "pcsx.cfg" from BleemSync 0.3.2 into every game folder and overwrite the "pcsx.cfg" file from version 0.4.1. After this the START button worked again and Select+Triangle was also useable.

**Comment by MadBobUK** [comment]
Tried that and it didn't work. I found another fix:

Delete the pcsx.cfg and game.ini file (I also deleted the png cover art) from each game folder. then run the BleemSync.exe which creates the game.ini and downloads a .png file.

everything worked great after that.

**Comment by brianhammerhand** [comment]
Move this to CLOSED please. I found that by painstakingly checking each .BIN file for corruption and using a new USB drive from the compatibility spreadsheet I no longer have this issue.  I was converting ISOs to CUE/BIN files with a program that was apparently corrupting them just enough to cause issues, and my USB drive was laggy.  And of course as MadBobUK mentioned above I re-ran Bleemsync with a new set of files.

**Comment by willshorty** [comment]
Before you close it could you please advise what program you are now using to convert iso to cue / bin files ?

**Comment by brianhammerhand** [comment]
I am using ISO Buster now but to be honest the easiest thing was to find those originally in a BIN CUE format already.

**Comment by brianhammerhand** [comment]
I was using "AnyBurn" prior to that, and the corruption could often be seen as early as the startup screen where the text below the Playstation logo would be off-center / truncated.

**Comment by brianhammerhand** [comment]
OK I will check it.  My luck with converting files and having them still be able to use the "Start" button is not great, though at least all the BIN files now load fully.  Finding files already in BIN/CUE format seems to be key to guaranteed success.

**Comment by brianhammerhand** [comment]
I found a solution to my issue where games persistently lost any input but the directional control  -- **I moved the USB drive to "port 1" and now I can use the controller "Start" and other buttons.**

**Comment by brianhammerhand** [comment]
I am not sure that technically this is a Bleemsync issue, it seems it may be related to a power requirement difference between port 1 and 2 perhaps?  In any case, moving the controller to port 2 doesn't seem to have any negative impact so far in games I've tried - I suppose it is still seeing it as Port 1 since it's the only controller.
