### ISSUE TITLE
Copied all files to FAT32 Drive, PSC Still boots to Stock Boot Screen

### ISSUE THREAD

**Issue by Namander** [pathartl/BleemSync#142]
I've tried this on 2 separate Flash Drives and I'm still getting the same issue. I added 2 games in sequential order, ran Bleemsync.exe, copied to flash drives... I unplugged the power, inserted the flash drive, plugged power back in, but it still boots to stock. Not sure what I'm doing wrong.

**Comment by ExSOLDIER1** [comment]
@Namander What kind of Flash Drive are you using and how old is it? Most 3.0's dont work because they draw too much power so you would need a powered USB hub for most of those. Also are you seeing the power light flash while the usb is inserted? If not then it sounds like the Flash Drives themselves are incompatible.

**Comment by jhusch77** [comment]
I have the same issue, USB drive lights up, counted 12 orange flashes of the power LED once powered on and it boots straight to the stock GUI

**Comment by pathartl** [comment]
You need to post something like logs. Without that we have no idea what it could be.

**Comment by thatpaulallen** [comment]
How do I access a log to post?

**Comment by pathartl** [comment]
They should be in System/Logs or System/UI

**Comment by jhusch77** [comment]
At what point do the logs get written? After the first failure (so first time system boots to usb, system powers off after blue safety warning screen), no log files in either location.


Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by chri54tkins** [comment]
I also have the same issue.  Have formatted several USB drives to FAT32 (quick format and longer process also) and have followed instructions meticulously however the system never recognises the USB drive and always boots to the regular menu system.  I purchased my PlayStation Classic in Europe, is that significant, is there a feature on Euro devices preventing alternative boot?  The drives I have used so far are a SanDisk Ultra USB 3.0 32 gb, a SanDisk Cruzer 4gb (I think USB 2.0) and some free ones from exhibitions that are likely to be USB 2.0  

Is there a list of known working USB drive models and sizes?  Would be good to know of one that has been proven to work.

Thanks to anyone in advance for their help.

**Comment by SirXen0** [comment]
Same issue, tried using powered USB hubs to see if it's a power issue (USB lights up plugged in, doesn't boot BleemSync), but they never detect the USB drive or controllers through the hubs.

**Comment by chri54tkins** [comment]
I am successfully using a 32GB Sandisk Ultra USB 3.0 (worked initially with just the one game)

The major difference is that I have now added a .LIC file to each game folder with the same name as the .BIN file. There is nothing in the .LIC file but it seems to work. I now have Gran Turismo, Spyro and Soul Blade working.

Still reckon that some .BIN will just refuse to play.  Maybe that is down to the creation process.

So lots of trial and error put certainly some progress now.  I can now work to establish a PlayStation Classic the way it should have been made.  And I also have the original the way it was if I pull out the drive and reboot.  Fantastic.

**Comment by chri54tkins** [comment]
A further refinement... If .BIN are not working you can modify the related .cfg file e.g. "G:\Games\5\GameData\pcsx.cfg" to make the game a different region.  The default is '0'.  I modified this one to '2' and got my .BIN file to work.  Trial and error here I think but following info may help.

Extract from Wikipedia
https://en.wikipedia.org/wiki/PlayStation_models

_Region codes
The last digit of the PlayStation model number denotes the region in which it was sold: 
0 is Japan (Japanese boot ROM, NTSC:J region, NTSC Video, 100 V PSU)
1 is USA/Canada (English boot ROM, NTSC:U/C region, NTSC Video, 110 V PSU)
2 is Europe/Australia/PAL region (English boot ROM, PAL region, PAL Video, 220-240 V PSU)
3 is Asia (English boot ROM, NTSC:J region, NTSC video, Wide range 110-240 V PSU)_

Screenshot extract of my modified .cfg file

![image](https://user-images.githubusercontent.com/46231645/50543171-d4e9cb80-0bc7-11e9-8416-df38161c4648.png)
 
Now got five games prepared and displaying.
