### ISSUE TITLE
Cant save on player 2 memory slot.

### ISSUE THREAD

**Issue by Boomeryang** [pathartl/BleemSync#144]
So I was playing Gauntlet legends and I wasn't able to the save player 2 character? it just said that there was no memory card connected but I was able to save player one with no problem. Seems like i need two memory card on both slots to be able to save both player.

**Comment by pathartl** [comment]
Should be able to go into the PCSX menu and connect a second memory card. We'll look at adding this in the future.

**Comment by swingflip** [comment]
I can look at adding this as a part of a global stock cfg patch in the payload but need to check if this is feasible with the playstation classic's stock save system. Let alone our synced RA PCSX save system
