### ISSUE TITLE
Can't get bleemsync to add games and database does not appear in the system file?

### ISSUE THREAD

**Issue by DrGreenthumb0099** [pathartl/BleemSync#146]

**Comment by pathartl** [comment]
Need more details than that bud

**Comment by joeyswannick** [comment]
I am having the same issue, When I got the the Bleemsync application (to add games to the presumed system) I dont get a new file added inside the system one? this one was the tutorial i was watching added a new file, which showed inside it, that the games had been added. so when i plug in the USB, it comes up with the titles etc, but the games dont actually load or play

**Comment by TheGreenGoblin** [comment]
I'm not sure if this is exactly what they're talking about, but this is something that happened to me a few times. I have a drive for Bleemsync that works fine, the I add a few game and run Bleemsync.exe. I put the drive in the PSC and get the 001-001 error. I examine the region.db file and the data tables are empty. After I run Bleemsync.exe again, all the games are there.

**Comment by PattonPlays** [comment]
Hey @DrGreenthumb0099    if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
