### ISSUE TITLE
Problems after problems! Boots up fine, then freezes going through carousel. Won't boot back up and keeps shutting down!

### ISSUE THREAD

**Issue by panaphobic** [pathartl/BleemSync#149]
So I'm having a pain in the ass time trying to get this working right. I'm using a 32GB Kingston DTSE9 USB 2.0 flash drive formatted to FAT32. I make all the game folders like I'm supposed to do, copy them to my flash drive, eject it from Windows and remove it, and then put it in the PS Classic. I then plug the PS Classic into my 2.4A USB adapter and turn it on. It boots up fine at first, and shows my new games with all the cover art like it's supposed to. Everything seems to work fine, but as I scroll through the carousel of games, it freezes all of a sudden and I can't do anything. If I unplug the power cord, the system STILL STAYS ON and displays on the screen until I unplug the HDMI cable! Then if I plug everything back in and turn the PS Classic back on, it will either show the Sony screen, then the screen goes black and shuts off after about 10-20 seconds (green light changes back to orange), or it will sit on the "health warning" screen for a minute (sometimes even longer), then finally boot up and says "Data repaired" or something like that. It'll show all my new games again after that, but will freeze up once again, just like before, typically after only trying to scroll through a couple games this time! It doesn't freeze on any particular game, sometimes it'll freeze after only going past 2 or 3 games sometimes, and other times I can go through the entire carousel a couple times before it freezes. I haven't even tried actually playing one of the new games though because this issue will need to be fixed first. If I take out the flash drive after it freezes, and plug it into my computer, Windows will say it's corrupted and needs to be repaired. I initially tried it with 38 games, then tried it with 20 (thought that might be an issue as the original system only has 20 games), then tried it with just 2 games (Breath of Fire 3 & 4). It still will freeze with just those 2 games as well if I just try switching between them several times.

I've tried reformatting the USB flash drive and reloading everything at least 10 times now, as well as using another one (same exact type of flash drive, just a different one). Still having the same issue. I tried running it with the BleemSync folder on it and without it (seems to boot up much faster without it). But still have the same exact issues every time! What am I doing wrong?

**Comment by pathartl** [comment]
Are you using a powered USB hub? That could be sending power back through the front ports. It's perfectly safe, but you just need to make sure to unplug/replug when replacing the USB storage device.

**Comment by pathartl** [comment]
Sounds like a problem with your USB device. The front ports are current limited so some drives may not work or may be unstable. Closing this as it's not an issue with BleemSync. Try out a powered USB hub or [disable current limiting](https://github.com/pathartl/BleemSync/wiki/USB-Current-Limiting).

**Comment by panaphobic** [comment]
So your saying that using my USB flash drive plugged directly into the PS Classic won't work because there's not enough power going to it from the PS Classic (see the attached picture)? Just want to make sure I'm reading this correctly. I really don't want mod the system itself, so what powered USB hubs will work with the PS Classic?

![20181228_154704](https://user-images.githubusercontent.com/46224783/50527838-d4164400-0ab8-11e9-8b2f-c156b885ce11.jpg)

**Comment by pathartl** [comment]
Correct. We're not tracking any specific powered hubs, most seem to work fine.

The front USB ports are limited to 100mA which is really only good for low power accessories like controllers, keyboards, mice, etc.
