### ISSUE TITLE
save states are no longer there after pluging usb back into computer

### ISSUE THREAD

**Issue by joshcasas** [pathartl/BleemSync#150]
after saving a few different games and turning off the system when i reboot the system and go to play the game all save states are gone.
dose anyone have an answer ?

**Comment by joshcasas** [comment]
after saving a few different games and turning off the system when i reboot the system and go to play the game all save states are gone.
dose anyone have an answer ?

**Comment by joshcasas** [comment]
update...
 Save states only disappear after pluging usb stick back into the computer. 
I can unplug usb stick from ps classic and plug it back in to ps classic and all save states are still there....But if i plug the stick into my computer and then back into the ps classic all save states are gone.

**Comment by brianhammerhand** [comment]
Did you re-run Bleemsync on your computer perhaps and that overwrote them? Just asking since it seems odd that only those files would be removed after mounting them on your PC?

**Comment by joshcasas** [comment]
NO even if its just pluged in to the computer all the save states disappear. i only run the bleemsync app when adding games and thats not the case here..

**Comment by FreudienSlip** [comment]
Your computer may be configured to try to fix a bad drive when you plug it in, mine asks if i want to fix it every time i plug into the pc, i decline.

**Comment by joshcasas** [comment]
mine also dose the some thing but i also decline.
