### ISSUE TITLE
Quake 2, JediPowerBattle, Winning Eleven don Run

### ISSUE THREAD

**Issue by Joelcumhon** [pathartl/BleemSync#154]
Every time I try to enter these games they do not initiate me, I get a message that the game has been closed due to an error in the games like QUAKE 2 and JEDIPOWERBATTLE and in the case of Winning Eleven 2002 the game does not start me, I do not even the loading screen appears. Very apart from that there is a small problem in terms of freezing screens is as if the screen freezes for a few seconds and then the game continues.

As for the games, I have already changed the Bin and Cue files for other games in the American, Japanese and European versions, but the same problems keep appearing

**Comment by pathartl** [comment]
This is an issue with the emulator, notban issue with BleemSync. Some games might just be incompatible with the emulator
