### ISSUE TITLE
Dragon Warrior 7 Save Crash

### ISSUE THREAD

**Issue by goggles789** [pathartl/BleemSync#156]
So far, everything seems to be working just fine.  I added a mix of Japanese and English games and so far so good.  Dragon Warrior 7 always seems to be an issue in emulation!

Anyway, Dragon Warrior 7 boots ups and plays fairly well with some framerate issues.  It has no problem creating a save file when you first start the game, but when you save the game at one of the churches, the game crashes and does an infinite loop of the save sound effect.  I am able to push the reset button on the system itself to get back to the menu, but so far I have not been successful in using the in-game save feature.

Any thoughts on how to resolve the issue?

**Comment by BoscoTheMan82** [comment]
Maybe its your iso file, I tried it last night and had no trouble saving at a church.

**Comment by PattonPlays** [comment]
Hey @goggles789  if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
