### ISSUE TITLE
Multi disc games

### ISSUE THREAD

**Issue by willshorty** [pathartl/BleemSync#159]
Hi, I have been watching for some period of time before I decided to try it out on the ps classic. 
I have followed all instructions so before I am asked I just want to state that I have checked all game ini and bin / cue files. 
I have a sandisk cruzer blade 2.0 64gb usb stick with 80 sets on bin and cue files on it. 
All menus load with info and images (looks great) and alot of the games I have work, however I have noticed that all of the multi disc games do not and some single disc games dont. All games when selected load onto the ps screen but when I have selected a game that does not work I have noticed the writing that is meant to say licensed by sony computer entertainment america is missing letters and in different sections of the screen, the game then hangs there. This is mainly on the multi disc games.

Is anyone able to help with this ? Am I doing something wrong or is there something I need to check ? Has anyonr managed to put FF8 on and play it ? Please let me know

**Comment by willshorty** [comment]
Thats one of the first things I checked, so as I just posted on one of the other threads all my bin / cue files are called after the disc id for example SLUS-XXXX. I am going to try adding (Track 01) etc to the end of the file names and re test however I know the game ini has the comma and corresponding file names for discs. 
I will also try sourcing the bin / cue files for elsewhere just to make sure its not bad roms however as mentioned its every multidisc game I have put on it so I will be suprised if ita every rom. More then likely something ive done

**Comment by willshorty** [comment]
Ok so I tried what you have suggested and still no joy, I have downloaded some new cue / bin files just the check but I am getting the exact same problem, I tried to fix 2 games that I have not been able to get working, Chrono Cross (Multi Disc) and Crash Bandicoot. 
I will upload some images now to show my files and settings maybe you could have a look and see if there is anything wrong with them.
Thanks

**Comment by willshorty** [comment]
https://attachment.outlook.live.net/owa/willshortell@hotmail.com/service.svc/s/GetAttachmentThumbnail?id=AQMkADAwATM3ZmYAZS04MGExLTAzOTItMDACLTAwCgBGAAAD262wqu1pG02xvVydPZgMSgcAkXK5W8RITUmpDEzD8RnCfAAAAgEMAAAAkXK5W8RITUmpDEzD8RnCfAACSnnfOAAAAAESABAA%2FIKIqZ02mkudWUPPcCHYEA%3D%3D&thumbnailType=2&owa=outlook.live.com&scriptVer=2018121703.02&isc=1&X-OWA-CANARY=9DgkZtXzCkqra13xgaQhQ0BBiMmQbtYYE6_zME_WcZFKugxon-8d_Fi0d2l-5DRUf0yydBbrS_c.&token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2MDBGOUY2NzQ2MjA3MzdFNzM0MDRFMjg3QzQ1QTgxOENCN0NFQjgiLCJ4NXQiOiJCZ0Q1OW5SaUJ6Zm5OQVRpaDhSYWdZeTN6cmciLCJ0eXAiOiJKV1QifQ.eyJ2ZXIiOiJFeGNoYW5nZS5DYWxsYmFjay5WMSIsImFwcGN0eHNlbmRlciI6Ik93YURvd25sb2FkQDg0ZGY5ZTdmLWU5ZjYtNDBhZi1iNDM1LWFhYWFhYWFhYWFhYSIsImFwcGN0eCI6IntcIm1zZXhjaHByb3RcIjpcIm93YVwiLFwicHJpbWFyeXNpZFwiOlwiUy0xLTI4MjctMjI5Mzc0LTIxNTgwMzU4NThcIixcInB1aWRcIjpcIjk4NTE1NTk4NjU4ODU2MlwiLFwib2lkXCI6XCIwMDAzN2ZmZS04MGExLTAzOTItMDAwMC0wMDAwMDAwMDAwMDBcIixcInNjb3BlXCI6XCJPd2FEb3dubG9hZFwifSIsIm5iZiI6MTU0NjE5OTUwOCwiZXhwIjoxNTQ2MjAwMTA4LCJpc3MiOiIwMDAwMDAwMi0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDBAODRkZjllN2YtZTlmNi00MGFmLWI0MzUtYWFhYWFhYWFhYWFhIiwiYXVkIjoiMDAwMDAwMDItMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwL2F0dGFjaG1lbnQub3V0bG9vay5saXZlLm5ldEA4NGRmOWU3Zi1lOWY2LTQwYWYtYjQzNS1hYWFhYWFhYWFhYWEifQ.YwmwoO9nAXXx6fX3kJTz8D-ws1AGEsCxfLUj_R2bwFHSHzHoQvN9mdZK2y_AdwT4SBmdYKfgcLQfDTvbbHUBBb__G0bx7sfjOeA05-_cgrj3lwiMk0Q0Fu3s6cNrpiReXJ3y3ScOSkY0GwrGrUzXRLSUDlcI9AhR1zK1QwLgnujtGqruaB1WzubQFTE6awuqS4sbUxeMgqAjpDK0y9KL59e5ro1ypxEUS0JHFmgqKcajSEHbX7RyMwg7pSMoSNOocN4-UVAWLPERMDElnvbacdZmS6d-EMLDZ_GAha9c-JVR7Zn_Axn723uuNPHzbN5AnC-D-zVAnBA4fHi9MSavOA&animation=true

**Comment by willshorty** [comment]
![untitled](https://user-images.githubusercontent.com/46262448/50550736-7e36cd00-0c6d-11e9-9d65-7f0b907bcb4a.png)
![thumbnail_20181230_192657](https://user-images.githubusercontent.com/46262448/50550737-81ca5400-0c6d-11e9-8871-ae8839e954dc.jpg)
![20181230_192919](https://user-images.githubusercontent.com/46262448/50550739-85f67180-0c6d-11e9-9509-551fc4248a88.jpg)

**Comment by ShadowHunter69** [comment]
Don't know about Crash bandicoot I have it and it works fine, chrono cross it looks like your missing the cue file for the second disc if they are multi disc games I'm sure they need a cue file for each disc

**Comment by ShadowHunter69** [comment]
I came across this issue myself with Dino Crisis this morning which I had also used anyburn to convert from CD image I have used anyburn for about 10 games so will have to try them all when I get chance

**Comment by willshorty** [comment]
Yes it appears to be same program I was using. I havnt had a chance to check a new software yet but will try some out later on and let you know aswell. It seems every single game ive converted using it has this problem single and multi disc games

**Comment by MartynKeigher** [comment]
Check out CDmage (https://www.emuparadise.me/links-and-downloads/General_CD_Utils/CDmage_1.02.1_Beta_5/20).

Good YouTube vid on how to use it too... https://www.youtube.com/watch?v=McrNQPc07RM

I've been using this for all of my multi-disc (multi-bin) games!

**Comment by willshorty** [comment]
Ok so just changed some bin files to new ones and yes appears that converting them with anyburn has been messing it up. All my multidisc ones work when I have jist sourced them through cue and bin rather then convert. Will look at what converter works. Thanks for all the help

**Comment by mlpope** [comment]
just so yall know, magic iso no good with me since it makes cd image where it stated is not supported when i load it...food for thought, i reckon

**Comment by mlpope** [comment]
what do u mean when u say u source the bin/cue in stead of convert...dont mean to bother, i was hoping u fellas could help me understand that one...im learning still and am a little ignorant!...😨

**Comment by willshorty** [comment]
Sorry I just meant find the cue/bin files to download instead of coverting either an .iso or .img file to cue/bin as converting them appears to be causing errors
