### ISSUE TITLE
i use 128gb usb driver the playstation classic will not start the hack on the 128gb drive but if is use 4 gb or 32gb driver it work fine

### ISSUE THREAD

**Issue by SlasherNLLD** [pathartl/BleemSync#164]

**Comment by MartynKeigher** [comment]
In all likelihood...  the board is incapable of registering USB devices larger than 32GB (or even 64GB)??

**Comment by pathartl** [comment]
No. There's no limit to storage devices. The USB ports are current limited to 100mA and most USB 3.0 devices have trouble with this. Either use a powered USB hub or [remove the limitation](https://github.com/pathartl/BleemSync/wiki/USB-Current-Limiting).

**Comment by MartynKeigher** [comment]
Ah... Good to know! :) (Thanks @pathartl)
