### ISSUE TITLE
multi usb sticks support with usb hub

### ISSUE THREAD

**Issue by blackpearl1477** [pathartl/BleemSync#165]
i want to know if multi usb sticks is supported to expand game library trough out multiple usb sticks.
this is handy for some of us when we run out of space on usb sticks and eliminate the need to swap out usb sticks

**Comment by alucard73** [comment]
I too would be interested to know if it is possible

**Comment by pathartl** [comment]
Without major changes to the way games are mounted, this can't be done. Maybe in the future way down the line we can take a look at this, but I'm labeling this wontfix and closing it.
