### ISSUE TITLE
ANY game gets stuck on ps screen (when game is loading)

### ISSUE THREAD

**Issue by lwood902** [pathartl/BleemSync#167]
i have tried many roms , all texting is correcting in all names and .cue file, even went out and bought the right USB , but nothing seems to get me past the first 4/5 seconds of the loading screen , 1 game had green fuzzy bits at the bottom of otje PS logo , but all the other ones just stuck with PS, PLEAAASE HELP ran out of ideas :')

**Comment by willshorty** [comment]
Are you converting iso or any other format to cue / bin ?

**Comment by lwood902** [comment]
atm the only 3/4 games ive tried have been iso , i think 1 was a  RAR which still didn't work

**Comment by willshorty** [comment]
Rar needs to be extracted with win rar that is not a disc image. Also this only reads bin/cue filea thats why your games are not loading if you get an iso ita possible yo convert to bin/cue however we have all been having problems with this corrupting game files and not working.

**Comment by lwood902** [comment]
ill give the RAR a go and let you know in 5 cheers :)

**Comment by lwood902** [comment]
do you have any links to working RAR files i can try please ?

**Comment by lwood902** [comment]
what about .7z files are they know to work ?

**Comment by willshorty** [comment]
All of these files your are saying are basically folders. The images are usually inside these files you need 7zip and winrar to open them. I cannot tell you where to download roms from as it is illegal if you dont own the original. You will have to figure that out for yourself however it is not difficult to find roms. 
You should do a little research into file types etc.

**Comment by lwood902** [comment]
Right, I've just managed to successfully complete MediEvil , thank you for giving me a better understanding on how to do this, originally i followed the YouTube tutorial but now its clear with what you said the .7z being "folders"

cheers for you help I REALLY Appreciate it

**Comment by willshorty** [comment]
No problem im no genius im omly on here because ive had problems haha
