### ISSUE TITLE
Black screen when loading Wipeout XL

### ISSUE THREAD

**Issue by mra144910** [pathartl/BleemSync#168]
Hi everyone,

I've been trying to get Wipeout XL to load. It appears normally on the PS Classic menu fine, however when I launch it, nothing happens, I just get a black screen. I followed all the same steps with other games. I double checked to make sure the bin, cue, and png files match as well as updating the database. I don't know what the problem is. Is Wipeout XL not compatible with Bleemsync?

I apologize if this has already been addressed. If I'm not providing enough info, please let me know.

**Comment by MLH199** [comment]
Hi, I now have this same issue, for wipeout, Wipeout XL and Wipeout 3 SE. They all worked, but now I just get a blank screen. I wonder if this is a database issue, as I could run Wipeout from the 'resume' snapshot, but deleted since and now can't run at all.

**Comment by rs2klee** [comment]
hi, i did have similar problems i could not load tekken 3 from the Bleem menu, it would flash then either black screen or just not do anything, But select and triangle to get into the emulator settings i could load up the New image then load it through that fine.. i know tekken 3 is in the main games list but when it boots to the Bleem listing its not in that part so wanted them to all be there when it boots into Bleem from the usb stick :)

**Comment by FyreAnt** [comment]
The issues with all the WipEout games are related to the BIOS files. They are trying to call the Japan version of the BIOS files on the USB stick. Go into the BIOS folder and delete the Japan version of the BIOS file leaving the other one and you'll be good to go.

**Comment by mra144910** [comment]
Thanks for the replies guys. I know this is a stupid question, but how do I access the BIOS file? Do I access it in the "triangle & select" menu? Or do you mean on the thumb drive through windows? I'm very new to this...

**Comment by willshorty** [comment]
Ive has multiple issues with games that came down to me converting them using anyburn. I have all my games working now 93 in total upto now. However wipeout, wipeout3 and wipeout xl all do the same thing and try to load from jp bios. I jave just hit select and triangle go into bios settings change yo mw and his reset game. Game loads and plays fine. I have tried to save this setting by saving config but that jist doesnt seem to save the config when trying to reload. Anyways I didnt notice that it i hit reset on the console create a save state i can load the game straight from that to title screen. It still.loads from jp bios but works fine. It would be good if the save config for the loaded game worked. It would solve this issue.

**Comment by FyreAnt** [comment]
You can browse the file system on the stick and delete the JP Bios and it will work properly from now on
