### ISSUE TITLE
4:3 video output

### ISSUE THREAD

**Issue by TheOlympian** [pathartl/BleemSync#173]
Is it possible to have a setting to change the aspect to 4:3 so I can play on a 4:3 screen and have it display games properly without black borders or not have it squash a 16:9 picture in to 4:3?

**Comment by rs2klee** [comment]
can try an old Dell 19" or 14 15" that has DVI input but you would need a HDMI to DVI cable.  HDMI is the new plug that used to be DVI. sometimes is the TV or monitor your using and needs to be switched into 4:3 ratio. Really unless you use a 4:3 tv you cant make a 16:9 behave like one you are always going to have black boarders to fill in the space.

**Comment by TheOlympian** [comment]
I specially bought from amazon a 10” 4:3 monitor to use with the classic but all it’s doing is squashing a 16:9 picture in to a 4:3 so even when playing games everything is made narrower and still gets black bars. 

So my question was can the devs add an option to have the classic output a 4:3 picture?

**Comment by pathartl** [comment]
Afaik the PSC always outputs at 1280x720. There has been progress to output at 1080p by switching the resolution, so there is a way to change the resolution. I'm not so sure the stock UI would work at 4:3, but might be something to test in the future.

**Comment by GMMan** [comment]
A custom Weston config file with the correct modeline configuration would be needed to switch output to 4:3 aspect ratio. The UI scales correctly at any aspect ratio (it letterboxes as necessary).

**Comment by swingflip** [comment]
I will consider this as part of the payload update after 1.1

**Comment by gustos247** [comment]
> Is it possible to have a setting to change the aspect to 4:3 so I can play on a 4:3 screen and have it display games properly without black borders or not have it squash a 16:9 picture in to 4:3?

Switching res in Retroarch does work fine.  Would be nice if it did on the bleem side.

**Comment by GMMan** [comment]
Do we know whether RA is changing the output mode directly or emulating a 4:3 stretch using the current resolution?

**Comment by TheOlympian** [comment]
Haven’t been following for a while. Has there been any progress on this lately?
