### ISSUE TITLE
Cannot Sync Original 20 games, even from USB

### ISSUE THREAD

**Issue by Shinto-Z** [pathartl/BleemSync#174]
After Exporting Original Games to USB via lolhack script, they cannot be re-added to Bleem Sync via USB. Bleem sync seems to programmatically skip over folders 0-20, when they contain the original 20 games... even if a game.ini file is created.

Only Non-Original Games sync. This has to be by design, but seems oddly limiting for no reason.

**Comment by thegoods87** [comment]
Pathartl just posted the release notes for the upcoming update a couple days ago. Support for adding the original 20 games is being added along with many othe awesome things. So just wait a few more days or so until BleemSync 0.7 is out and your issue should be solved.

**Comment by GMMan** [comment]
Make sure that the games are in a GameData folder under the numbered folder.

**Comment by PattonPlays** [comment]
Hey @Shinto-Z  if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
