### ISSUE TITLE
Support for other file types (.iso, .img, etc...)

### ISSUE THREAD

**Issue by thegoods87** [pathartl/BleemSync#175]
Hey super appreciate the work you're doing! Can't wait to see 1.0! I'm just wondering if support for other image formats will be added in the future? I'm on mac and I'm finding it nearly impossible to find a utility to correctly convert other image formats to bin/cue for use with BleemSync. mdf2iso works great but can't convert any other image types besides mdf. Tried PowerISO and seems to work but none of the files converted to bin/cue will run when I test them in PCSX. I Even tried converting a .img to .iso since that's what the program seems to specialize in and that won't run either (in PCSX) so I know somethings up. PCSX will run any image type (img, iso, bin, mdf..) normally so I'm assuming AnytoISO isn't converting the files properly. The .mdf files I converted to .bins with mdf2iso run perfectly. 

Any insight would be muchly appreciated thanks!

**Comment by pathartl** [comment]
We're currently looking at opening up the different file types that PCSX supports (https://github.com/RetroPie/RetroPie-Setup/wiki/Playstation-1)

**Comment by TheGreenGoblin** [comment]
With .img and .iso files, simply changing the extension to .bin seems to work for me so far.

**Comment by swingflip** [comment]
Technically speaking as of 1.0 we already support the following formats with RetroArch PCSX:
    .bin
    .cue
    .img
    .mdf
    .pbp
    .toc
    .cbn
    .m3u

We will be aiming to add bin/cue/pbp support within the UI for 1.0 

Closing for now as enchancement effectively fufilled

**Comment by salsan** [comment]
Tried Iso9660 Analyzer Tool ?

https://sourceforge.net/projects/iat.berlios/
