### ISSUE TITLE
no booting from 32G USB

### ISSUE THREAD

**Issue by Michael150883** [pathartl/BleemSync#177]
when i tried 32G usb it stuck to the 1st screen and then reboot or shut down
i already have 50 games on it

**Comment by Gab-75** [comment]
Did you try to use a powered USB hub? I use a SiteCom CN-81 USB 2.0 powered hub with a SanDisk Ultra 64 GB (95 games on it) and all works perfectly...

**Comment by Michael150883** [comment]
no but if i don't want to use a powered hub is there any other solution

**Comment by hofabass** [comment]
Did you try another USB stick? PS Classic is quite picky...

**Comment by Gab-75** [comment]
As far as I know, at the current stage, use a powered USB hub is the most safe way to prevent USB storage devices malfunctions... in any case, I read that DEVs are working on a new method for use the micro USB port on the back of PS Classic (it should solve the "milliAmpere" issue).

**Comment by Michael150883** [comment]
Well my usb is scandisk ultra 3.0 32 gb .. I formatted it with allocation unite size 64k it worked once and then when I was trying the first game it stopped working and never booted again

**Comment by hofabass** [comment]
I had the same problem with Kingston 64GB - it worked for a while, then it stopped working. Now I use SanDisk Ultra Fit 64GB (3.1) formated to FAT32 without any problems.

**Comment by Gab-75** [comment]
Sometimes when the NAND chip of a pendrive is read/wrote the energy request exceeds to 100 mA and this can cause troubles/data corruption with the limited mA output of PS Classic USB ports... personally I suggest to use a powered USB hub...

**Comment by raynebc** [comment]
My PS classic would only black out like this when I had a specific game's bin file on it (for whatever reason), all other ones I had (smaller and larger files) weren't a problem.  The problem went away after I connected the flash drive to the console with a powered USB hub.
