### ISSUE TITLE
Powered Hub compatbillty list?

### ISSUE THREAD

**Issue by mikewolfskin** [pathartl/BleemSync#178]
I can't seem to find where the compatibility list for powered hub's is. Can anyone point me in the right place? A Link perhaps?

**Comment by Gab-75** [comment]
I use a SiteCom C-81 and it works perfectly...
https://www.sitecom.com/en/usb-20-hub-4-port/cn-081/p/1717

**Comment by Gab-75** [comment]
I use a SiteCom CN-81 and it works perfectly...
https://www.sitecom.com/en/usb-20-hub-4-port/cn-081/p/1717

**Comment by mikewolfskin** [comment]
Can't seem to find that one listed here in the USA.

**Comment by K3nny150** [comment]
How can I use a 128gb flash drive on ps classic need help plzz usb is on efat format

**Comment by raynebc** [comment]
I'm using an Orico powered hub, but I don't imagine there are compatibility issues with most USB spec compliant hubs.  They're supplying all their own power so I can't imagine it's hit or miss the way that the power draw for USB flash drives are.

**Comment by BekaMaster** [comment]
here:
https://docs.google.com/spreadsheets/d/1saluXC8jfWhOVT9-JXj1Kd62hL2WGtCX6zErY6AElco

**Comment by K3nny150** [comment]
I’ve done that and it doesn’t work

**Comment by K3nny150** [comment]
I have the 128gb micro center usb on the list it says it’s compatible but the ps is not taking it at all

**Comment by pathartl** [comment]
Most powered hubs should work. Or [learn how to disable the current limiting on the front ports](https://github.com/pathartl/BleemSync/wiki/USB-Current-Limiting).
