### ISSUE TITLE
[Suggestion] Wifi dongle support

### ISSUE THREAD

**Issue by jhaleit** [pathartl/BleemSync#179]
Would be awesome to have Wifi support for Netplay and maybe a way to transfer games through Wifi.

**Comment by swingflip** [comment]
This is something we will be baking in to the kernel update within 1.1.

This is something for @GMMan to review and pick up

**Comment by GMMan** [comment]
I happen to have a WiFi adapter coming in the mail soon, so can definitely take a look.

**Comment by Wh1terat** [comment]
If you need any modules (in or out of tree) compiling just give me a shout.

**Comment by swingflip** [comment]
Will need to do some prototyping but by using wpa-supplicant and a realtek 8188 driver this shouldn't be too hard.
