### ISSUE TITLE
Bleem Exe not in download

### ISSUE THREAD

**Issue by maverickhunterzero0000** [pathartl/BleemSync#18]
Says in tutorial to run the Bleemsync.exe. This file is no where to be found. Please help. =)

**Comment by saschagehlich** [comment]
Make sure you download it from the Releases Page, not via "Clone or download":

https://github.com/pathartl/BleemSync/releases

**Comment by maverickhunterzero0000** [comment]
I just downloaded from the release page and there is no exe file in there. thank you btw for helping me out, I feel so close to playing Parasite Eve again
