### ISSUE TITLE
Automatic state saving does not work if PCSX's menu is used to step back into the games list

### ISSUE THREAD

**Issue by AX3L87** [pathartl/BleemSync#181]
Hi,
I'd like to thank you for this awesome hack for the ps classic!

I've noticed that if I push the console's reset button while I play a game, when returned into the games list, bleemsync (1.41) ask me if I would like to save (or overwrite) the current game's status.

The same pop up come even if I step back to the games list thought the PCSX's menu (select+triangle). However, in this case, the saved status will be not playable anymore (it will be corrupted or missing).

Can you fix it, please?

**Comment by GMMan** [comment]
This is an emulator feature that cannot be managed from BleemSync. I'm closing this issue because it does not relate directly to BleemSync. Someone in the future can patch the emulator to handle saving on exit properly.
