### ISSUE TITLE
Resident Evil 2 multi disc

### ISSUE THREAD

**Issue by RobinClair** [pathartl/BleemSync#184]
Does anyone know a way to get both Resident Evil 2 Leon and Claire discs running as one title with 2 discs? You unlock fun modes where you play as Hunk if you beat both discs on one save files. I can get the games to run separately as separate titles but not as one.

**Comment by willshorty** [comment]
I to would be interested in this....

**Comment by SynecViren** [comment]
U can change disc within the Select+triangle menu.

**Comment by samingrassia** [comment]
Try this:

***Files***
Game.ini
SLUS-00421-1.bin
SLUS-00421-2.bin
SLUS-00421.cue
SLUS-00421.png
SLUS-00592-1.bin
SLUS-00592-2.bin
SLUS-00592.cue
pcsx.cfg


***Game.ini***
[Game]
Title="Resident Evil 2"
Publisher=Capcom
Year=1998
Players=1
Discs=SLUS-00421,SLUS-00592

**Comment by ApexAftermath** [comment]
> U can change disc within the Select+triangle menu.

Just to expand on this, when you launch RE2 and it is at the PS logo screen you hit select + Triangle and you'll get an option to change the disc. This worked great for RE2, but other games like Final Fantasy 7 that comes on the system does not like when you do this and crashes. I believe games like that always need to just be launched, and then you do a switch discs depending on the save loaded. Games like RE2 however will tolerate a disc swap.

**Comment by SynecViren** [comment]
Games like FF7 or more multi disc games got screen for changing discs, its no problem then.  U got a prompt to change disc, button which changes discs work like a charm.  But games like RE2 dont have this screen, thats why it is a big problem for RE2
