### ISSUE TITLE
Failed to load data. Error Code : 001-001

### ISSUE THREAD

**Issue by KingSinister7** [pathartl/BleemSync#188]
Installed in root directory. Using a Lexar 128GB S75 thumb drive (passes on compatible list). Ran the Bleemsync executable on drive with admin privelages (it made a system folder). I just get the white sony logo screen then it cuts mid screen and goes to the blue screen.

**Comment by KingSinister7** [comment]
I just went and purchased an a/c powered USB hub. Still the exact same issue.

**Comment by raynebc** [comment]
The system folder is part of the Bleemsync installation, so if it didn't appear until you ran bleemsync.exe, you may have missed copying/extracting some things to your flash drive.

**Comment by TheGreenGoblin** [comment]
Have you tried running bleemsync.exe again (see my reply under "Can't get bleemsync to add games...")?

**Comment by KingSinister7** [comment]
Ok. So I figured out the issue. When I was creating my game folders I wasn't creating the "GameData" sub folder. Just the numbers. Thank you all for the help. :)
