### ISSUE TITLE
Configuration Pcsx

### ISSUE THREAD

**Issue by Pierinolartista** [pathartl/BleemSync#19]
I had launch The king of fighter 95 but not compare the figures on screen. I tried to launch with gpghax enter in emulator press "select+ triangle" and select "gpu_peops.so" and its ok.

How can i modify the file psx.cfg?

**Comment by pathartl** [comment]
Resolved in [0.3.0](https://github.com/pathartl/BleemSync/releases/tag/0.3.0)
