### ISSUE TITLE
Game starts but won't work :(

### ISSUE THREAD

**Issue by poku12** [pathartl/BleemSync#190]
i have found 3 games(diablo - all regions, tony hawk 2 - U.S and bomberman party edition) that start but thats it (without the ps logo screen but start). Sounds is good, video is good but the remote does not work, with or without the poweredhub.

**Comment by willshorty** [comment]
Are you converting the game files ? I had major problems with games not working and it turned out to be because I was converting .iso and .img files to bin and cue, the software I used messed up the image. I now have over 93 games working fine. No powered usb on a 64gb sandisk cruzer blade.

**Comment by poku12** [comment]
nope all are downloaded as cue and bin and all the other games i have are working just fine even tony hawk 2 EU ver

**Comment by willshorty** [comment]
Check what bios its pulling up. On wipeout it trys to load from jp bios. Have to select mw and reset game and works fine then

**Comment by poku12** [comment]
i cant even press reset and triangle when im in the game

**Comment by willshorty** [comment]
Maybe try removing the jp bios from the usb stick in system file. That way you know its not pulling up them bios.

**Comment by poku12** [comment]
thanks man, it worked ;)
