### ISSUE TITLE
Bleemsync work most of the time once than need to reinstall system folder 

### ISSUE THREAD

**Issue by i-sledge** [pathartl/BleemSync#192]
I got it working. But after closing game or shut down PSX. It not possible to restart a game. The ui works but I can not start the game. I need delete the system folder on the USB stick and install BleemSync again. 
In short
1. Installation of BleemSync works
2. Play game works
3. Leave game works (often it crashes)
4. switch of PSX ( press button)
5. restart PSX -> UI is working -> but can not start game get error message from UI
6. Plug USB stick in Mac delete System Folder and recopy it from bleem image
7. Plug Stick in PSX and wait for installation and it works again
8. after game end or switch off issue starts again

I tried it several times I can reproduced it all the time .
Did somebody has a clue ?
I

**Comment by PattonPlays** [comment]
Hey @i-sledge   if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
