### ISSUE TITLE
PNY 32GB 2.0 flash drive

### ISSUE THREAD

**Issue by JDarkRai84** [pathartl/BleemSync#193]
I am trying to get bleemsync to work but no matter how many times I try the PS classic just boots up to the stock games. I checked the Disc names all are the same. I run Bleemsync.exe it recognizes the games on the flash drive but when I put the flash into the Classic it just boots to the stock games.

**Comment by TheGreenGoblin** [comment]
In my experience, using PNY flashdrives with Bleemsync can be summed up in one word:
AVOID!!!!!!!!!!

**Comment by GMMan** [comment]
If the light when you plug in the USB drive does not blink orange, that means either your payload is not set up correctly or your USB drive is not receiving enough power.

**Comment by PattonPlays** [comment]
Hey @JDarkRai84  if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
