### ISSUE TITLE
Title that does not work

### ISSUE THREAD

**Issue by whip28** [pathartl/BleemSync#195]
Do you have an option to run these games without problems?

1.Worms Pinball  (Black Screen)
2.Extreme Pinball  (Flipper Not functional)
3.True Pinball  (Flipper Not functional)

**Comment by TheGreenGoblin** [comment]
I found a few games that either have problems or don't run at all...
Capcom vs SNK Pro
Doom
Final Doom
Jupiter Strike

**Comment by willshorty** [comment]
I have both doom and final doom working fine. I did have an issue with first final doom i tried. It crashed at loading bar. Vommon ossue with the audio apparently. I downloaded a multi track bin file and its working fine now

**Comment by BoscoTheMan82** [comment]
The problem with doom isn't it loading, there are areas that are completely dark when it should have blue lighting

**Comment by TheGreenGoblin** [comment]
Thanks, will. I redownloaded the multi track .bin files from the cool website and they work fine now.
