### ISSUE TITLE
controllers not recognised

### ISSUE THREAD

**Issue by rory316** [pathartl/BleemSync#196]
was using bleemsync and was working fine then unplugged system to move it when, i plugged in back in the main menu is back to original games and saying controllers not recognised so i cant do anything with the system to reset/reboot

**Comment by rory316** [comment]
tried every combanation controllers in each port, usb in and out, on and off and no change, the ports dont seem to have power going to them, it could just be a hardware fault and i've been unlucky but if theres a fix, i'd rather know it

**Comment by PattonPlays** [comment]
Hey @rory316   if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
