### ISSUE TITLE
bleemsync not working

### ISSUE THREAD

**Issue by tgrinnan85** [pathartl/BleemSync#197]
so i looked at the chart for compatible flash drives i went out an bought the sandisk ultra fit 64 gb 3.0 formatted it using the tool provided an loaded everything over an it wont even find this one i have no blinking light when i start it up...the other flash drive i had tried to use previously is a memorex 32 gb flash  drive that one i also had everything loaded over naming it sony an i get the blinking light in the beginning the sony title loads up then my scren goes blank an after a few secs it shuts off whats goin on

**Comment by K3nny150** [comment]
you need this to power usb 64gb and up there to strong for ps classic

**Comment by tgrinnan85** [comment]
Whatever picture u sent it’s not showing up is it the usb hub that I heard other ppl taking about

**Comment by K3nny150** [comment]
Yes I have a 128gb and it works with no problems it’s called (insignia 4 port usb 3.0 hub black) at Best Buy’s $29

**Comment by whip28** [comment]
The USB2 model was just $ 15.95 at January 3. The Ps Classic has just usb2 port. bestbuy Canada
NS-PCH5421-C

**Comment by nevbartos** [comment]
Run this https://github.com/nevbartos/BleemSync.Validator/releases utility against your USB drive to see if it is configured correctly as you may have the contents incorrectly configured.

Cheers.

**Comment by PattonPlays** [comment]
Hey @tgrinnan85   if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
