### ISSUE TITLE
hostfxr.dll failed to load

### ISSUE THREAD

**Issue by MindController** [pathartl/BleemSync#2]
I noticed when trying to run the BleemSync.exe off the usb drive, it would immediately close down.  After running it through the cmd prompt, I get this error:

Failed to load the dll from [Z:\New folder\psclassic\BleemSync\BleemSync\hostfxr.dll], HRESULT: 0x80070057
The library hostfxr.dll was found, but loading it from Z:\New folder\psclassic\BleemSync\BleemSync\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

I installed those prerequisites and yet the issue continues to happen.  Ideas?

**Comment by MindController** [comment]
Figured it out.  Installing Visual Studio 2015 Community Edition fixed it.

**Comment by pathartl** [comment]
Reopening. This is probably because I published it as win10x64 when it should probably be win7x86.

**Comment by pathartl** [comment]
Resolved in [0.3.0](https://github.com/pathartl/BleemSync/releases/tag/0.3.0)
