### ISSUE TITLE
Not verying anything

### ISSUE THREAD

**Issue by rick2890** [pathartl/BleemSync#20]
I tried 4hrs for getting the menu showing in psx and its not showing or loading my customs games. Yes I download mine from release page and no luck. Help??

**Comment by saschagehlich** [comment]
What stick are you using? The PS Classic seems to be very picky when it comes to USB devices in general.

**Comment by rick2890** [comment]
@saschagehlich 2.0

**Comment by saschagehlich** [comment]
It needs to be of a specific brand and model. See issue #1

**Comment by rick2890** [comment]
@saschagehlich Sandisk

**Comment by rick2890** [comment]
I also tried it with other USB still turns green doesn't change color

**Comment by saschagehlich** [comment]
Read the issue I linked to.

**Comment by rick2890** [comment]
Hi it worked the usb was the problem! Thabks, Cheers
