### ISSUE TITLE
Bleemsync / games issue 

### ISSUE THREAD

**Issue by ss5gamer** [pathartl/BleemSync#200]
Hello! I'm having a issue where everything boots up well except the games are blank with no png the  title info and blank square image is all there for every game I added. when I click on the game its blinks a for a sec like it tried to open the game but nothing happens. I tried more than 10 different compatible usb with all the same issue. Any help is kindly appreciated

**Comment by willshorty** [comment]
You would also have to open the .cue file with notepad etc. And if you have changed .bin name youd have to change it inside the cue file.

**Comment by PattonPlays** [comment]
Hey @ss5gamer   if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
