### ISSUE TITLE
Directory corrupts on power down

### ISSUE THREAD

**Issue by mattcwessel** [pathartl/BleemSync#203]
I am able to get the directory to mount and run on a 32gb sandisk microSD in a usb 2.0 adapter, i can play everything, it all works great, but when i shut the system down, the entire directory corrupts,  even if i don't remove the card, i can't power back into bleem.  If I put the card into my mac again, i can see the file folders, but cames, png, game.ini.. all kinds of stuff is 'missing (it's still there, but the drive directory is corrupted so it can't seem to be seen or accessed, i then need to reformat and rebuild the drive)   anyone seen anything similar?  This is in 0.4.1

**Comment by MaxLempira** [comment]
Having the same problem. When try to power up second time I can't get Bleem! to work, I have to delete everything on System (Except Database) to make it work again. Sometimes everything on SDCard got corrupted.

**Comment by PattonPlays** [comment]
This issue has been addressing a future revision that has not been publicly released yet. Keep an eye on this  page for a future update that helps to correct this issue.
