### ISSUE TITLE
One USB stick works but not the other please help!

### ISSUE THREAD

**Issue by RobinClair** [pathartl/BleemSync#205]
Hello internet! I set up a 32Gb stick with lots of games I wanted, followed all the instructions and it worked in my PS1 classic perfectly. So I read through the compatibility doc here and choose a 64 gb stick that someone said works, bought it and pre made a 64gb bleemsync file to copy over when it arrives and it won’t work! The system just doesn’t recognize is on boot. It is fat32 named SONY I’ve even copied the exact 32Gb file the other stick works with and it just isn’t recognized by the system. I’m feeling a bit defeated! Please help

The new USB stick is

SanDisk Ultra Flair USB 3.0 64GB Flash Drive High Performance up to 150MB/s (SDCZ73-064G-G46)

SanDisk Ultra Flair USB 3.0 64GB Flash Drive High Performance up to 150MB/s (SDCZ73-064G-G46) https://www.amazon.ca/dp/B015CH1NAQ/ref=cm_sw_r_cp_api_i_vA0nCbW16HB3Y

Not sure if I need a powered USB hub or something? Please lend insights.

**Comment by MrMilenko** [comment]
Unfortunately this isn't something we can actually fix with BleemSync, it's an issue with Sony's hardware. As such we have to close this issue and forward you to modmyclassic.com/wiki for help on this topic.
