### ISSUE TITLE
Issue with ™ & ® characters not showing

### ISSUE THREAD

**Issue by MaxLempira** [pathartl/BleemSync#210]
I would like to have stock games on my USB and some have those characters on their names, but BleenSync don't recognize them. Hope it can support them in the future

**Comment by GMMan** [comment]
Check that when you're saving the file it's saved with UTF-8 encoding and BOM. That will at least rule out incorrect encoding in the file itself.

Related to #57

**Comment by MaxLempira** [comment]
> Check that when you're saving the file it's saved with UTF-8 encoding and BOM. That will at least rule out incorrect encoding in the file itself.
> 
> Related to #57

Thanks so much, it really worked. So just need to Save as UTF-8 the Game.ini file and that's all. Please close this Issue
