### ISSUE TITLE
Constant Error 001-001

### ISSUE THREAD

**Issue by DunkSB412** [pathartl/BleemSync#213]
ok I just bought a USB Flash off amazon, loaded it with 137 games inserted and boom it loaded 100% fine decided ok Ill try more games, added more reran bleemsync to build the database, unplugged power, inserted usb, powered on, loads to the error 001-001 screen. I tried removing those games still same error, i tried loading even less games still same error. I went back to stock ps classic menu and initialized tried everything (stock 20 games work and load fine) I formatted the USB several times and tried loading everything fresh still same error, i redownloaded the bleemsync zip files and tried using all new stuff on the flash drive still same error? What can be possibly causing it and why did it load flawlessly first time i ever loaded the USB?

my SONY/System/UI/error.log shows this
Can't open preference file [/data/AppData/sony/ui/user.pre] for loading
Fatal : Resource unavailable

regional.pre shows this
iUiSystemSettingRegionId=1
iUiSystemSettingDefaultLanguageId=3
bUiSystemSettingReverseEnterKey=true
iUiUserSettingAutoPowerOff=1

user.pre shows this
iUiUserSettingAutoPowerOff=1
iUiUserSettingLastSelectGameCursorPos=0
iUiUserSettingSelectedLanguageId=3
bUiUserBootedFlag=true

lolhack.log shows this
killall: ui_menu: no process killed
/media/lolhack

ui_menu.log shows this
The subsystem type is not supported yet
The subsystem type is not supported yet
The subsystem type is not supported yet
The subsystem type is not supported yet
The subsystem type is not supported yet
The subsystem type is not supported yet
The subsystem type is not supported yet
The subsystem type is not supported yet
The subsystem type is not supported yet
The subsystem type is not supported yet
libEGL warning: MESA-LOADER: failed to retrieve device information

mtk_performance-shm exiting running 0 ret 4

**Comment by TheGreenGoblin** [comment]
Try using DB Browser to examine your System/Databases/regional.db file. If your data tables are empty, you need to run BleemSync.exe again.

**Comment by DunkSB412** [comment]
> Try using DB Browser to examine your System/Databases/regional.db file. If your data tables are empty, you need to run BleemSync.exe again.

fixed it man thanks! I did a few test ins with bleemsync.exe and examined them vs my original post with it being empty, so finally got the data tables correctly ordered and numbered, loaded into the classic and boom it worked! thanks a bunch man
