### ISSUE TITLE
Running cheats/gameshark with bleemsync

### ISSUE THREAD

**Issue by mlpope** [pathartl/BleemSync#214]
i didnt seem to find a thread on this issue but i was wondering if there was a way to run gameshark through bleemsync...i would guess you could run/load gameshark iso file but then there is the issue with switching over to the game to run those cheats...thanks in advance.

**Comment by TheGreenGoblin** [comment]
There was a YouTube video that covered this.
https://www.youtube.com/watch?v=ohAw5u2TiJw&t=35s

**Comment by mlpope** [comment]
thank u k... i will give it a whirl, (as Kevin McCalister from Home Alone would say.)
