### ISSUE TITLE
[Suggestions] overlayfs, bash traps, animation delay

### ISSUE THREAD

**Issue by Wh1terat** [pathartl/BleemSync#218]
I've been doing things my own way, but a couple of small parts that might be of use.
*Note* I am using an ext4 usb drive - fat filesystems are not POSIX compliant and so not compatible with overlayfs, you could look at udf or diskimages on the fat partition I guess, but this wasn't a requirement for me.

1. Overlayfs 
Whilst not included in the kernel; I've compiled the overlayfs module and currently use it in my own builds - not going to go into huge detail about overlayfs (unless you'd like me to) but the advantages are many. No need for 100s of bind mounts, symlinks or to copy unaltered files to USB.
[overlay.ko.zip](https://github.com/pathartl/BleemSync/files/2752567/overlay.ko.zip)

2. Bash traps
In your mount sequence, rather than appending "|| MOUNT_FAIL=1" everywhere (or setting -e) it's preferable bash-wise to use traps.

3. Animation delay
Only minor, but killing showLogo early just looks a bit rough - looping for it to die naturally just made the bootup experience more natural.

Just for reference, this is my boot script.

```bash
#!/bin/sh

killall -s KILL sonyapp ui_menu

# Cleaner experience just to wait for the splash to finish
while [ $(pidof showLogo) ]; do
    sleep 0.1
done

# Cleanup function called by trap
cleanup() {
    sync
    sync
    reboot
}

# Call cleanup() if any process exits with a non-zero code
trap cleanup ERR

# Insert the OverlayFS kernel module
insmod /media/files/overlay.ko

# Create "associative array" (hack) of data and gaadata with original mountpoints as value
partitions=( "data:/dev/mmcblk0p10" "gaadata:/dev/mapper/gaadata" )

for i in "${partitions[@]}"; do
    # <Bash4 workaround
    mname=${i%%:*}
    mpoint=${i#*:}

    # Unmount partitions
    umount /${mname}

    # Create new mountpoint and OverlayFS dirs
    mkdir -p /tmp/${mname}_lower /media/${mname} /media/tmp/${mname}_working

    # Remount original partition as read-only on new mountpoint
    mount -o ro ${mpoint} /tmp/${mname}_lower

    # Create OverlayFS mounts
    mount -t overlay overlay -o lowerdir=/tmp/${mname}_lower,upperdir=/media/${mname},workdir=/media/tmp/${mname}_working /${mname}
done

# Bind mount Joystick udev rules - only file outside of /data and /gaadata so would be overkill to overlayfs that
mount -o bind /media/files/20-joystick.rules /etc/udev/rules.d/20-joystick.rules

# Reload and apply udev rules that were overmounted above
# Allows both controllers to be detected through a USB hub
udevadm control --reload-rules
udevadm trigger

# Enable pcsx menu
export PCSX_ESC_KEY=2

# Bizarely relative paths are used so must be in the below folder
cd /data/AppData/sony/pcsx

# Launch menu
/usr/sony/bin/ui_menu --power-off-enable &> /media/logs/ui_menu.log

# Sync and reboot
cleanup()
```

**Comment by MaxLempira** [comment]
This...

Animation delay
Only minor, but killing showLogo early just looks a bit rough - looping for it to die naturally just made the bootup experience more natural

**Comment by swingflip** [comment]
Classing this as a clean up Boot routine killing and configuration as Weston contains some sort of framebuffer cache which makes this weird crap UI issue.

The overlayFS is part of a seperate ticket

**Comment by swingflip** [comment]
OverlayFS is being added as a seperate task. I will look at cleaning up using traps for next build and I fixed the dumb animation thing. Thanks for the suggestions (y)
