### ISSUE TITLE
BleemSync 0.4.1 works sometimes but is not working most of the time for me

### ISSUE THREAD

**Issue by dazzerwrestle** [pathartl/BleemSync#222]
Hi I am new to this group hoping someone can help I have run BleemSync 0.4.1 on my USB's lexar 32gb memory stick and had around 25 games on it and they were running fine for about 5 days then yesterday they stopped working and the memory stick said it needed to be formatted in the pc so I did a format followed all the steps again and it does not flash when I plug it into the playstation anymore as in the playstation light does not flash it just loads the games that came installed with the playstation I then tried another memory stick a SanDisk Ultra USB Flash Drive USB 3.0 up to 100 MB/s - Black, 32GB which also would not make the playstation light flash but when I tried it again this morning the lights on the playstation flashed when I loaded 2 games on the Sandisk stick it played one of the games but when I tried to load more games on it it again stopped working and would not load any games including the ones that worked this morning it just loaded the preinstalled games that came with the playstation when I plugged it back in? Any help would be appreciated as I have tried for hours to get it to work again

**Comment by santiis2010** [comment]
I have the same problem, just wait till the version 1.0 is available for download this week.

**Comment by dazzerwrestle** [comment]
Thanks I guess it must be a common issue as I have seen someone else on another Forum with the same issue at the moment and no solution reported yet so will wait to see if version 1,0 solves this

**Comment by PattonPlays** [comment]
Hey @dazzerwrestle if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
