### ISSUE TITLE
Final Fantasy VIII

### ISSUE THREAD

**Issue by mredward87** [pathartl/BleemSync#224]
Is difficult for work this game: I put inside folder .sbi file of every disc. The first disc start but after first mission of seed crash.. you have any solutions for this game?

**Comment by DNA64** [comment]
Hey @mredward87 Please refrain from opening issues unrelated to BleemSync. If you would like some support on your issue, you're welcome to join us in #sony-support on the ModMyClassic Discord server. https://discord.gg/mzEeWAn

**Comment by mredward87** [comment]
Your invitation is expired. Please send me another time.
