### ISSUE TITLE
Having to overwrite my Bleemsync files quite often.

### ISSUE THREAD

**Issue by abelogan** [pathartl/BleemSync#227]
Every time I turn off the console (whether it's because I'm done playing or because the game crashes), when I try to start it back up, it will either get stuck on a black screen or it will go straight to default (20 original game) interface (it doesn't load from the USB drive).  I've found the only way to fix it is to put the USB drive into my computer, copy the 4 folders from Bleemsync 0.4.1 (all the folders except "Games"), and paste them into the USB drive.  Not the end of the world, but it does get annoying.  Any way around this?

**Comment by PattonPlays** [comment]
The future update address this. For some reason on some drives the files get corrupted upon shutting down.
