### ISSUE TITLE
bleemsync not booting

### ISSUE THREAD

**Issue by vris2809** [pathartl/BleemSync#229]
Hi, the last days works everthing fine, today i want to play, and my classics starts all the Time
in the original Dashboard.
1. pad=port 1
2. Usb stick=port 2
3. power in
4. power button. (usb stick blink 1 time)
5. power LED ist not blinking

i format the usb stick new, and install bleemsync 0.41 new.
bleemsync will not boot.

**Comment by PattonPlays** [comment]
Hey @vris2809  if you need assistance please head over to the ModMyClassic Discord channel. It is much easier to troubleshoot in that environment. Thanks! http://discord.gg/96DKEdd
