### ISSUE TITLE
Add Triangle+Select Menu access

### ISSUE THREAD

**Issue by Delphi79** [pathartl/BleemSync#23]
Will you add this to your config so you can access menu? Tested on my console and works well.

#Access Esc Menu from Select + Triangle on controller
sleep 5s
export PCSX_ESC_KEY=2

Here is the lolhack I am using with this function added.
[lolhack.zip](https://github.com/pathartl/BleemSync/files/2668392/lolhack.zip)

**Comment by saschagehlich** [comment]
Just create a Pull Request, that's what GitHub is there for :)

**Comment by plinkr** [comment]
I believe you don't need the "sleep 5s" at the beginning, the line "export PCSX_ESC_KEY=2" it's what makes the keybinding for SELECT+TRIANGLE, as the export command is used to export a variable or function to the environment of all the child processes running in the current shell.
All "sleep 5s" does is make the script pause for 5 seconds before continuing.

**Comment by saschagehlich** [comment]
@plinkr True, just move that line to the very top of the file (after the shebang, if present) and you should be fine
