### ISSUE TITLE
[Question] Is it possible to run PlayStation 2 games too?

### ISSUE THREAD

**Issue by ViBE-HU** [pathartl/BleemSync#235]
Just a thought: I'm not so familiar with the old PS hardwares but as I see the PSC hardware could be capable to run PS2 games too. But what about the software side? Not clear what kind of fork Sony use, but can the PSC run PS2 games?

**Comment by ViBE-HU** [comment]
@andshrew Why?

**Comment by Gab-75** [comment]
The SoC MediaTek MT8167a has not enough computing power to emulate the PS2 hardware at a decent speed...
