### ISSUE TITLE
BleemSync mutliple Discs

### ISSUE THREAD

**Issue by Bre4k1tUp** [pathartl/BleemSync#246]
Hi Guys,

i´m using bleemsync since yesterday, it works perfect when i use games with only one Disc.
If I use a game like final fantasy 9 with mutliple discs (4 discs) i got the problem, if the game starts, I stuck in a blackscreen.

I have for any bin the cue file in my folder, but it still dosen´t work.
Could someone help me with this hopely little problem :) ?

Thanks a lot :)

**Comment by BeatzByMiix** [comment]
Go to the folder with FF9, there should be a Game.ini file. Click edit and rename the disc section the same as your Que/Bins

Example...


 [Game]
Title="Final Fantasy IX"
Publisher=Square
Year=2000
Players=1
Discs=Final Fantasy IX (Disc 1), Final Fantasy IX (Disc 2), Final Fantasy IX (Disc 3), Final Fantasy IX (Disc 4)


Hope this helps.

**Comment by Bre4k1tUp** [comment]
Yeah i have done it.
On FF7 it works, but not with FF9 ;/ 

Could my disc 1 be broken in the file? Because i downloaded the file from 2 different paiges and both are not working..
It´s the german version of ff9

**Comment by tommys77** [comment]
Is it patched? I believe the PAL version of FFVIII and IX needs to be patched to remove copy protection.

**Comment by andshrew** [comment]
> Is it patched? I believe the PAL version of FFVIII and IX needs to be patched to remove copy protection.

You don't need to patch it to remove the copy protection, but yes it's most likely to be this.

Download the [SBI file](https://psxdatacenter.com/downloads.html) for your version of FF9 and place it in the same folder as your game files naming it the same as your disc 1 .cue file... ie. if disc 1 is named SLES-02967.cue you would name the SBI file SLES-02967.sbi. The emulator will then automatically load this file when you start the game.

**Comment by Bre4k1tUp** [comment]
i´m gonna try it in a sec

**Comment by Bre4k1tUp** [comment]
It works, but the language is not like i wanted in german, it´s in english, but i downloaded it for PAL German
some advice for this?

**Comment by PattonPlays** [comment]
Hey @Bre4k1tUp  if you need assistance please head over to the ModMyClassic Discord channel. It is much easier to troubleshoot in that environment. Thanks! http://discord.gg/96DKEdd
