### ISSUE TITLE
Uploading Games via Web App Won't Work With 1.1's Planned OTG Support

### ISSUE THREAD

**Issue by patrickmollohan** [pathartl/BleemSync#256]
Hello, just wanted to first say thank you everyone for releasing 1.0 and for all the hard work put into the project. The web app is a unique way of handling uploads, but it will not be sufficient for 1.1's OTG support, assuming the user expects to upload games to their USB storage device via the web app and OTG. I have tested two different OTG adapters so far (a generic angled one, as commonly used on the (S)NES Classic Editions, and a wired one from Rii); on both, the power connector is lacking data lines. Plugging it in effectively creates a USB condom, blocking communication with my computer, rendering the web app useless. The only way a user could upload games is by using a powered USB hub connected to the front, which defeats the purpose and hype of the OTG support. A proper desktop application will need to be created (similar to Hakchi) that would allow the user to plug in the Playstation Classic and USB storage device to the computer seperately and sync the games. Additionally, manual game uploading should be reimplimented. Not allowing this seems a touch restrictive.

**Comment by pathartl** [comment]
This a concern that has been brought up previously. We are currently doing discovery on what it would take to pivot to a desktop app. Ideally we would keep the on-console solution as well as a desktop app. This has to do with the overall vision of BleemSync and what it is made to resolve that other solutions do not tackle.

**Comment by patrickmollohan** [comment]
Awesome! My apologies, I must not have seen the previous discussions on this. Just wanted to make sure it was thought of before too long. Can't wait to see what the future holds for the project!

**Comment by patrickmollohan** [comment]
Awesome! My apologies, I must not have seen the previous discussions on this. Just wanted to make sure it was thought of before too long. Can't wait to see what the future holds for the project!
