### ISSUE TITLE
Games not starting - EU Version

### ISSUE THREAD

**Issue by acocalypso** [pathartl/BleemSync#26]
Hi,

I followed your instructions step by step and the games are loaded into the ui, but no cover is visible and none of the games will start.

I used the first lolhack version from the repo https://github.com/justMaku/gpghax which is working for me.

![1c736b8e-3c0b-4e47-ad18-03bacff458ef](https://user-images.githubusercontent.com/2846629/49830163-a62ec100-fd90-11e8-9a48-3c7373a66470.jpg)
![1e71132a-45c3-4060-b032-8580eb1a58ed](https://user-images.githubusercontent.com/2846629/49830164-a62ec100-fd90-11e8-8c19-fcf386f7bb3c.jpg)

[regional.zip](https://github.com/pathartl/BleemSync/files/2669397/regional.zip)

**Comment by pathartl** [comment]
There should be a filelist.log on the root of your USB, can you upload that?

**Comment by acocalypso** [comment]
[filelist.log](https://github.com/pathartl/BleemSync/files/2669581/filelist.log)
here we go this is the filelist.log

I also saw this error messages in system/ui_menu.log
```
pcsx.cfg file not exist in 1 directory
pcsx.cfg file not exist in 2 directory
pcsx.cfg file not exist in 3 directory
pcsx.cfg file not exist in 4 directory
pcsx.cfg file not exist in 5 directory
pcsx.cfg file not exist in 6 directory
/gaadata/21/pcsx.cfg not found
/gaadata/22/pcsx.cfg not found
/gaadata/23/pcsx.cfg not found
/gaadata/24/pcsx.cfg not found
/gaadata/25/pcsx.cfg not found
```

the pcsx.cfg is in each directory.
[ui_menu.log](https://github.com/pathartl/BleemSync/files/2669585/ui_menu.log)

![xxx](https://user-images.githubusercontent.com/2846629/49832570-530c3c80-fd97-11e8-9572-e505094efb76.PNG)

**Comment by manchos2** [comment]
Except for the UserData folder, those files all need to be in a folder called 'GameData'

Eg Games\1\GameData\

**Comment by pathartl** [comment]
Please try [0.3.0](https://github.com/pathartl/BleemSync/releases/tag/0.3.0)

**Comment by saschagehlich** [comment]
@acocalypso Your folder structure is wrong. Everything inside your `1` folder needs to be in another `GameData` folder. See the README of this repo for reference.

**Comment by acocalypso** [comment]
Thats right...

I will check this later...

Gesendet von Workspace ONE Boxer

Am 12.12.2018 11:47 schrieb Sascha Gehlich <notifications@github.com>:

@acocalypso<https://github.com/acocalypso> Your folder structure is wrong. Everything inside your 1 folder needs to be in another GameData folder. See the README of this repo for reference.

**Comment by acocalypso** [comment]
after changing the folder structure according the readme its working. 

closed
