### ISSUE TITLE
Optimize add game function in bleemsyncUI

### ISSUE THREAD

**Issue by elbundz** [pathartl/BleemSync#260]
I had a very hard time to understand how to add new games with the UI.
My expectation was, that I press the button "Add new game" and then I can select the game files to add. I did not understand, that then the button "choose files" appears and has to be used for that.

So for a better and quicker user expierence I suggest the following change:
* If the user clicks "Add new game" the file selection appears directly.
* "Choose files" button can be removed, because it is not needed anymore.
* Optional: "Add game" button should be renamed into "Upload game".

**Comment by MaxLempira** [comment]
If you let me add some more...

- Select Custom .png when selecting .cue & .bin to upload instead of droping it in the UI.
- If could... Select too the Game.ini File with .png, .cue & .bin files some of us have from previous releases.
- Show the remaining space on USB Memory Stick would be amazing plox.
- Ability to Order/ReOrder Games as they will show in carousel, including Stock Games if possible.

**Comment by nex86** [comment]
Actually, no.
The game should not be uploaded right away when added.
you should have the ability to add your games to the list, and edit them without uploading.
The possibility to add multiple game folders at once would be appreciated.

Then have an "Upload Games" or "Sync" button that will upload all your added games at once.

**Comment by LifesFailure** [comment]
I would like to see the following in the UI:

-Internal AND External Games with carousel order (use different font color to differentiate)

Check box(es) in UI or link to "Display Order" in preferences.
-Arrange by order in BleemSync UI     <--This would allow users to drag/drop in the order they'd like the games to be displayed
-Arrange by Title (alphabetically)
-Arrange by Sort Name (custom games only)
-Arrange by Date

-->Once selected and "Applied" the list in the UI will be arranged to reflect this

**Comment by GMMan** [comment]
@LifesFailure What you're describing is out of the scope of this issue. Could you move it to a new issue?
