### ISSUE TITLE
BleemSyncUI must be an open source client-side app.

### ISSUE THREAD

**Issue by realromhunter** [pathartl/BleemSync#261]
When design is clever, we got usefull tools like this: 
https://github.com/TeamShinkansen/hakchi2/releases
Webapp was terrible idea. I thinks It could be just Web Services for covers and game data.
Even cover pack and db files repo are better options than a webapp.

**Comment by PattonPlays** [comment]
Please restrict your personal opinions in the Issues section of this github. It is for issues with the program only.
