### ISSUE TITLE
Heart of Darkness saved game issue

### ISSUE THREAD

**Issue by Tamakwa** [pathartl/BleemSync#262]
Hi Guys,

I updated to 1.0, added the multiple disc game Heart of Darkness, and copied back my saved game. The game runs fine when I start from the beginning, but resume my old save game, it loads, the screen appears, than freeze. Nothing I can do. Is this some kind of compatiblity issue with 0.4.1 and 1.0? I can send you my saved game, maybe that is help you for some bug tracking.

Regards,
Zoltan

**Comment by PattonPlays** [comment]
Hey @Tamakwa  if you need assistance please head over to the ModMyClassic Discord channel. It is much easier to troubleshoot in that environment. Thanks! http://discord.gg/96DKEdd
