### ISSUE TITLE
Boot Menu suggestion: Use the Open button to launch Retroarch

### ISSUE THREAD

**Issue by AnotherLife** [pathartl/BleemSync#264]
Sometimes I need to connect the default pad in order to press the X button to launch Retroarch because my DualShock4 isn't recognised at that point. Is it possible to make the unit's Open button launch RA?

**Comment by nex86** [comment]
Thats a good idea and really something to consider!

**Comment by runboy93** [comment]
Bleemsync 1.0 does have certain option in bleemsyncui called "Boot directly to Retroarch", DS4 controller is detected automatically by Retroarch, so need default controller to get past of the default boot menu.

**Comment by AnotherLife** [comment]
But ... I don't want to always boot directly to Retroarch.

**Comment by pahakalle** [comment]
Could we make Retroarch appear as a game on the magical wheel of games that you can open?

**Comment by swingflip** [comment]
I will leave @CompCom to be the decision on this

**Comment by AnotherLife** [comment]
@CompCom 
Please make the Open button act as X in the boot menu (or just launch Retroarch). It's a bit silly that I have to juggle cables just to press 1 button :/

**Comment by AnotherLife** [comment]
Well, this happened! 

Thanks!
