### ISSUE TITLE
Persistent mouse cursor when using 8BitDo USB Wireless Adapter for PS classic edition

### ISSUE THREAD

**Issue by raddp** [pathartl/BleemSync#267]
Both in UI and in games, persistent mouse cursor in the upper left area of the screen. This only occurs while 8BitDo adapter is connected. 8BitDo provides a fix for this issue in their latest firmware 1.22 from 1/18/19: [Added the function of hide cursor on PSC mode: Hot key - SELECT+A+B+X+Y]. This fix is working with USB stick disconnected, mouse cursor disappears on both stock UI and in games. But when USB is reconnected and using BleemSync + 8BitDo adapter, mouse cursor is persistent. Solutions online to unplug and re-plug the adapter after power-on, and after game starts have not worked. Another user suggested "Disable Desktop Composition" in RetroArch, which just hangs the PS Classic for me. Reporting here since the 8BitDo mouse cursor fix is working outside of BleemSync. Thank you in advance!

**Comment by swingflip** [comment]
Yeah this is down to 8bitDo and not us. So we can't fix. 

We will be looking to add generic $1 BT dongle support for controllers so we don't have to rely on these dongles

**Comment by tdullemond** [comment]
When you connect a USB mouse to the PlayStation Classic you can move the mouse cursor around the screen (and out of the screen), maybe it is possible to do the same in BleemSync. That would be an easy fix for this annoying issue...
