### ISSUE TITLE
Sortable game list function

### ISSUE THREAD

**Issue by cnterr** [pathartl/BleemSync#268]
I tried to customize the games order by dragging them to the desired position but the change do not saved, later I tried to use the field "sort name" and now in the management interface the titles are listed correctly but when starting BleemSync in the carousel continue to be sorted by name.
I have also tried to disable the setting "If true then auto alphabeticalise emmc+usb games" but nothing has changed.
Am I doing something wrong or is it a bug?

Many thanks!

**Comment by swingflip** [comment]
We would need a copy of your regional.db from USB:/bleemsync/etc/bleemsync/SYS/databases/

So we can confirm exactly what your issue is

**Comment by cnterr** [comment]
My regional.db

[regional.zip](https://github.com/pathartl/BleemSync/files/2805323/regional.zip)

**Comment by swingflip** [comment]
@andshrew will need to review as he will better understand the issue if any

**Comment by GMMan** [comment]
I don't believe sort name is actually being used right now in any meaningful way when a new game is stored to the stock UI DB.
