### ISSUE TITLE
Bleem Sync 1.0 UI sorting error

### ISSUE THREAD

**Issue by crispycritter911** [pathartl/BleemSync#274]
Bleem Sync 1.0, Current limited usb ports bypassed, none powered 4 port Targus hub with 128GB Sandisk USB3.0 drive formatted to exFAT. When installing games via GUI, worked fine for the first 25 or so games. Afterwards that amount, the GUI randomly puts newer installed games out of alphabetized order. When you try to drag and drop to correct position. The list will reflect correctly and then reload back out of order. Some games that did load in 0.4.1 only load to black screen on 1.0. (Syphon Filter 1~3, Metal Gear Solid, Puzzle Fighter.)

**Comment by cnterr** [comment]
There's a field called "sort name", I tried to populate it for every game with an incremental number (10-20-30...) and the list now reflect my custom order but only in management console, in carousel the game list is not changed.

**Comment by swingflip** [comment]
This indeed sounds like a bug. Can you please try your best to describe in bullet points on how to replicate this and we can look at it straight away

**Comment by GMMan** [comment]
I can identify several issues in this single ticket:

- BSUI inserts new games in odd position after manually ordering games
- BSUI not committing custom order correctly
- Automatic alphabetizing not working correctly
- Sorting by sort name may not be working

Can we separate each problem out into a separate ticket?

**Comment by TheGreenGoblin** [comment]
When I encountered this, it seemed to me that the games on the console were placed in the order that they were added and/or updated. Placing them in the desired order may be possible, but is going to take some work, especially if you have a lot of games.

**Comment by cnterr** [comment]
Initially it seemed to me but when I tried to update some titles nothing has changed, with or without the option 'If true then auto alphabeticalise emmc+usb games' activated.
For the moment I "solved" with a stupid workaround by reactivating the option 'If true then auto alphabeticalise emmc+usb games' and adding a progressive number in front of my 287 titles (001 - ,002 - ,003 - ...)

**Comment by swingflip** [comment]
I will close this issue and raise a mega ticket with the 4 bullets outlined above in one task and assign it to both projects for 1.1
