### ISSUE TITLE
BleemSync UI Page - 'Uh oh something went wrong' Error

### ISSUE THREAD

**Issue by denizen8** [pathartl/BleemSync#276]
When adding a .bin and/or .cue file the progress gets to around 30% before the error message appears. Seems to happen with every title, all stop at the exact same point on the progress meter.

**Comment by swingflip** [comment]
Your USB will be browning out due to too high draw of current on the front USBs. The issue is detailed under the FAQ of the release page https://modmyclassic.com/bleemsync/
