### ISSUE TITLE
Connecting the PSC to Ubuntu creates multiple connections

### ISSUE THREAD

**Issue by cowanh00** [pathartl/BleemSync#277]
When connecting the Playstation Classic via Ubuntu a new connection is created each time in Network Manager, it's necessary to select Link-Local Only in the settings but this is not saved as it appears the MAC address is not recognised and a random one is created each time.

**Comment by swingflip** [comment]
Confirmed bug. I think we are assigning a bad hash for the MAC and it's not being accepted by ubuntu

**Comment by swingflip** [comment]
Need to look at changing the Kernel Configuration for the RNDIS. Needs to be looked at in conjuction of OTG and Overlay Support

**Comment by GMMan** [comment]
MAC address appears to be configured using binary rather than text. Will need to check if wceis should be enabled, if it's not already, as apparently Windows can autodetect this kind of device.

**Comment by Zibri** [comment]
Also, on Ubuntu 17.10 I get this:

> enp0s20f0u11: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet6 fe80::ffb9:7678:d3df:c469  prefixlen 64  scopeid 0x20<link>
>         ether 9e:85:48:15:c0:6b  txqueuelen 1000  (Ethernet)
>         RX packets 8  bytes 536 (536.0 B)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 196  bytes 43393 (43.3 KB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Does not get any IP.
