### ISSUE TITLE
Fix bug with BSUI when adding cue with CAPTALISED FILENAME

### ISSUE THREAD

**Issue by swingflip** [pathartl/BleemSync#278]
When adding .CUE via BSUI the basename includes .CUE and isn't remove before being inserted in to the table.

**Comment by andshrew** [comment]
Believe the fault is here:
https://github.com/pathartl/BleemSync/blob/c08669d68cc691199d36dc308ff5cbe38f4a5385/BleemSync.Extensions.PlayStationClassic/BleemSync.Extensions.PlayStationClassic.Core/Services/GameManagerService.cs#L105

However should we also silently rename any uploaded .cue files with an upper case extension to lower case on the basis that the Stock UI assumes the extension will be lower case, and therefore wouldn't ordinarily be able to launch an upper case one (more of an issue now we support case sensitive file systems).

**Comment by andshrew** [comment]
I think for now let's just rename .cues and maybe .pngs (need to double check if the Stock UI is explicitly expecting lower case extensions for those) and leave the other files as they are. The intercept script will need some modification to be fully case sensitive aware.
