### ISSUE TITLE
Compile Notes for 1.0.1 HOTFIX 

### ISSUE THREAD

**Issue by swingflip** [pathartl/BleemSync#279]
Need to compile the release notes for the 1.0.1 HOTFIX. This process will be improved for next hotfix

**Comment by swingflip** [comment]
**Payload Changes**
- Remove retroarch-core-options.cfg on RA boot to prevent crap core options overriding fixes
- fixed broken RA font on copy over from console
- Migrate now migrates over cores and bios files correctly
- Added Credits and License information
- Added Uppercase support for alternative format games
- Fixed network RA buildbot issues.
- Fixed JAPAN console RA stock game list in RA GUI
- Fixed JAPAN stock EMMC games to prevent crashing when loading BS1.0 on JP console
- Optimised on console SQLITE3 code
- Fixed the chance of RA overwritting good fixed configs with crap ones.
- Fixed Old RA folder not moving to remove/ after migration 

**UI Changes**
- Fix database entry generation when .cue file extension is not all lowercase.
- Fixed issue where cue files were being created for pbp files. No longer necessary with intercept updates.
- Fixed issue with cue files with capital filenames being added to the system improperly
- Added full rebuild regional.db button to BleemSync UI

**Comment by swingflip** [comment]
**Payload Changes**

- fixed broken RA font on copy over from console
- Migrate now migrates over cores and bios files correctly
- Added Credits and License information
- Added Uppercase support for alternative format games
- Fixed network RA buildbot issues.
- Fixed JAPAN console RA stock game list in RA GUI
- Fixed JAPAN stock EMMC games to prevent crashing when loading BS1.0 on JP console
- Optimised on console SQLITE3 code
- Fixed the chance of RA overwritting good fixed configs with crap ones.
- Fixed Old RA folder not moving to remove/ after migration 
- If no retroarch core options config exists then create. (Stops overwriting existing global core configs)
- Changed config logic so if no cfgs used for BS or RA then create them on load with defaults
- ADDED UPDATE_CONFIG, UPDATE_RA_CONFIG and UPDATE_BOOT to supported flags (use to force update cfg with defaults)


**UI Changes**

    * Fix database entry generation when .cue file extension is not all lowercase.

    * Fixed issue where cue files were being created for pbp files. No longer necessary with intercept updates.

    * Fixed issue with cue files with capital filenames being added to the system improperly

    * Added full rebuild regional.db button to BleemSync UI

**Comment by swingflip** [comment]
(FINAL)
**Payload Changes**

- fixed broken RA font on copy over from console
- Migrate now migrates over cores and bios files correctly
- Added Credits and License information
- Added Uppercase support for alternative format games
- Fixed network RA buildbot issues.
- Fixed JAPAN console RA stock game list in RA GUI
- Fixed JAPAN stock EMMC games to prevent crashing when loading BS1.0 on JP console
- Optimised on console SQLITE3 code
- Fixed the chance of RA overwritting good fixed configs with crap ones.
- Fixed Old RA folder not moving to remove/ after migration 
- If no retroarch core options config exists then create. (Stops overwriting existing global core configs)
- Changed config logic so if no cfgs used for BS or RA then create them on load with defaults
- ADDED UPDATE_CONFIG, UPDATE_RA_CONFIG and UPDATE_BOOT to supported flags (use to force update cfg with defaults)
- Added Xpad driver support. Loads more controller support added, including Xbox 1, Xbox 360 and steam controller support. Mostly complete list available here: [list](https://gist.githubusercontent.com/swingflip/70e5ec3e4b81e3e87d15823eaf241a09/raw/71e80ed9dd183335ed6e6c3adf7672e67d3c6839/gistfile1.txt)
- Added SDL mapping support for the boot menu, [(List of mapped contollers)](https://github.com/pathartl/BleemSync.Payload.PlayStationClassic/blob/master/bleemsync/etc/boot_menu/gamecontrollerdb.txt)
- Added physical console button support for the boot menu 
(`reset` toggles options. `open` selects that option)
- Changed memory configuration to prevent crashes from occurring when memory limit is nearing. We now over commit memory so a lot of issues should now be prevented.
- overcommit the DRAM
- Created extra fast swap ram totalling to 512mb more memory split across 4 cores into 128mb banks to increase compatibility, stability and slight performance (in some small cases) 
- Added new bleemsync build of RetroArch 1.7.6
- UPX'd1.7.6
- Optimised Monochrome XMB theme assets for Ozone
- Compressed all RA bundled assets 
- Added brand new Ozone theme as default (won't override existing set ups)
- Added compressed Ozone theme assets
- Prepped some code for OverClocking and network support within RA
- Optimised GDB and SQLite3
- Improved initial RA directory structure
- Optimised RA as a whole down from 18.2mb to 8.23mb (approx 50% reduction whilst include many more features)
- Optimised whole payload and reduced size


**UI Changes**
- Fix database entry generation when .cue file extension is not all lowercase.
- Fixed issue where cue files were being created for pbp files. No longer necessary with intercept updates.
- Fixed issue with cue files with capital filenames being added to the system improperly
- Added full rebuild regional.db button to BleemSync UI

**Comment by dridder123** [comment]
You guys are freaking awesome thank you
