### ISSUE TITLE
new Version BleemSync 0.3.0 wont start

### ISSUE THREAD

**Issue by Unmortal81** [pathartl/BleemSync#28]
So i tried the new Version BleemSync 0.3.0, but no luck to Start, only the Sony PSX Boot logo appears, after that: black screen. I tried new USB Stick with no games on it, but no luck to. Tried another stick: same result.  Old 0.2.2 Version still boots up. Oh: Win7 Version tried.. wont work under Win 10? But BleemSync.exe still do its work.
Greets

**Comment by tH3TragiKprinCe** [comment]
Same happens to me. Screen goes black half way into initial Sony Computer Entertainment gold logo screen.

**Comment by FreudienSlip** [comment]
Same to me. Also when rebooting, most stock games do not start now. A few do. About to try previous version. Not sure what happened to stock settings though. (could be from gpg old hack? but never hit any noticeable snags with that)

**Comment by FreudienSlip** [comment]
Previous version is working.

**Comment by GforceMI69** [comment]
I have the same Black screen issue, also got the first OG 2 games in the carousel not working after using V3.0, any ideas on how to get those back ? I tried both reset options from the settings menu and both do not fix it.

**Comment by mpalpha** [comment]
"Carriage Return Line Feed"

**Comment by DaveyyP** [comment]
Hello all i am having the same problems as the other with this update, but also having a problem with the stock 2 games not working booting up cool boarders2 and the destruction derby. i did have gpghax on my system i then uninstalled it and tried using bleemsync 0.2.2. i had it work just when i went to load a custom game my controller stopped working. after that i tried to load back the normal 20 games and that's when i had the problem were two games wont work. i also the tried the new update 0.3.0 and i got the black screen everyone is talking about. anyone think they can help me get these games working? sorry i also tried to uninstall everything after these problems and i did it but the two games still wont load. any help would be get thanks

**Comment by DaveyyP** [comment]
> 
> 
> I have the same Black screen issue, also got the first OG 2 games in the carousel not working after using V3.0, trying to add 2 games to slot 1 & 2, any ideas on how to get those back ? I tried both reset options from the settings menu and both do not fix it.
> 
> and something unusual with the first 2 games not running in stock state, however, if I fire up the console without the usb key installed the first game will not run, but as soon as I insert the usb key with Bleemsync 2.2 while the console is still running and I try to play, it switches over to the 2.2 menu with my game set to use slot 1 on usb, and the custom game runs and plays.
> 
> my guess is something is retargetting the stock games to run from the usb key somehow, after trying v3.00
> 
> think I figured out why we lost the use of some games, after trying to boot with V3 and getting black screen and rebooting, the console has set target game file directory to the usb games like it would set to start up with any of the stock games last played.

did you get it to work?

**Comment by pathartl** [comment]
@DaveyyP This issue tracker is related specifically to issues/bugs with BleemSync. Since you had gpghax installed previously, your internal games are probably affected from that. Someone might be able to help you out in the [ModMyClassic Discord server](https://discord.gg/mteuJtk), but this is not the channel for that type of discussion.

**Comment by pathartl** [comment]
This black-screen-on-boot issue has been fixed in [0.3.1](https://github.com/pathartl/BleemSync/releases/tag/0.3.1). Please remove your `System`, `BleemSync`, and `lolhack` directories and replace them with the contents of the release zip.



Blame Windows line endings.

**Comment by DaveyyP** [comment]
@pathartl hey just want to let you know this update did fix the problem of it not loading thank you. now i just need to find out how to fix those games.
