### ISSUE TITLE
Blank games

### ISSUE THREAD

**Issue by chaud-froid** [pathartl/BleemSync#292]
Hello,
I add some games, they work fine but some of them had a blank cover so I try to modify them with the gui but I got an error. After that, I delete them and put them in again.
And now, I have theses games in double. One is the game that work just fine with cover and another one with no cover and doesn't do anything when I click play.
How can I delete them ? They doesn't appear in the gui on the web browser :(

EDIT : after some investigation, it seems that I have the problem with 2 games and I have 2 empty folders in the "game" folder on my USB stick. I think that if I delete them, the problem'll be solved but it's impossible to delete them. windows says that it can't delete. I can't even rename these folders. How can I delete that ? I tried unlocker but it doesn't work

**Comment by PattonPlays** [comment]
Hey @chaud-froid  if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd

**Comment by ryad-eldajani** [comment]
Can confirm the same/similar issue.

Deleting and re-uploading games sometimes causes blank (i.e. "invisible") covers.

Steps to reproduce:
- Delete Game A from web UI
- Re-Upload Game A from Web UI
- Boot into stock UI
- Game A appears twice, one correct variant with cover, one incorrect variant without cover
