### ISSUE TITLE
Limit title entry in bleemsyncui to max 30 chars

### ISSUE THREAD

**Issue by filmcriticbeta** [pathartl/BleemSync#294]
Issue: Games with titles longer than 30 chars do not fit into the stock ui

Steps to reproduce: 
* Add a game with a long title ( eg Crash bandicoot 2 )
* In the stockui, the title appears truncated.

Possible Solutions:
* Limit text input in Bleemsyncui to a max 30 chars
* Update the BleemSync Central database so that no records have titles longer than 30 chars

**Comment by GMMan** [comment]
Alternatively: allow user to input newlines in the name. It's used by some games on the Japanese region console.

**Comment by pathartl** [comment]
Newlines makes sense to me. It's something that we can split the string by if needed on other platforms. We shouldn't be limiting the text input on the UI or modifying entries in Central to compensate for this. It's a visual issue, not a data issue.

**Comment by swingflip** [comment]
FYI @pathartl @GMMan IIRC /n newlines are supported with the database as of 1.0.1 to fix the Japanese bug so this is actually a feature technically supported by 1.1 and just needs confirming. I will add to the debate queue for the UI project.
