### ISSUE TITLE
[Question] Is there a way to add games manually on the usb stick

### ISSUE THREAD

**Issue by Nosferatumiamor** [pathartl/BleemSync#295]
Hello and thanks for the great job done with bleemsync 1.0.0.
The only problem I have comes from the way to upload games on the USB stick, through the UI. It's nice and easy, but most of the time it just crashes or gets stuck at the end of the loading screen.
So I was wondering if there's a way to get the job done manually, like in previous versions ... by adding the games directly to the USB stick from the computer, and using the bleemsync exe to scan them and add them to the gamelist before plugging the stick to the console.
Yeah I know, this method was a bit of a pain, but at least it had the job done. 

The UI is nice and promising, and it has great features, but importing whole games through it feels a bit nonsensical. It would be better to add the games beforehand on the stick and then have the UI scan, recognise and organise the games.

**Comment by pathartl** [comment]
No. We are looking at improving the workflow so adding games is quicker / more convenient, but we are moving away from the auto-scan-drive methodology.
