### ISSUE TITLE
Fix bug with BS UI generating a .cue file for pbp format games

### ISSUE THREAD

**Issue by andshrew** [pathartl/BleemSync#297]
When a user uploads a game in .pbp format BS UI generates a .cue file for the game.

This is not inherently a problem for single disc games as that .cue file is never used - the intercept script will detect the .pbp file on launch and bypass it.

However for multi disc games this may generate additional bad entries on the disc swap screen (a disc entry for the potentially invalid .cue, and one for the .pbp).

There's no real reason for a .cue to exist for a game in .pbp format so BS UI should not generate these.

**Comment by pathartl** [comment]
Easy to remove. The .cue creation was added before the intercept was in place.
