### ISSUE TITLE
Overmounted entries still use the built-in memory card/save state locations

### ISSUE THREAD

**Issue by Lastdancer-RS** [pathartl/BleemSync#3]
Right now when saving to a memory card or saving a save state, the entries are stored on the built-in memory.

Loaded one entry onto USB, played until I could save, saved to memory card slot 1. Pressed the reset button on the console to return to menu and saved the state. Powered down the console, unplugged, removed USB stick, plugged in the power, started up the console, and the game of the same gameID had a save from the other game, as well as the save state.

I'm pretty sure this is a known issue and something you plan to address but I figured I'd mention it.

**Comment by pathartl** [comment]
Yep, known issue. Thanks for opening this.

**Comment by pathartl** [comment]
Resolved in [0.3.0](https://github.com/pathartl/BleemSync/releases/tag/0.3.0)
