### ISSUE TITLE
Only switch eMMC to more memory inside PSC?

### ISSUE THREAD

**Issue by pawnlab** [pathartl/BleemSync#306]
Hello. 

As I understand, we cannot expand the memory like in SNES and NES (SDCard Mod), because there are no pins for this. It turns out that we can only replace Nand memory with a more extended one? Or in the future it is planned to solder something inside the console? Maybe based on existing ports or something? 

Thanks for all what you doing.

**Comment by pathartl** [comment]
This is out of the scope of the BleemSync software project.

The real answer is there are no SD pins on board. Additionally, there is no unpopulated USB pins on board. You could replace the eMMC chip, but that requires quite a bit of skill. Our best bet going forward is going to be OTG.
