### ISSUE TITLE
HELP! I cant use my USB STICK anymore

### ISSUE THREAD

**Issue by Gusheanu** [pathartl/BleemSync#308]
I plugged my USB stick in the ps and then I plugged it back into my laptop to add games, but i accidently clicked "format" when right clicking on my stick and now it wont work. I can see the stick but I cant open it becouse I need to format it, but I cant format it becouse it either says "Disk cant be written" or "Windows failed to format this disk". I tried e few fixes but nothing seems to work

**Comment by GMMan** [comment]
Hi, thanks for filing an issue. Because this isn't directly related to the BleemSync app, could you join the ModMyClassic Discord for support? https://discord.gg/8gygsrw
