### ISSUE TITLE
Can't update games in BSUI and 95% of the games don't work after migration

### ISSUE THREAD

**Issue by tommys77** [pathartl/BleemSync#309]
I migrated with 31 games installed, all of them working. After booting Bleemsync, only three of the games work. Using a powered hub and a 64GB Cruzer Fit,  Tried removing the images, since they were mostly renamed jpgs anyway, but didn't help, and only gave me blanks instead. Didn't do any good, so I tried adding the image back with Bleemsync UI, and when I try to save it fails.

**Comment by GMMan** [comment]
Can you post your original regional.db file?

**Comment by tommys77** [comment]
> Can you post your original regional.db file?


[regional.zip](https://github.com/pathartl/BleemSync/files/2819015/regional.zip)

**Comment by GMMan** [comment]
Your DB seems to look OK. Could you describe what "not working" and "error" looks like? It would be helpful if you can attach the logs from the logs folder on your USB drive after trying to upload or run a game.

**Comment by Mr0Abdo** [comment]
Delete Evrything except games folders and install again the bleemsync0.4.1  on to your usb then from usb open bleemsync.exe in folder Names ( Bleemsync ) that's it u should have internet

**Comment by GMMan** [comment]
@Mr0Abdo That doesn't really make sense. You're just telling them to install 0.4.1, and that won't do anything to make 1.0 work, especially that the game folder layout is a bit different.

**Comment by Mr0Abdo** [comment]
Oh yeah you right the folders changed from GameData to only the only filters numbers 1-2-3-4-5 where the game data no more gameData fielder with new Bleemsync

The only way you got put the games again with old directory but this time no more adding new game the data base only read it in the begging then will not appear if u add another game with issue

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Mr0Abdo** [comment]
> @Mr0Abdo That doesn't really make sense. You're just telling them to install 0.4.1, and that won't do anything to make 1.0 work, especially that the game folder layout is a bit different.

Coz i have issue with adding game in new bleemsync 1.0

but in Previews Bleemsync the Bleemsync.exe Help me allot that why i use it to add all my 100# Games then i Upgraded agian to Bleemsync 1.0  no time to wait and its working good and well

best of luck

**Comment by C0llab0rat10n** [comment]
Make sure your USB has not run out of space. And, scan your USB for repairs as I get that issue too once in a while. And after the repairs are fixed, I can add games games again. It works for me all the time.
