### ISSUE TITLE
Controllers - Rapid Button presses

### ISSUE THREAD

**Issue by luminaire11** [pathartl/BleemSync#314]
Got Bleemsync loaded. No sweat. But I was playing Brave Fencer Musashi with Retroarch and while trying to fuse an enemy the system does not recognize rapid button presses. In fact, even with a rapid fire controller the system seems to struggle to read the button inputs. Can this be fixed?

**Comment by swingflip** [comment]
unfortunately no, this is completely down to the core and the emulation
