### ISSUE TITLE
.pcsx folder needs to be elsewhere for multidiscs

### ISSUE THREAD

**Issue by pascl** [pathartl/BleemSync#317]
Hi. I realized that the swap disc ui doesn't display correctly in the stock ui:
* For a 2cd game, 3 cd appears.
* For a 3cd game, 4 cd appears.
* If I force the disc change by the menu on a 1cd game, 2cd appears.
* For a 4cd game, the swap disc ui doesn't appear, I have to go left or right in the pcsx menu to select a disc by its cue file.

But it works well with the internal games.

The difference between them is the presence of .pcsx in the same folder or not.\
Maybe it's more complicated than that but if I remove the .pcsx folder and put it elsewhere (by modifying some paths about line 145 in 0050_bleemsync.funcs), the disc swap ui is ok.

**Comment by Mr0Abdo** [comment]
yeah you right for me i add another folder for disc no# 2 so when u finish disc one go to disc tow like its another game

thanks
