### ISSUE TITLE
Some Custom game not working

### ISSUE THREAD

**Issue by Pierinolartista** [pathartl/BleemSync#32]
I have install 7 games but some game not working as like "Winning Eleven 4" "Winning Eleven 2002" (black screen or Gran Turismo (EU and US versione) there are more glitch. 
What can i do?

**Comment by acocalypso** [comment]
Final Fantasy VIII (German) isn't working as well. I see the Playstation intro and then a black screen.
On my pc it is working.

**Comment by Pierinolartista** [comment]
Update for Winning eleven 2002 is bad iso, anyone try to install Gran Turismo?

**Comment by pathartl** [comment]
Closing this as it's not related directly to the development of BleemSync. Game compatibility with the emulator on the system is not a priority of this project.
