### ISSUE TITLE
Suggestion: BleemSync App GUI

### ISSUE THREAD

**Issue by AceTheSpaceCase** [pathartl/BleemSync#320]
A couple of minor quality of life suggestions. 

Move "ADD NEW GAME" button from the bottom of the game manager to the top. 
This would save scrolling up and down longer lists of games to add a new one.

Scale the UI down 10% so that the "UPDATE GAME"/"ADD GAME" buttons appear with out the need to scroll in 1920x1080 resolution.

That last one may just be me (strange screen arrangement) but I currently set the web page zoom to 90% and it fixes the issue.
![bleemsyncuibefore](https://user-images.githubusercontent.com/47383803/52336222-5821ec80-29d2-11e9-8ac0-580a648dd94e.jpg)
![bleemsyncuiafter](https://user-images.githubusercontent.com/47383803/52336231-5a844680-29d2-11e9-8e2f-319718312664.jpg)

**Comment by TheGreenGoblin** [comment]
I would also suggest the ability to work directly to the flash drive without the need to go through the console, especially if it's a drive that requires a powered USB hub.  Hakchi did this, why can't BleemSync?

**Comment by AceTheSpaceCase** [comment]
> I would also suggest the ability to work directly to the flash drive without the need to go through the console, especially if it's a drive that requires a powered USB hub. Hakchi did this, why can't BleemSync?

The reason is can't is that there currently is no independent desktop application but they are working on it as can be seen in other posts. The current application runs from the classic its self so requites the Flash drive to be plugged in to it directly.

**Comment by TheGreenGoblin** [comment]
> > I would also suggest the ability to work directly to the flash drive without the need to go through the console, especially if it's a drive that requires a powered USB hub. Hakchi did this, why can't BleemSync?
> 
> The reason is can't is that there currently is no independent desktop application but they are working on it as can be seen in other posts. The current application runs from the classic its self so requites the Flash drive to be plugged in to it directly.

It was my understanding that this topic was about the upcoming desktop app.

**Comment by AceTheSpaceCase** [comment]
> > > I would also suggest the ability to work directly to the flash drive without the need to go through the console, especially if it's a drive that requires a powered USB hub. Hakchi did this, why can't BleemSync?
> > 
> > 
> > The reason is can't is that there currently is no independent desktop application but they are working on it as can be seen in other posts. The current application runs from the classic its self so requites the Flash drive to be plugged in to it directly.
> 
> It was my understanding that this topic was about the upcoming desktop app.

Nope, the web based APP, as the images attached clearly show.

**Comment by pathartl** [comment]
The desktop app will essentially be the same as the on-console web app as it exists right now. A few things like USB drive destination selection / management will be added for quality of life purposes.

**Comment by AceTheSpaceCase** [comment]
I think we have kind of gotten off topic a little, but I am looking forward to the desktop app.
