### ISSUE TITLE
Order of games

### ISSUE THREAD

**Issue by BeatzByMiix** [pathartl/BleemSync#321]
Throughout Bleemsync 1.0 I've been adding them in alphabetical order myself, for some reason when I got to M and started added games the first few where fine, now when I got to Megaman 8, Legends and Legends 2 they appear at the top of the page. I've manually moved the folders down but they keep going back to the top, same when I launch Bleemsync.

For example the top folders are...

007 Racing
Megaman 8
Megaman Legends
Megaman Legends 2
007 Tomorrow Never dies
(And so forth).

Has anyone had this issue? I've even ticked the alphabetical order in the UI settings and that still doesn't make a difference. (OCD is kicking in lol)
Thanks.

**Comment by BeatzByMiix** [comment]
Any help would be appreciated :)

**Comment by swingflip** [comment]
@BeatzByMiix Can you try again in 1.0.1 please and recreate an issue if it appears again
