### ISSUE TITLE
Disney's Tarzan (SCUS-94456) 

### ISSUE THREAD

**Issue by Mr0Abdo** [pathartl/BleemSync#327]
I Add more than 40 games and its working good except couple games including Disney's Tarzan (SCUS-94456) 

the controller not pressing start and select and the button not working is Square + circle + triangle + and X

but the arrow of direction working good up down let right all good means I cant start the game with

Also crash Bandicoot 1

Also Winning Eleven - J.League Jikkyou Winning Eleven 3 (SLPM-86162)

**Comment by AnotherLife** [comment]
I added Crash Bandicoot 1 just fine earlier today, works good.

**Comment by Mr0Abdo** [comment]
Also working with me but the controller not working but game working good controller hang there

But not with other games something wrong ! I didn’t figure yet !

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
