### ISSUE TITLE
FEATURE - Add C64 mini export facility

### ISSUE THREAD

**Issue by swingflip** [pathartl/BleemSync#328]
https://cdn.discordapp.com/attachments/496469652076232719/543098192456318997/Capture2.JPG

Part of a bigger picture project. Now I managed to get the hack payload prototype up and running we should consider expanding the scope at some point to cover the exporting games to USB for the commodore 64 mini. There will need to be a seperate button for the C64 and options would need to be broken down by console too.

I attached a screenshot to roughly show the current game layout will be

**Comment by pathartl** [comment]
What do the .tsg files look like?

**Comment by darbyram** [comment]
Something like this..

T:Highway Encounter
X:64,pal,sid6581
D: (Game game synopsis)
D: (Game game synopsis) in different language
D:  as above etec...
A:Pedigree
M:Fred Gray
E:shoot
Y:1986
F:games/HIGHWAY-ENCOUNTER.vsf.gz
C:covers/HIGHWAY-ENCOUNTER-cover.png
G:screens/HIGHWAY-ENCOUNTER-01.png
G:screens/HIGHWAY-ENCOUNTER-02.png
J:2*:JU,JD,JL,JR,JF,JF,5,JF,JF,,,,5
