### ISSUE TITLE
EPIC - Finish of C64 Mini Payload Prototype

### ISSUE THREAD

**Issue by swingflip** [pathartl/BleemSync#329]
I already started the prototype C64 mini payload hack codenamed BleemQuark. I need to finish this off. It works and runs with manual intervention but jj_0 would also preferably need to update the ramfs image so it's more stripped down and launches the payload injection.

We also need to put the source up for the ramfs image source and others.

**Comment by whip28** [comment]
Driveway you improved the playback speed of the C64 on PS Classic ?.

**Comment by Mr0Abdo** [comment]
best of luck

**Comment by dridder123** [comment]
i still cant get any of my games to load on 1.0.0
