### ISSUE TITLE
Games with more than 1 bin

### ISSUE THREAD

**Issue by jayphung90** [pathartl/BleemSync#33]
There a few games I downloaded that has more than 1 bin, multiple tracks. What do I do?

**Comment by levigilbertson** [comment]
I tested this and they should work without issue just make sure they are named correctly and then edit the .cue to match.
ie 
SLUS-00067 (Track 1).bin, SLUS-00067 (Track 2).bin and so on...
.cue looks like
FILE "SLUS-00067 (Track 1).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
FILE "SLUS-00067 (Track 2).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00

**Comment by jayphung90** [comment]
Yes it works! Thank you! Maybe you can post this in the front to let others know
