### ISSUE TITLE
Bleem Sync 1.0 Crashing when Booting

### ISSUE THREAD

**Issue by voodoochild718** [pathartl/BleemSync#330]
So I have gotten a USB Stick (a Samsung 3.1 USB 128GB) to work. I learned that if I plug in my USB drive into my comp and run BleemSync, syncing all the games through the pc, The PS Classic boots into Bleemsync instantly when I plug into the classic without a USB hub. I have gotten 106 games on the USB stick and I was having errors when trying to add more games to the disk. 

The USB is half full so I decided to open up the Bleemsync and the Retroarch programs from the PC to sync the games again and the Classic LED turns to Orange and I get an image of Crash on my screen. (Genius feature by the way).

I have attached copies of all the logs to the post. Is there anything I can do to fix this without reloading all of those games again? 

[bleemsync.log](https://github.com/pathartl/BleemSync/files/2847430/bleemsync.log)
[bleemsync_ui.log](https://github.com/pathartl/BleemSync/files/2847431/bleemsync_ui.log)
[bootloader.log](https://github.com/pathartl/BleemSync/files/2847432/bootloader.log)

**Comment by TheGreenGoblin** [comment]
Flashdrives getting corrupted seems to happen a lot.

**Comment by voodoochild718** [comment]
So that means that I have to reinstall the program and all of the games again? @TheGreenGoblin

**Comment by TheGreenGoblin** [comment]
> So that means that I have to reinstall the program and all of the games again? @TheGreenGoblin

Not sure if that's what happened in your case, but it's a worst case scenario that's happened to me a few times.

**Comment by Mr0Abdo** [comment]
all you need you get the right usb working with for me same thing happned until i figure it out its all matter of usb 
my usb its 2.0 and not any 2.0 work by the way so just use sandisk Cruzer Blade red one its working good and Delete all your data do it again unless you have issue adding new games

**Comment by swingflip** [comment]
@TheGreenGoblin @voodoochild718 it's not corrupted. Infact 95% of the time it's not corruption. The application tried to generate a basic SQLite database on the usb and it timed out after 45 seconds.

This could be down to an extremely slow USB or something was right with the intial copy.

What format is the USB? You would of installed the extra payload so you can just try formatting the usb to exFAT and trying it again.
