### ISSUE TITLE
bleemsync 1.0 can not working in the HK and japanese version PS1 classic

### ISSUE THREAD

**Issue by cashimi001** [pathartl/BleemSync#331]
MY PS classic it si HK version ,bleemsync 0.41 working fine,but bleemsync 1.0 can not working when select bleemsync on boot menue, the ps 1 ll power shutdown.but it is working in my EU version PS classic very fine.
[bleemsync.log](https://github.com/pathartl/BleemSync/files/2850066/bleemsync.log)
[bleemsync_ui.log](https://github.com/pathartl/BleemSync/files/2850067/bleemsync_ui.log)
[bootloader.log](https://github.com/pathartl/BleemSync/files/2850068/bootloader.log)

**Comment by k3nnk3nn** [comment]
I'm also having the same issue with my PS1 Classic Jap Edition. After, I select Bleemsync, the device goes down and the led becomes yellow.

**Comment by GMMan** [comment]
Fixed in #263
