### ISSUE TITLE
Fake ps3 controller always vibrating

### ISSUE THREAD

**Issue by SpardaXV** [pathartl/BleemSync#332]
I have a fake dualshock 3 controller (called 'shanwan gamepad ps3' in retroarch) and when I connect it to the playstation classic I have a problem: It starts to vibrate and never stops doing it. This happens with both the normal console and the console with a pendrive with bleemsync installed.

In retroarch all buttons and analog work without problems, but with the control vibrating continuously (I would like to test if the vibration also works in pcsx rearmed, but I can not do it because the control does not stop vibrating)

It seems that this error is common with Raspberry pi 2/3 and retropie. In this case, it was solved (it seems) with the following linux script:

Issue: https://github.com/RetroPie/RetroPie-Setup/pull/2252
Code: https://github.com/raspberrypi/linux/commit/492ca83c3d19fba1622164f07cd7b775596a7db2

Can this code help solve this problem in PSC via bleemsync in future updates?

These fake dualshock 3 are a cheap and easy way to get a gray (silver) controller similar to the original dualshock of playstation 1. As I said before, all buttons work in retroarch and if it were not for the problem I describe, I think is a very good option to use with the pcsx rearmed core.

Thanks to all the people involved in this project

**Comment by andshrew** [comment]
It should be possible to incorporate these same changes into hid-sony, but believe it won't be possible until the kernel can be replaced.

**Comment by swingflip** [comment]
Yeah we can ionclude this as an adding kernel module. We can't include it as part of the kernel IMO due to the limited file storage allocated for the kernel. 

Lets add this in 1.1
