### ISSUE TITLE
[Suggestion] Ethernet Support and Network loading support

### ISSUE THREAD

**Issue by alienbiker99** [pathartl/BleemSync#334]
This might be more of an extension to issue #179.
It might be a pipe dream but since the usb otg support is happening, it would be pretty cool to have support for a wired 100MB ethernet adapter.

Both this and #179 could then load games from via a network share ftp/samba/nfs and load from a local server with much higher storage capacity.

I know there were projects for the ps2: openps2loader which used smb and ps3: ps3netsrv which allows for network streaming (not sure how).

This would bypass most of the storage related issues for people who keep the PSC at home.

**Comment by swingflip** [comment]
Hi @alienbiker99, thanks for your suggestion
This is an extension of #179 and will be included along with wifi support. We need to include certain config in the kernel for networking when we do OTG so it will be done. I will close this issue for now as it's pretty much part of 179 as stated
