### ISSUE TITLE
DISC table entry not being generated for pbp format game

### ISSUE THREAD

**Issue by andshrew** [pathartl/BleemSync#335]
Following on from https://github.com/pathartl/BleemSync/issues/297

In 1.0.1 uploading a game in .pbp format results in no entry being created for the game in the DISC table.

The game itself is correctly identified, and the actual files are uploaded to the system.
```
root@bleemsync:~# ls /media/games/3
SCUS-94244.pbp  SCUS-94244.png
```
Example database files:
https://cdn.discordapp.com/attachments/522907882379804712/545235200536477732/BleemSync.db
https://cdn.discordapp.com/attachments/522907882379804712/545235220195049483/regional.db

Issue may be down to an expectation of a .cue file existing when generating the basename:
https://github.com/pathartl/BleemSync/blob/c9663311b84db44e12d2ea18a6668c8b28a85fc8/BleemSync.Extensions.PlayStationClassic/BleemSync.Extensions.PlayStationClassic.Core/Services/GameManagerService.cs#L91

**Comment by Mr0Abdo** [comment]
thanks 

and why not use the classic way adding games Bin/cue files and enjoy it i thing the pub is big deal with server


thanks

**Comment by GMMan** [comment]
Some people like PBP better and don't want to convert to bin/cue

**Comment by Mr0Abdo** [comment]
yeah you right  and i dont mean converting i mean downloading it as its bin/cue files ar ready and many millions there 


thanks best luck

**Comment by GMMan** [comment]
Sure. Would you mind keeping opinion pieces out of issues in progress?

**Comment by Mr0Abdo** [comment]
sure and sorry for disturb
