### ISSUE TITLE
1.0  problems adding games manually 

### ISSUE THREAD

**Issue by Kenshin20** [pathartl/BleemSync#337]
Good Afternoon 

i tried to add some games manually since it didn't find the Cover or i want to use a custom cover and after adding the game ( the cover on all my games will be gone or the UI will crash turning off my console ) 

how can i add custom .PNG covers for my games

**Comment by Mr0Abdo** [comment]
same here dude i think its time for them to make BleemSync.exe pc Version to Sync. all games and find cover if not u can laso add manually not like now ? its not working good like Previous Bleemsync 0.4 it was better than now thats my opinion

**Comment by pathartl** [comment]
You can drag custom covers into the cover area either when editing or adding a game.

A desktop port is in the works but requires some important work to be done on the back end code.

**Comment by Mr0Abdo** [comment]
its honor for me that that you reply and i know how much you working hard

i rellay appreciate what you doing for community

best of luck bro we love you
