### ISSUE TITLE
.7zip 

### ISSUE THREAD

**Issue by Kenshin20** [pathartl/BleemSync#338]
are you guys going to add compress images or 7zip  to save storage ?

**Comment by Mr0Abdo** [comment]
i dont understand your question but if you talking about games for psx u neet to extratct it to get the Bin/Cue File then u add it throw http://169.254.215.100:5000/Game/Manager By Connecting ur usb male to male 


and if u mean the roms for emulator some of it extraxt it like .gba .nes if its Sega no need extract 


hope i did help ya 


best of luck

**Comment by Kenshin20** [comment]
Sorry,  what i meant is will compress files ever work in the future?

**Comment by GMMan** [comment]
The emulator appears to have built-in support for images generated from PocketISO, but other than that, nothing for standard compressed archives. For the time being, if you want compression, use PBPs.

**Comment by AnotherLife** [comment]
Yeah, use PSX2PSP to convert your cue/bin to PBP, they are compressed.

**Comment by swingflip** [comment]
Yeah the recommended method is to compress to PBP for the psx games. I will close for now
