### ISSUE TITLE
I still have a black screen

### ISSUE THREAD

**Issue by alucard73** [pathartl/BleemSync#34]
Good evening,
I use version 0.3.1 and since my microSD 64 GB is no longer detect the console while with the version 0.2.2 I have no problem. I tested with another 64 GB USB same thing as my microSD, with the 32 GB I have a black screen

boot.log
killall: ui_menu: no process killed

**Comment by pathartl** [comment]
Can you post the log in `System/Preferences/UI` and `System/Preferences/Logs`?

**Comment by alucard73** [comment]
I can not, the files look corrupted and I can not extract them

I think there is too much incompatibility on USB for this console, should see if you can fix it

**Comment by DaveyyP** [comment]
@pathartl hey i just want to say thank you for your help i did reach out to the gpghax and i got the games not load working and then i got the bleemsync 0.3.1 to work great as well. thank you and i followed every step and worked great.
