### ISSUE TITLE
bleemsync page down?

### ISSUE THREAD

**Issue by poku12** [pathartl/BleemSync#341]
IS the bleemsync page down? i cant get in anymore, i tried reinstalling the drivers again but nothing works :(

**Comment by shezzam** [comment]
Issues here too.
Can’t get metadata or artwork to load.... 😢

**Comment by poku12** [comment]
yeah that problem also for me

**Comment by drwho2019** [comment]
I had to flash my usb stick 3 times what's going on with the ui

**Comment by shezzam** [comment]
The page leads up for me but no artwork, metadata 
, etc.... hope it’s temporary.

**Comment by drwho2019** [comment]
Ik it's frustrating it's making me think my files are corrupted. I left it plugged in earlier and it corrupted my sound on my system had to wipe it again.

**Comment by shezzam** [comment]
It’s back on.

**Comment by poku12** [comment]
artwork and meradata also?

**Comment by shezzam** [comment]
Yes

**Comment by poku12** [comment]
nope its down again

**Comment by pathartl** [comment]
It is up. Please do not create issues for Central related status issues. This issue board is for development purposes.
