### ISSUE TITLE
Game glitched during save... is it gone forever?

### ISSUE THREAD

**Issue by KingSinister7** [pathartl/BleemSync#343]
I am almost near the end of disc one in chrono cross and when I went to save the system glitched out and corrupted the save I think. (Using 0.4.1). When I rebooted the game it shows the file but won't load the save. Any hopes of getting it uncorrupted. Or is there a way to import other people's save files to bleemsync?

**Comment by pathartl** [comment]
BleemSync doesn't do anything in the form of memory card management, it simply points the built in emulator to where the game is located. The emulator (pcsx) uses .mcd files to store memory card data. If you were to replace your corrupted one with another in the same format, it should work fine.
