### ISSUE TITLE
Psc version problem

### ISSUE THREAD

**Issue by jinnhr** [pathartl/BleemSync#344]
Does the Hong Kong version not support BleemSync? Why can't I use the BleemSync after the tutorial is installed, please shut down directly and ask what is the problem?

**Comment by jinnhr** [comment]
After entering the BleemSync1.0.0 system, click on the BleemSync black screen. The indicator light turns orange.

**Comment by jinnhr** [comment]
[bleemsync.log](https://github.com/pathartl/BleemSync/files/2876957/bleemsync.log)
[bleemsync_ui.log](https://github.com/pathartl/BleemSync/files/2876958/bleemsync_ui.log)
[bootloader.log](https://github.com/pathartl/BleemSync/files/2876959/bootloader.log)

**Comment by swingflip** [comment]
Yes 1.0.0 has a bug. This was fixed in 1.0.1 which is about to release soon :)

**Comment by jinnhr** [comment]
> Yes 1.0.0 has a bug. This was fixed in 1.0.1 which is about to release soon :)

thank you very much

**Comment by GMMan** [comment]
Duplicates #331
