### ISSUE TITLE
Trying to get Bleamsyc to work with my playstation classic

### ISSUE THREAD

**Issue by geist009** [pathartl/BleemSync#345]
I am getting beyond frustrated with this. I did everything from this video https://www.youtube.com/watch?v=eX8GsaSQo64 and still no luck. The other videos are painful to go through. Each video doesn't help at all and it keeps leading me to download files that don't even help me with this. I keep going through all the steps. Plugging in the USB drive waiting for the light to blink and its does not blink orange and green. Can I get some help over here.

**Comment by dridder123** [comment]
If I may ask what version of bleemsync are you using

**Comment by dridder123** [comment]
And really he's doing too much in that video it's so much easier then what he's showing

**Comment by AnotherLife** [comment]
https://www.youtube.com/watch?v=rtH937J0UC0

Follow that one. And post on reddit if you have problems

https://www.reddit.com/r/PlaystationClassic/

**Comment by C0llab0rat10n** [comment]
make sure your usb cable is not too long and old. I was using a 8 foot usb and while it works great charging my phone it didn't work very well with bleemsync. I switched to a short cable and it worked great. Also, I have to wait a minute or two for my PC browser to see the PS1 Classic.  So connect your PS1 classic to the PC then wait a minute. Then turn it on and don't touch it. Sometimes mine will turn off afte 30's then turn back on. then wait a minute again. They try the browser to add games. I don't know why but it does and I use Firefox.

If you still have problem them it might be your USB stick. If the USB stick has issues then the broswer will not pop up with bleemsync to add games.

**Comment by TheGreenGoblin** [comment]
And if all else fails...

https://github.com/pascl/pbPSCReAlpha
