### ISSUE TITLE
PS Classic with Bleemsync 0.4.1 and NTSC games

### ISSUE THREAD

**Issue by OldWitch666** [pathartl/BleemSync#346]
Hello.
I live in Europe region and I have PS Classic with Bleemsync 0.4.1 installed. Console is switched to PAL version. Is that normal my NTSC games wont work? Its always stop on PS logo. European SLES work great.

Thanks for answers.

**Comment by dridder123** [comment]
When you try to play those do you have your PSC switch to ntsc

**Comment by dridder123** [comment]
If not hit select in Triangle get into settings and switch your system to ntsc and it should play fine

**Comment by OldWitch666** [comment]
Thank you. And when I do this i will be able to play both regions?
I cant switch, because I do not have working keyboard to do this

**Comment by dridder123** [comment]
With 0.4 point one you can use your controller hold select press triangle option menu is right there just use your controller

**Comment by OldWitch666** [comment]
OK, thank you :)

**Comment by dridder123** [comment]
No problem you're welcome

**Comment by OldWitch666** [comment]
Its me again I did what you wrote, but problem still exist.
For example I have MOH USA version with SLUS-00974 and I made a .cue file with:

FILE "Medal of Honor (U) [SLUS-00974].bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
And game still stuck on PS menu with strange, cutted words something like: 
Sony Com
puter Entertainment.

**Comment by dridder123** [comment]
Hum can you make a video and show me so i can help better

**Comment by OldWitch666** [comment]
Ok, here's the video:
https://youtu.be/26L6o3Wi6bg

**Comment by dridder123** [comment]
Humm dose the system load the pal games with no problem

**Comment by dridder123** [comment]
And where did you get the iso from without give the rom site was it cool Mania Hustler free emulator or romulation

**Comment by dridder123** [comment]
It very well could be the ISO

**Comment by pathartl** [comment]
No talking on where to download copyrighted assets.

**Comment by dridder123** [comment]
My bad sorry

**Comment by AnotherLife** [comment]
https://docs.libretro.com/library/pcsx_rearmed/

Put the BIOS files in the system folder with those exact names, case-sensitive.

**Comment by C0llab0rat10n** [comment]
Test the medal of honor game in ePSXe emulator for PC. If it fails then it's the game. Also, make sure the game is in the proper format, .bin or eboot format. I've had issues where if the Eboot is compressed to much the game wont start, you'd have to re-compress it with a smaller compression rate.

**Comment by OldWitch666** [comment]
Thanks for all answers. I Found a solution and used different program to convert iso to bin.
