### ISSUE TITLE
Option - Add jpeg or png as filters for scanlines

### ISSUE THREAD

**Issue by C0llab0rat10n** [pathartl/BleemSync#347]
I know bleemsync has a scanlines feature but it does not display properly on and LCD or flat screen as the scanlines are squished. Well, Mame had the same problem but I fixed it with a properly made scanline bit map. I'd like to have the same kind of feature added to Bleemsync. I've attached images of my LCD monitor with scanlines and as you can see it looks pretty good. I colored the scanlines a very light gray and you can see they all appear equally spaced out.

![img_20190221_001928](https://user-images.githubusercontent.com/47843891/53148110-3e0a1180-356f-11e9-9833-4557337ac556.jpg)

![2](https://user-images.githubusercontent.com/47843891/53148187-87f2f780-356f-11e9-98c1-ead9f3f1aaa8.png)

**Comment by swingflip** [comment]
We added an overlay pack along side the bleemsync download link so this should cover what you need
