### ISSUE TITLE
Auto-generatate Game.ini files

### ISSUE THREAD

**Issue by pathartl** [pathartl/BleemSync#35]

**Comment by pathartl** [comment]
[Parsing PBP's seems straight forward](http://www.psdevwiki.com/ps3/Eboot.PBP), but BIN's and ISO's are a bit different. Parsing out the serial number for discs would be crucial for this.

**Comment by alucard73** [comment]
I do not know much but why not use the same system as psx2psp?

**Comment by pathartl** [comment]
As far as I know the PSX2PSP source has not been released.

**Comment by filmcriticbeta** [comment]
If you can dump the directory structure from the image this becomes trivial - the games main executable file was required to use the GameID as its filename. The bios then used the system.cnf text file ( which in turn was located on the disk root ) to determine its location/parameters/etc.

Anyways does the linux isoinfo utility support bin/cue as well?  You can use that with the -f flag to dump the directory structure. The code for that is also open source.

IIRC the one exception to this was Tekken 3 Pal - I recall having to hard code some terrible hack into my ePSXe frontend to get it to correctly pass on the appropriate emulation settings.  However this was around 15 years ago, so I can't remember the details - sorry.

**Comment by fritztoch** [comment]
Would we add a file to this distribution listing every release's metadata, and then populate Game.ini from it when the disc ID is matched? Alternatively, is there an online source for this metadata that would let us mine it?

**Comment by mtrivs** [comment]
> Would we add a file to this distribution listing every release's metadata, and then populate Game.ini from it when the disc ID is matched? Alternatively, is there an online source for this metadata that would let us mine it?

My own thought on how this would be implemented, would be to have an array populated with the release data contained [here](http://redump.org/discs/system/psx/) or [here](https://psxdatacenter.com/) for every possible release.   I don't own either of these sites, so I don't know if they would help you in obtaining a data dump, but the data does exist.  Then each game would need to be evaluated to determine the game name/serial number, seemingly the way @filmcriticbeta mentioned, where all the data could be correlated into the game.ini file.    Likely not the most elegant solution, as you may find that different regions use the same title for the game, but have a different serial number (i.e. Asteroids (US) = SLUS-00773; Asteroids (FR) = SLES-01468; Asteroids (DE) = SLES-01469).  

An alternative solution to this issue, might be to make the user responsible for renaming the file to match (exactly) the serial number or game title against one of the two databases linked above.   From there, each title could be evaluated based on the filename, rather than having to dive into each file to extract the serial number.

**Comment by fritztoch** [comment]
I checked http://psxdatacenter.com, I don't see any links about some sort of API to search against the database programmatically. I personally favour http://psxdatacenter.com but as they are asking for financial contributions, they may not welcome us scraping their site for data. The list of PSX titles is static: there will (likely) never be another new release (although every site I looked at says their lists aren't *yet* complete), and a text file containing all the titles' metadata shouldn't be too big. I think we should contact these site owners for permission to do a single export of the data they've collected and store that in a file for inclusion in this package, to minimize traffic/server load for them. If their data gets revised periodically, we could approach them for an update periodically.
As far as parsing the BIN for the disc ID: I looked at a couple and they don't seem to keep it in the same place in different discs. Renaming the CUE to match the disc ID sounds like a simpler idea.

**Comment by mtrivs** [comment]
I did some more research and it looks like there are a few other sites that would provide an API that could be used to build a scraper: [https://api.igdb.com/](https://api.igdb.com/). This site does offer an API for free, but it is limited to 3,000 requests monthly.   It may be possible for multiple users to query the DB using the API to divide and conquer, until we have a finalized data dump.


https://github.com/sselph/scraper - Scraper designed for RetroPie, that will hash .bin/.cue files and scrape metadata from theGamesDB.net to output a gamelist.xml.   The gamelist.xml can then be parsed to match up the metadata and build the .ini file

**Comment by fritztoch** [comment]
> It almost sounds like you would want a "Custom Game" button, where a user can specify all the metadata, add additional disks, etc. to build the game.ini file in a guided manner through the gui.<

This is something that could be implemented first, IMO. We could add the database later, but a front end for manually building the game.ini would still be easier than the current. Add a gadget to Google Image search for the cover.

**Comment by pathartl** [comment]
I wrote a util that opens up a filestream and reads through the disc image and extracts the disc serial number out. It's pretty quick, uses ~1MB of RAM, and runs in all well under 50ms.

**Comment by mtrivs** [comment]
> I wrote a util that opens up a filestream and reads through the disc image and extracts the disc serial number out. It's pretty quick, uses ~1MB of RAM, and runs in all well under 50ms.

HEY NOW!  That sounds much faster than I had anticipated.   Thank you for the update and for all of your hard work to make this a reality.

**Comment by filmcriticbeta** [comment]
Ah. Performing a string extraction on the bin file will pull the boot parameter line out the system.cnf file without the need to understand the underlying file structure, and the boot parmeter contains the GameID in its path. My hat is off to you good sir, that was genius.

**Comment by pathartl** [comment]
It needs to be cleaned up, but the database API is created as a .NET Web API project. I've deployed it to a temporary DigitalOcean droplet. A client has been written into BleemSync (albeit quickly) and game info will now pull from the 'net based on the serial number extracted from the bin/iso.

Some bug fixes need to be done before this can be considered for release. Namely multiple discs aren't being handled properly.

**Comment by pathartl** [comment]
Added with 0.4.0.
