### ISSUE TITLE
ui editing problems after 1.0.1

### ISSUE THREAD

**Issue by ennahh76** [pathartl/BleemSync#353]
unable to edit/delete some titles via the UI after 1.0.1 as the options/cover on the right hand side do not appear

**Comment by TheGreenGoblin** [comment]
At least you can still connect your PSC to the computer. Suddenly, I'm not even getting the light when I connect mine. Fortunately, I discovered this:
https://github.com/pascl/pbPSCReAlpha

**Comment by swingflip** [comment]
@ennahh76 you are using internet explorer or some old edge. Use chrome or firefox

**Comment by swingflip** [comment]
@TheGreenGoblin that sounds like user error. I worked on the payload myself and if it’s installed correctly and you use a usb cable with data this isn’t an issue. 

What did you do? Did you install the payload? Did you swap usb cable? Did you try another port?

**Comment by TheGreenGoblin** [comment]
@swingflip I tried ALL of that and more. I tried connecting my SNES Classic and when I switched it on, IT WORKED. So whatever the problem is, it appears that it is NOT "user error."

**Comment by ennahh76** [comment]
@swingflip I was using chrome. I am in the process of re-installing everything to a new hard drive now and it’s doing the same.  I thought it might be just on Japanese titles but I think it might of happened on a u.s.  I will have to double check when I get home.

**Comment by ennahh76** [comment]
@swingflip checked it, using the most up to date version of chrome.  installed firefox and it does the same thing.  it does seem however to only be japanese games that go missing.

**Comment by ennahh76** [comment]
it looks like its japanese games that are not in the database i.e. the ones where you have to insert your own cover art/name/release details as the few japanese games that are, do appear.

**Comment by ennahh76** [comment]
Just installed a u.s. version of a game that’s not on the database and sure enough, I can’t re-access it to change any details.

**Comment by swingflip** [comment]
> @swingflip I tried ALL of that and more. I tried connecting my SNES Classic and when I switched it on, IT WORKED. So whatever the problem is, it appears that it is NOT "user error."

@TheGreenGoblin, if that is the case then you have just confirmed that the USB cable you are using has datalines as well as power lines. When you plugged in the PSC did it not have any LED then flicker RED for a second and have no LED? If so you haven't installed the payload to the console.

If you got no LED and NO RED LED for a split second then I would suggest trying a different PC/Laptop USB as we have had pc/laptops that outright refuse to send enough power to the PSC for it to even start up.

**Comment by pathartl** [comment]
Can you pop open the dev tools of Chrome (F12), click on a game, and then paste the error that's thrown in the bottom or in the console?

**Comment by TheGreenGoblin** [comment]
@swingflip YES I DID install the payload onto the console!!!! It used to connect fine but suddenly stopped. Everything else involving the payload works fine. Apparently the file on the console that allows PC connectivity got corrupted, and I tried reinstalling it.

**Comment by ennahh76** [comment]
@ pathartl who is that too please?

**Comment by swingflip** [comment]
@TheGreenGoblin technically not possible as the files written to the console are protected as they are mounted read only after installation...

Can you explain the LEDs and what the LEDs did

**Comment by ennahh76** [comment]
@pathartl is this what youre looking for?

game-manager.js:143 Uncaught TypeError: Cannot read property 'split' of null
    at GameManager.EditGame (game-manager.js:143)
    at Object.success (game-manager.js:137)
    at u (jquery-3.3.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.min.js:2)
    at k (jquery-3.3.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.min.js:2)
EditGame @ game-manager.js:143
(anonymous) @ game-manager.js:137
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
k @ jquery-3.3.1.min.js:2
(anonymous) @ jquery-3.3.1.min.js:2
load (async)
send @ jquery-3.3.1.min.js:2
ajax @ jquery-3.3.1.min.js:2
w.(anonymous function) @ jquery-3.3.1.min.js:2
getJSON @ jquery-3.3.1.min.js:2
LoadEditGameForm @ game-manager.js:137
TreeOnSelectNode @ game-manager.js:124
(anonymous) @ game-manager.js:109
dispatch @ jquery-3.3.1.min.js:2
y.handle @ jquery-3.3.1.min.js:2
trigger @ jquery-3.3.1.min.js:2
triggerHandler @ jquery-3.3.1.min.js:2
trigger @ jstree.min.js:2
select_node @ jstree.min.js:3
activate_node @ jstree.min.js:3
(anonymous) @ jstree.min.js:2
i @ jquery-3.3.1.min.js:2
dispatch @ jquery-3.3.1.min.js:2
y.handle @ jquery-3.3.1.min.js:2

**Comment by TheGreenGoblin** [comment]
@swingflip I thought I made it quite clear that the LED does NOTHING. And don't be so dismissive of the FACT that the files written to the console can get corrupted.

**Comment by swingflip** [comment]
@TheGreenGoblin I don't appreciate your aggesive attitude especially whilst being offtopic to the current issue. I was trying to assertain your complete situation and you are just giving back grief.

If the LED is doing "NOTHING" as you kindly put it and doesn't either:
1. Show the RED for a split second and go off
2. Display orange.

This means your console is not being powered correctly. Nothing to do with the payload because even if the payload was corrupt the LED would respond in one shape or form and it's impossible to not do so.

I would suggest not throwing the "FACT" word around if you don't fully understand how the architecture works or how the software operates.

**Comment by TheGreenGoblin** [comment]
@swingflip  Sorry if I sounded so gruff, but I don't take kindly to being wrongly accused. Power should not be an issue because:
1: The PC connectivity WAS working, but inexplicably stopped.
2: The console is connected to the PC through a powered USB hub.

**Comment by GMMan** [comment]
@TheGreenGoblin @swingflip Could you separate out the discussion to a different issue so it's not overtaking the original issue? I suggest going to the Discord instead. Thanks.

**Comment by GMMan** [comment]
@ennahh76 Could you lay out the reproduction steps?

**Comment by ennahh76** [comment]
@GMMan it’s just transferring the game to the classic via bleemsyncui.com.

1. select your bin/cue files,

2.  if you don’t get artwork/description in the top right right, you would click and drag artwork and manually enter in the details and then transfer to the classic.

 3. Once transfer done, click on the game from your games list.

If the artwork/details appear when you select your bin/cue, that stuff will reappear in the top right so you can change the artwork and edit the details or delete the game.

If you have to manually enter Artwork/details after selecting bin/cue, once you have transferred it to the classic and select it on your games list, nothing appears in the top right so you cannot edit anything or delete the game.

I have found this normally happens for Japanese games.  Like for instance castlevania was fine as the details appeared when initially selecting bin/cue files so I can edit them over and over or delete.  However, none of the biohazard games have details appear so once transferred, you cannot do anything with it, and your stuck with it on your memory stick/hdd.

Hope this didn’t go on too long.

**Comment by GMMan** [comment]
@ennahh76 Thanks, that's very helpful.

**Comment by glebtv** [comment]
This is related: #376 
Also #377
