### ISSUE TITLE
Suggestions: Be able to add games by copying them to USB stick and Bleemsync recognizes them.

### ISSUE THREAD

**Issue by CommodoreOS** [pathartl/BleemSync#354]
Be able to add a game to the games folder and when switching on the PSC with the USB Stick in,Bleemsync recognizes the game and adds it automatically.

**Comment by GMMan** [comment]
We're not entertaining this option because the next release will move the app back to the desktop and have bulk load capabilities. Dynamic game detection adds too much overhead in upkeeping of the database.
