### ISSUE TITLE
8bitdo and controls not working after 1.0.1

### ISSUE THREAD

**Issue by jesparchaos** [pathartl/BleemSync#355]
I updated to 1.0.1.When I plug a controller into the USB, it wont reguister me selecting a game. Whn i try to use the 8BitDo, it says cant recognize the controller.

**Comment by ennahh76** [comment]
sorry if this sounds like a daft question.  are you using a 8bitdo controller or the dongle for any controller.  i had a similar thing with the dongle, so updated/reinstalled the firmware (even though it was the same one) and it now works again.

**Comment by jesparchaos** [comment]
- The 8bitdo doesn't work at all with any controller period now. 
- When I plug in the DS4 via a USB cord, I can only move things. The face buttons do not seem to work anymore. 
- If I use the original PSC Controller, it works properly. 

I did a fresh install of 1.0.1 also and the problem is still happening.

**Comment by ennahh76** [comment]
I don’t know if this is what you mean, but I plugged the dongle in to the pc and downloaded the dongles firmware and upgraded that. Latest is version 2.2.  Does the light on the ds4 come up blue or green?  If it’s green, definitely do the dongles firmware.  After I upgraded to 1.0.1 I had issues as well and all I did was redo the dongle and even though I was already using firmware 2.2 it sorted it and controllers light is blue again. USB cable never worked for me either.

**Comment by swingflip** [comment]
you need to update your firmware of your 8bitdo device. People have been able to use the 8bitdo and DS4 with 1.0.1 100% perfectly and I think someone even posted in the /r/playstationclassic subreddit regarding it too.

**Comment by andshrew** [comment]
You need to make sure the dongle is in PlayStation Classic mode by holding SELECT (SHARE) + DOWN for 3 seconds.

**Comment by jesparchaos** [comment]
@andshrew  I realized this last night. It turned out my 8bitdo was in the wrong mode (which I didnt even know you could do. I must have pressed one of these combos by accident), 

As for the other issues. I resinstalled bleemsync 3 times, and on the 3rd time it seemed to work. So I must have botched the first 2 installs somehow. Thanks for the help with this.
