### ISSUE TITLE
Make the Reset button quit from the carousel back to the boot menu

### ISSUE THREAD

**Issue by AnotherLife** [pathartl/BleemSync#357]
I just saw Swingflip is working on a Retroarch launcher from the carousel but some people may not want a retroarch entry between their games. Or maybe they have hundreds of games.

So is it possible to make the Reset button quit back to the boot menu?

**Comment by swingflip** [comment]
This won't be done as it would be a nightmare to implement and the launchers will be configurable within the configuration so I will close this for now if thats ok.
