### ISSUE TITLE
Generate CUE files if they don't exist

### ISSUE THREAD

**Issue by pathartl** [pathartl/BleemSync#36]

**Comment by fritztoch** [comment]
Something like this? https://github.com/thorst/CueMaker

**Comment by mtrivs** [comment]
This GitHub page also exists: https://github.com/opsxcq/psx-cue-sbi-collection 

There is a small shell script for generating .cue files, along with a collection of .cue files for most games

**Comment by mtrivs** [comment]
On a side note, it might make more sense to leave the .CUE file generation up to the user.   If we have a list box that displays all of the titles, we could highlight the row "Red" to let the user know that that file needs attention before it can be processed.   The user could then correct those issues by either specifying their own CUE file or having Bleem create one for them.   There are some games that use CDDA audio tracks, where each track is a separate .bin file.   This means you will have at least two .bin files – one .bin for the game’s executable and one or more .bin file for each CDDA audio track.   A good example of this is the PAL version of Tomb Raider which has; “Tomb Raider (Europe) (Track 01).bin”, “Tomb Raider (Europe) (Track 02).bin”, “Tomb Raider (Europe) (Track 03).bin” …all the way up to; “Tomb Raider (Europe) (Track 57).bin”.   In this instance, it might get very tricky having an automated solution that would fit all use cases. 

Here is what the correct .cue sheet looks like for Tomb Raider (Europe) (PAL): 
```
FILE "Tomb Raider (E) (Track 01) [SLES-00024].bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
FILE "Tomb Raider (E) (Track 02) [SLES-00024].bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Tomb Raider (E) (Track 03) [SLES-00024].bin" BINARY
  TRACK 03 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Tomb Raider (E) (Track 04) [SLES-00024].bin" BINARY
  TRACK 04 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
```
