### ISSUE TITLE
Double Joy retro wireless controllers USB Hub

### ISSUE THREAD

**Issue by roydestroy** [pathartl/BleemSync#360]
I have 2 joyretro wireless controllers. Do you think there is a way we could have them both working with a USB hub through Bleemsync? When I plug them both on the hub they start blinking and connecting from one controller to the other and PSclassic does not recognize and controller.

**Comment by OldWitch666** [comment]
I dont think so. I tried to plug in first port Trust Yula gamepad. D pad worked fine, same with analogs, but any action button (x, o, etc.) does not work.

**Comment by roydestroy** [comment]
When I plug in only one of them on the hub it works fine. Also if I use the psclassic original pad as a second controller on the hub both of them work fine. The problem only starts when I connect both the wireless pads on the hub. If that helps at all
