### ISSUE TITLE
Playstation Classic does not boot up.

### ISSUE THREAD

**Issue by Ninjahahn** [pathartl/BleemSync#361]
![img_5822](https://user-images.githubusercontent.com/48196387/53711188-25ff8100-3dfe-11e9-877f-3e33a74d4c0f.JPG)

**Comment by Ninjahahn** [comment]
I was able to use BleemSync, for about a week and then i got this message when i booted up my playstation classic.

**Comment by LifesFailure** [comment]
Have you unplugged the power and USB and attempted to boot without the USB stick plugged in?

-Unplug PSC power
-unplug USB
---Wait 10 seconds or so
-Plug back in power
-After orange light shows up, boot the PSC (without the USB drive plugged in)

**Comment by andshrew** [comment]
This error usually means that the system was turned off while a game above ID 20 was selected, and for some reason the procedure which runs during shutdown to reset this back to 1 did not run, so when the stock system boots up it is trying to select a game ID which does not exist.

You can either:

* Start the console with your BleemSync USB inserted and launch BleemSync. On the main menu game ID 1 should be selected by default. Turn the system off by pressing the power button and wait until the LED goes off to remove the USB drive. Then boot the system without the USB drive and it should work as normal.
* Put the uninstaller image on another USB drive and let it uninstall. This process resets the selected game back to 1. Once uninstalled confirm the stock system is working as expected, and then insert your original USB drive to re-install BleemSync. You loaded games should all remain intact as long as you don't modify the USB drive in anyway.

**Comment by Ninjahahn** [comment]
LifesFailure, I have tired that but still get same message.. 

andshrew, I only have one thumb drive, where could I get uninstaller? I still have the files for Bleemsync in my laptop with the games I have unzipped..

**Comment by andshrew** [comment]
Try what I suggested in the first step, but if that doesn't work the uninstaller is on the main web page https://modmyclassic.com/bleemsync/ - scroll down to **How to uninstall bleemsync 1.0**. (the uninstaller is the same for 1.0 and 1.0.1)
