### ISSUE TITLE
Bllemsync not installing

### ISSUE THREAD

**Issue by drkPASSENG3R** [pathartl/BleemSync#367]
I've formatted the USB drive to FAT32, titled SONY. I move the contents from the zip over to the drive, install the stick, controller, hdmi then power cable. Once the amber light turns on, I hit the power button. At this point, I do not get the bleem screen I'm reading about, just a quick white flash on the screen, then the system shuts down, back to amber light. Am I missing a step?

**Comment by LifesFailure** [comment]
Did you make sure to extract BleemSync.zip before moving files to the USB drive? Is your USB drive 2.0 or 3.0?

**Comment by drkPASSENG3R** [comment]
Yes, it’s 2.0 and I only placed the 2 folders that were inside the zip: I just checked the drive and it now has a Logo folder, but also says it can access as it’s corrupt. Maybe some issue with install so I’m going to format and try again

**Comment by guy30000** [comment]
I cant get it to work either. I've tried 6 USB drives. All with fat32, Ive tried in port 1 and 2 as I saw someone say they got it to work in port 1. It's just booting normally. Making me wonder if there has been a revision locking this procedure out.

**Comment by drkPASSENG3R** [comment]
Mine worked smoothly after I purchased a new usb drive. Here is a link to the drive that worked for me.


https://www.amazon.com/SanDisk-32GB-Ultra-Flash-Drive/dp/B077VXV323/ref=mp_s_a_1_4?keywords=sandisk+sd+drive&qid=1558126724&s=gateway&sr=8-4

**Comment by wavapps** [comment]
drkPASSENG3R That sounds like you need to do a CHKDSK in windows. I have had that same prob. Plus the power issue. Did you do the power mod or using a powered usb hub?
