### ISSUE TITLE
Add menu entry for extracting stock games

### ISSUE THREAD

**Issue by pathartl** [pathartl/BleemSync#37]

**Comment by swingflip** [comment]
This will be aimed for 1.1 release when the payload has the ability to inject the recovery method to the recovery partition on the console.

**Comment by Wh1terat** [comment]
Out of interest - why does the recovery partition play a role in this?

On-box gaadata is decrypted and available as a volume in device-mapper and can be remounted to any arbitrary mount point for copying or even just dd from devicemapper as block device would result in the decrypted ext4 image.

and off-box with the encrypted partition is trival enough to mount:  
```bash
losetup /dev/loop0 mmcblk0p9.img
echo 0 29360127 crypt aes-xts-plain e44f1fd8a0d566e3f89dd4d795b1a3f010a36dcbe1033d1de554246ea313077f 0 /dev/loop0 1 | dmsetup create gaadata
mount /dev/mapper/gaadata /mnt/gaadata
```

**Comment by GMMan** [comment]
Can we clarify what extracting means here?
