### ISSUE TITLE
Expendable not working...?  No matter which ROM I try...?

### ISSUE THREAD

**Issue by abelogan** [pathartl/BleemSync#371]
I'm trying to get the game "Expendable" to play on Bleemsync, but no matter which ROM I use (I've downloaded all the ones I could find), the game seems to start normally, but as soon as I start moving my character, the game goes all glitchy and quickly becomes an incomprehensible mess, like someone threw up all over the TV screen lol.  Anyone else having problems with this game, or does anybody know how to fix this?

Thanks!

**Comment by andshrew** [comment]
As this is an emulation issue, you would have more chance of this being fixed if you raise the issue against the pcsx_rearmed project: https://github.com/libretro/pcsx_rearmed/issues
