### ISSUE TITLE
Adding a game which does not exist BleemSync DB shows up empty info for Manage game screen

### ISSUE THREAD

**Issue by tamo4** [pathartl/BleemSync#378]
When add a Japanese version game using BleemSync UI, the right side pane shows up empty since it does not have any date BleemSync Server side. 
Thus, user cannot delete the game or edit the game.

**Comment by TheGreenGoblin** [comment]
It might look empty, the the game files are still selected. You can enter all that data manually, like this:
![Mortal Kombat 2 BS101](https://user-images.githubusercontent.com/46424152/56030813-cd1fe400-5ceb-11e9-816a-dc9347903605.png)

**Comment by tamo4** [comment]
Panel itself does not show up.
![ManageGame1](https://user-images.githubusercontent.com/49542218/56052090-6f989100-5d05-11e9-9099-b7c6e16cdb88.jpg)
![ManageGame2](https://user-images.githubusercontent.com/49542218/56052091-70312780-5d05-11e9-9ff9-f1936b7b0fb0.jpg)

**Comment by TheGreenGoblin** [comment]
@tamo4 I haven't encountered that. Definitely something going wrong here. If you are using Windows, you may want to consider this more functional alternative:
https://github.com/pascl/pbPSCReAlpha
