### ISSUE TITLE
Will I void Warranty and lose Stock OS?

### ISSUE THREAD

**Issue by xpresservers** [pathartl/BleemSync#379]
I am trying to figure out if I use BleemSync on my PS Classic then will I lose access to stock system and void the warranty? Any harm on PS Classic with Bleemsync?

**Comment by TheGreenGoblin** [comment]
Will you lose access to the "stock system?" No.
Will you void the warranty? Technically, yes.
Bleemsync is basically safe, but as a wise man once said, "anthyding can hadplen."
