### ISSUE TITLE
Update github repo for bleemsync 1.1?

### ISSUE THREAD

**Issue by PinkFreud** [pathartl/BleemSync#384]
When will this repo be updated for the recent bleemsync 1.1 release?

**Comment by TheGreenGoblin** [comment]
Most likely, never. The GitHub page has pretty much been abandoned. Go to https://modmyclassic.com/bleemsync/ for updates.

**Comment by PinkFreud** [comment]
Is it no longer open source as of 1.1?

**Comment by Cabalist** [comment]
This seems to say it is GPLv3 https://modmyclassic.com/license-agreements/   I don't know where development is happening though...   I'd love to look at the source

**Comment by pathartl** [comment]
The project has been passed off to the ModMyClassic team. They have control over this repository. As I understand they've been working to move over to another system. I would follow up with them for more info. I know they've been working to get the source out there, but the reorganization has thrown a couple wrenches in it.
