### ISSUE TITLE
Bleemsync not installing

### ISSUE THREAD

**Issue by coryschmitz** [pathartl/BleemSync#396]
Hello,

I formatted my USB drive (SanDisk Ultra Flair 16GB, USB 3.0) to MS-DOS (FAT32) & named it "SONY". I put "bleemsync" & "d8781dae-c45c-4fc1-b961-e03eedebbffb" folders in the root of SONY. I unplugged everything from PSC, plugged in the USB stick into the second controller port, plugged it in, waited for orange light, powered on, but then it just boots normally to the PSC UI. No Bleemsync in sight.

Notes:
• This is a refurbished/returned PSC from Amazon.
• I am using a Mac (10.14.5), don't have a PC.

Any help would be greatly appreciated.

Thanks!!

**Comment by diouf** [comment]
samething here, it just goes to the official UI.

Bought brand new from Amazon.

is it possible they did a fixed for newer devices?

**Comment by pinknickel** [comment]
I'm having the same issue! If the newer devices have been fixed, I'm taking the system back to the guy at GameStop who sold it to me promising we could download games.

**Comment by kickasskc** [comment]
Possible issues may be your usb drive compatability(might have better luck on the initial install eith smaller usb 2.0 drives), or altered system files from the refurbished psc's previous owner(maybe you can restore the console with a backup found online?).
I do not believe macs will alter file structure of external storage devices compared to windows, but tbh, if you plan on tinkering with and modding things in the future, get a pc.
