### ISSUE TITLE
Bleemsync 1.1 power off switching game

### ISSUE THREAD

**Issue by nite138** [pathartl/BleemSync#397]
Everything loads/plays fine, except when you hit the reset button on the console to change a game.  It goes back to the menu, but freezes and then shuts off.

I've resized all of the png to 226x226 and compressed 

I'm running OTG w/2tb external hdd

**Comment by kickasskc** [comment]
I think i read that the psc menu is limited to like 100mb of cache/ram so having all those images shrunk and compressed as they are, takes up too much memory to allow the interface to create a save state. I think the best hope is better folder support allowing users to minimize the amount of games in the carousel at once.
