### ISSUE TITLE
Consistency and memory issues

### ISSUE THREAD

**Issue by ItsSmokieFTW** [pathartl/BleemSync#40]
So im not exactly sure whats happening with my USB but when i first load the files onto it everything shows up and looks good but after i start Final Fantasy 8 up it all works good and the minute i save the game i have to make 2 save files because one of them always becomes corrupt and damaged and when i hit the reset button to go back to the screen all the games disappear from the hub. I have to reload the files onto the USB to get my games back but after i do one of my saves are corrupt. I also get crashes when i even try to use the emulator settings at all. Its very inconsistent in general. Im not even sure where to start with the pile of problems im coming across. I want to help you guys so anything you need tell me i could do what i normally do and upload my files from what i get once it crashes because i can tell theres errors im just not sure why. Also im using a mixture of 0.3.0 and 0.3.1 because for some reason 0.3.1 by itself basically makes my playstation classic not even know the usb is plugged in but all the other releases worked in terms of my playstation classic recognizing it.

**Comment by fritztoch** [comment]
0.3.1 has worked flawlessly for me so far. Have you tried a different USB?

**Comment by FreudienSlip** [comment]
Samsung BAR Plus 32GB - 200MB/s USB 3.1 Flash Drive Titan Gray (MUF-32BE4/AM)
on amazon has worked so far for all releases
under 9 dollars
its even a usb 3.1
