### ISSUE TITLE
i have SAGA game that isnt seen 

### ISSUE THREAD

**Issue by maty87** [pathartl/BleemSync#404]
i have a saga game that isnt seen by the retroboot but the file is there

**Comment by TarkinMX** [comment]
This isn't the place to ask about retroboot, the devs here aren't responsible for that. Go to [https://github.com/autobleem/AutoBleem/issues](url) to ask your question. You can also try reddit, [https://www.reddit.com/r/PlaystationClassic/comments/e25ae9/release_retroboot_010_standalone_and_retroboot/](url)
