### ISSUE TITLE
I have met a problem while installing

### ISSUE THREAD

**Issue by jiangjinxiang** [pathartl/BleemSync#406]
Dear Sir/Madam,
  I tried to install version 1.2 for my PSC, but I have met a trouble about step 11 to upgrade the ' custom kernel'. During this step, my PSC turned on the LED green with 5 times flicker, and then kept on LED red flicker. I do not know what is wrong on it while installing. Please help, thanks!

**Comment by pathartl** [comment]
This project is no longer associated with BleemSync v1.1 and higher. Please visit https://modmyclassic.com for future support.
