### ISSUE TITLE
Stock games dont start after putting a comma in game.ini

### ISSUE THREAD

**Issue by appletacos** [pathartl/BleemSync#46]
I can see the stock games, but it doesnt do anything when i select it. i think it happwned after i accidenrly put a comma in a game.ini file title name. ive rerun bleemsync afterwards but no games play after they are selected.

**Comment by pathartl** [comment]
To use commas in any of the string fields in Game.ini, you must wrap it in double quotes. E.g.
```
[Game]
DiscIds=SLUS-00860
Title="Title with, a comma"
...
```
