### ISSUE TITLE
0.3.2 release Linux version has backslashes instead of forward slashes, ruining folder structure.

### ISSUE THREAD

**Issue by UltimaN3rd** [pathartl/BleemSync#47]
When extracted you get files like "Games\2\GameData\SLUS-01066.png" as a single named file, rather than "SLUS-01066.png" being with a Games/2/GameData/ folder.

**Comment by pathartl** [comment]
I added a new build script with 0.3.2. Can you try the release again? https://github.com/pathartl/BleemSync/releases/tag/0.3.2

**Comment by UltimaN3rd** [comment]
Downloaded it again and when extracted from the archive it's still full of all those improperly named files.

**Comment by pathartl** [comment]
Sorry, one more try
https://github.com/pathartl/BleemSync/releases/download/0.3.2/BleemSync-0.3.2-linux-x64.zip

Built in Windows ZIP compression does it's Windows thing.

**Comment by UltimaN3rd** [comment]
That seems to have done the trick! Cheers mate
