### ISSUE TITLE
Release 0.3.2: macOS version folder structure missing

### ISSUE THREAD

**Issue by fritztoch** [pathartl/BleemSync#48]
Downloaded BleemSync-0.3.2-osx-x64.zip. After extraction, every file is in one folder, with the filenames containing the path. Directory listing:

> FritzBookPro:BleemSync-0 birddog$ ls
\028c18a9-ec4b-4632-b2cf-d4e20f252e8f\LUPDATA.BIN
BleemSync\BleemSync
BleemSync\BleemSync.Data.dll
BleemSync\BleemSync.Data.pdb
BleemSync\BleemSync.Services.dll
BleemSync\BleemSync.Services.pdb
BleemSync\BleemSync.Utilities.dll
BleemSync\BleemSync.Utilities.pdb
BleemSync\BleemSync.deps.json
BleemSync\BleemSync.dll
BleemSync\BleemSync.pdb
BleemSync\BleemSync.runtimeconfig.json
BleemSync\Castle.Core.dll
BleemSync\Microsoft.CSharp.dll
BleemSync\Microsoft.Data.Sqlite.dll
BleemSync\Microsoft.DotNet.PlatformAbstractions.dll
BleemSync\Microsoft.EntityFrameworkCore.Abstractions.dll
BleemSync\Microsoft.EntityFrameworkCore.Proxies.dll
BleemSync\Microsoft.EntityFrameworkCore.Relational.dll
BleemSync\Microsoft.EntityFrameworkCore.Sqlite.dll
BleemSync\Microsoft.EntityFrameworkCore.dll
BleemSync\Microsoft.Extensions.Caching.Abstractions.dll
BleemSync\Microsoft.Extensions.Caching.Memory.dll
BleemSync\Microsoft.Extensions.Configuration.Abstractions.dll
BleemSync\Microsoft.Extensions.Configuration.Binder.dll
BleemSync\Microsoft.Extensions.Configuration.dll
BleemSync\Microsoft.Extensions.DependencyInjection.Abstractions.dll
BleemSync\Microsoft.Extensions.DependencyInjection.dll
BleemSync\Microsoft.Extensions.DependencyModel.dll
BleemSync\Microsoft.Extensions.Logging.Abstractions.dll
BleemSync\Microsoft.Extensions.Logging.dll
BleemSync\Microsoft.Extensions.Options.dll
BleemSync\Microsoft.Extensions.Primitives.dll
BleemSync\Microsoft.VisualBasic.dll
BleemSync\Microsoft.Win32.Primitives.dll
BleemSync\Microsoft.Win32.Registry.dll
BleemSync\Newtonsoft.Json.dll
BleemSync\Remotion.Linq.dll
BleemSync\SOS.NETCore.dll
BleemSync\SQLitePCLRaw.batteries_green.dll
BleemSync\SQLitePCLRaw.batteries_v2.dll
BleemSync\SQLitePCLRaw.core.dll
BleemSync\SQLitePCLRaw.provider.e_sqlite3.dll
BleemSync\SharpConfig.dll
BleemSync\SharpINI.dll
BleemSync\System.AppContext.dll
BleemSync\System.Buffers.dll
BleemSync\System.Collections.Concurrent.dll
BleemSync\System.Collections.Immutable.dll
BleemSync\System.Collections.NonGeneric.dll
BleemSync\System.Collections.Specialized.dll
BleemSync\System.Collections.dll
BleemSync\System.ComponentModel.Annotations.dll
BleemSync\System.ComponentModel.DataAnnotations.dll
BleemSync\System.ComponentModel.EventBasedAsync.dll
BleemSync\System.ComponentModel.Primitives.dll
BleemSync\System.ComponentModel.TypeConverter.dll
BleemSync\System.ComponentModel.dll
BleemSync\System.Configuration.dll
BleemSync\System.Console.dll
BleemSync\System.Core.dll
BleemSync\System.Data.Common.dll
BleemSync\System.Data.dll
BleemSync\System.Diagnostics.Contracts.dll
BleemSync\System.Diagnostics.Debug.dll
BleemSync\System.Diagnostics.DiagnosticSource.dll
BleemSync\System.Diagnostics.FileVersionInfo.dll
BleemSync\System.Diagnostics.Process.dll
BleemSync\System.Diagnostics.StackTrace.dll
BleemSync\System.Diagnostics.TextWriterTraceListener.dll
BleemSync\System.Diagnostics.Tools.dll
BleemSync\System.Diagnostics.TraceSource.dll
BleemSync\System.Diagnostics.Tracing.dll
BleemSync\System.Drawing.Primitives.dll
BleemSync\System.Drawing.dll
BleemSync\System.Dynamic.Runtime.dll
BleemSync\System.Globalization.Calendars.dll
BleemSync\System.Globalization.Extensions.dll
BleemSync\System.Globalization.Native.dylib
BleemSync\System.Globalization.dll
BleemSync\System.IO.Compression.Brotli.dll
BleemSync\System.IO.Compression.FileSystem.dll
BleemSync\System.IO.Compression.Native.a
BleemSync\System.IO.Compression.Native.dylib
BleemSync\System.IO.Compression.ZipFile.dll
BleemSync\System.IO.Compression.dll
BleemSync\System.IO.FileSystem.AccessControl.dll
BleemSync\System.IO.FileSystem.DriveInfo.dll
BleemSync\System.IO.FileSystem.Primitives.dll
BleemSync\System.IO.FileSystem.Watcher.dll
BleemSync\System.IO.FileSystem.dll
BleemSync\System.IO.IsolatedStorage.dll
BleemSync\System.IO.MemoryMappedFiles.dll
BleemSync\System.IO.Pipes.AccessControl.dll
BleemSync\System.IO.Pipes.dll
BleemSync\System.IO.UnmanagedMemoryStream.dll
BleemSync\System.IO.dll
BleemSync\System.Interactive.Async.dll
BleemSync\System.Linq.Expressions.dll
BleemSync\System.Linq.Parallel.dll
BleemSync\System.Linq.Queryable.dll
BleemSync\System.Linq.dll
BleemSync\System.Memory.dll
BleemSync\System.Native.a
BleemSync\System.Native.dylib
BleemSync\System.Net.Http.Native.a
BleemSync\System.Net.Http.Native.dylib
BleemSync\System.Net.Http.dll
BleemSync\System.Net.HttpListener.dll
BleemSync\System.Net.Mail.dll
BleemSync\System.Net.NameResolution.dll
BleemSync\System.Net.NetworkInformation.dll
BleemSync\System.Net.Ping.dll
BleemSync\System.Net.Primitives.dll
BleemSync\System.Net.Requests.dll
BleemSync\System.Net.Security.Native.a
BleemSync\System.Net.Security.Native.dylib
BleemSync\System.Net.Security.dll
BleemSync\System.Net.ServicePoint.dll
BleemSync\System.Net.Sockets.dll
BleemSync\System.Net.WebClient.dll
BleemSync\System.Net.WebHeaderCollection.dll
BleemSync\System.Net.WebProxy.dll
BleemSync\System.Net.WebSockets.Client.dll
BleemSync\System.Net.WebSockets.dll
BleemSync\System.Net.dll
BleemSync\System.Numerics.Vectors.dll
BleemSync\System.Numerics.dll
BleemSync\System.ObjectModel.dll
BleemSync\System.Private.CoreLib.dll
BleemSync\System.Private.DataContractSerialization.dll
BleemSync\System.Private.Uri.dll
BleemSync\System.Private.Xml.Linq.dll
BleemSync\System.Private.Xml.dll
BleemSync\System.Reflection.DispatchProxy.dll
BleemSync\System.Reflection.Emit.ILGeneration.dll
BleemSync\System.Reflection.Emit.Lightweight.dll
BleemSync\System.Reflection.Emit.dll
BleemSync\System.Reflection.Extensions.dll
BleemSync\System.Reflection.Metadata.dll
BleemSync\System.Reflection.Primitives.dll
BleemSync\System.Reflection.TypeExtensions.dll
BleemSync\System.Reflection.dll
BleemSync\System.Resources.Reader.dll
BleemSync\System.Resources.ResourceManager.dll
BleemSync\System.Resources.Writer.dll
BleemSync\System.Runtime.CompilerServices.Unsafe.dll
BleemSync\System.Runtime.CompilerServices.VisualC.dll
BleemSync\System.Runtime.Extensions.dll
BleemSync\System.Runtime.Handles.dll
BleemSync\System.Runtime.InteropServices.RuntimeInformation.dll
BleemSync\System.Runtime.InteropServices.WindowsRuntime.dll
BleemSync\System.Runtime.InteropServices.dll
BleemSync\System.Runtime.Loader.dll
BleemSync\System.Runtime.Numerics.dll
BleemSync\System.Runtime.Serialization.Formatters.dll
BleemSync\System.Runtime.Serialization.Json.dll
BleemSync\System.Runtime.Serialization.Primitives.dll
BleemSync\System.Runtime.Serialization.Xml.dll
BleemSync\System.Runtime.Serialization.dll
BleemSync\System.Runtime.dll
BleemSync\System.Security.AccessControl.dll
BleemSync\System.Security.Claims.dll
BleemSync\System.Security.Cryptography.Algorithms.dll
BleemSync\System.Security.Cryptography.Cng.dll
BleemSync\System.Security.Cryptography.Csp.dll
BleemSync\System.Security.Cryptography.Encoding.dll
BleemSync\System.Security.Cryptography.Native.Apple.a
BleemSync\System.Security.Cryptography.Native.Apple.dylib
BleemSync\System.Security.Cryptography.Native.OpenSsl.a
BleemSync\System.Security.Cryptography.Native.OpenSsl.dylib
BleemSync\System.Security.Cryptography.OpenSsl.dll
BleemSync\System.Security.Cryptography.Primitives.dll
BleemSync\System.Security.Cryptography.X509Certificates.dll
BleemSync\System.Security.Principal.Windows.dll
BleemSync\System.Security.Principal.dll
BleemSync\System.Security.SecureString.dll
BleemSync\System.Security.dll
BleemSync\System.ServiceModel.Web.dll
BleemSync\System.ServiceProcess.dll
BleemSync\System.Text.Encoding.Extensions.dll
BleemSync\System.Text.Encoding.dll
BleemSync\System.Text.RegularExpressions.dll
BleemSync\System.Threading.Overlapped.dll
BleemSync\System.Threading.Tasks.Dataflow.dll
BleemSync\System.Threading.Tasks.Extensions.dll
BleemSync\System.Threading.Tasks.Parallel.dll
BleemSync\System.Threading.Tasks.dll
BleemSync\System.Threading.Thread.dll
BleemSync\System.Threading.ThreadPool.dll
BleemSync\System.Threading.Timer.dll
BleemSync\System.Threading.dll
BleemSync\System.Transactions.Local.dll
BleemSync\System.Transactions.dll
BleemSync\System.ValueTuple.dll
BleemSync\System.Web.HttpUtility.dll
BleemSync\System.Web.dll
BleemSync\System.Windows.dll
BleemSync\System.Xml.Linq.dll
BleemSync\System.Xml.ReaderWriter.dll
BleemSync\System.Xml.Serialization.dll
BleemSync\System.Xml.XDocument.dll
BleemSync\System.Xml.XPath.XDocument.dll
BleemSync\System.Xml.XPath.dll
BleemSync\System.Xml.XmlDocument.dll
BleemSync\System.Xml.XmlSerializer.dll
BleemSync\System.Xml.dll
BleemSync\System.dll
BleemSync\WindowsBase.dll
BleemSync\libclrjit.dylib
BleemSync\libcoreclr.dylib
BleemSync\libdbgshim.dylib
BleemSync\libe_sqlite3.dylib
BleemSync\libhostfxr.dylib
BleemSync\libhostpolicy.dylib
BleemSync\libmscordaccore.dylib
BleemSync\libmscordbi.dylib
BleemSync\libsos.dylib
BleemSync\mscorlib.dll
BleemSync\netstandard.dll
BleemSync\sosdocsunix.txt
Games\1\
Games\1\GameData\Game.ini
Games\1\GameData\SLUS-00594.bin
Games\1\GameData\SLUS-00594.cue
Games\1\GameData\SLUS-00594.lic
Games\1\GameData\SLUS-00594.png
Games\1\GameData\SLUS-00776.bin
Games\1\GameData\SLUS-00776.cue
Games\1\GameData\pcsx.cfg
Games\2\
Games\2\GameData\Game.ini
Games\2\GameData\SLUS-01066.bin
Games\2\GameData\SLUS-01066.cue
Games\2\GameData\SLUS-01066.lic
Games\2\GameData\SLUS-01066.png
Games\2\GameData\pcsx.cfg
lolhack\boot.sh
lolhack\lolhack.sh
FritzBookPro:BleemSync-0 birddog$ \

**Comment by pathartl** [comment]
I added a new build script with 0.3.2. Can you try the release again? https://github.com/pathartl/BleemSync/releases/tag/0.3.2

**Comment by fritztoch** [comment]
Aces. Working as expected now. Thanks
