### ISSUE TITLE
adding disk with tracks

### ISSUE THREAD

**Issue by filocted** [pathartl/BleemSync#49]
I dont know if this is a issue but unable to add games with disk 1 (trakc1) and (trakc2).

**Comment by levigilbertson** [comment]
I tested this and they should work without issue. Just make sure they are named correctly and then edit the .cue to match. Notepad or Notepad++ will work for editing the .cue file

.bins should look like
SLUS-00067 (Track 1).bin
SLUS-00067 (Track 2).bin
and so on...

.cue looks like (TRACK and INDEX should already exist in the .cue file there should be no need to edit those.)
FILE "SLUS-00067 (Track 1).bin" BINARY
TRACK 01 MODE2/2352
INDEX 01 00:00:00
FILE "SLUS-00067 (Track 2).bin" BINARY
TRACK 02 AUDIO
INDEX 00 00:00:00
INDEX 01 00:02:00

**Comment by Sakarha** [comment]
You can also combine bins into one bin with the right programs. I had to do this for a couple games, and they both worked.

**Comment by LifesFailure** [comment]
Check out CDmage and this video. Guy walks through the process to combine multiple .bin files into one. Start video at 2:55

https://youtu.be/sE1w9g54OCQ?t=175

**Delete if not allowed**

**Comment by filocted** [comment]
big thx it worked my problem was game.ini file I was putting my bin file name instead of cue file name
