### ISSUE TITLE
UI error occures in japan variant

### ISSUE THREAD

**Issue by sqnyceo** [pathartl/BleemSync#5]
UI error occures in japan variant.

I already played a game with db switch, and it works as well.
(so my PSC db contains the 21st game)
https://github.com/ElMassman/gpghax

However, even if using the same game data, BleemSync occures an UI error.

If you want further logs or information, please tell me.

**Comment by pathartl** [comment]
If you could upload your regional.db from gpghax I can investigate

**Comment by pathartl** [comment]
I don't see anything that stands out. Are you getting the 001-001 error or the error that instructs you to shut down your system?

**Comment by sqnyceo** [comment]
Sorry, It was probably not "UI" error.
![error](https://user-images.githubusercontent.com/29799382/49733343-8df17000-fcc4-11e8-901d-9b93cb5d5c64.png)
This screen was displayed, and it is English
even thought other screen is Japanese.

In addition, I think that it does not matter, but I tried to take UI's error.log.
As I saw, it seems that there is not much relation, but attach it as a precaution.
[ui_error.log](https://github.com/pathartl/BleemSync/files/2663171/ui_error.log)

**Comment by sqnyceo** [comment]
I confirmed that another japanese could open BleemSync.
Maybe my specific issue...
I'll try 0.2.2, and close this soon.
Thank you.

**Comment by sqnyceo** [comment]
I could open BleemSync 0.2.2!
language select screen was displayed first.
game's datas and Game.ini are same as what failed.

I'm grad if you could tell me what you changed other than audio and controller settings.
Anyway, close this.
Thank you.
