### ISSUE TITLE
Print version number when running BleemSync (Quality of life improvement)

### ISSUE THREAD

**Issue by UltimaN3rd** [pathartl/BleemSync#50]
I think it would be nice to print out something like "BleemSync v0.3.2" preceding all the "Game Added" messages, just to let the user know that they've indeed used their freshly downloaded latest version.

**Comment by pathartl** [comment]
Should be part of the logging overhaul. Reliant on #76 

Crappy response for now: checking version on Windows can be done by checking the product version on BleemSync.dll

**Comment by swingflip** [comment]
Build version will be available from 1.0 GUI and in the 1.0 payload we store the build and git version of the payload and bootloader to the console for reference.

Closed as this is fufilled in 1.0
