### ISSUE TITLE
Bypass LibCrypt protection (.sbi)

### ISSUE THREAD

**Issue by madballnyhc** [pathartl/BleemSync#52]
Hello,
I have tried to play to the PAL version of medievil, but this game was protected. It request a sbi file to unlock the protection. Should I put this file in GameData folder ? A lot of PAL games are concerned by this limitation.
Thanks

**Comment by MrMilenko** [comment]
They cannot be bypassed as far as I'm aware, but they are available.

http://psxdatacenter.com/sbifiles.html
