### ISSUE TITLE
USB maker

### ISSUE THREAD

**Issue by acidrain97** [pathartl/BleemSync#54]
can someone explain why the size/maker of USB stick matters? I like to get a working 128gb but I can't even get a 16 or 32gb San Disk working. Only 2 or 4gb no name brand sticks seem to work. Any Clues?

**Comment by LifesFailure** [comment]
I did not have luck with a SanDisk 64 GB USB 3, but an 8 GB USB 2 worked fine. 

Seems that USB 3 has more issues being recognized. I have not tested any 2.0 sticks over 8 GB as I no longer own any of these

**Comment by acidrain97** [comment]
I'll have to find an 8gb 2.0 and give it a try... But San Disks do not work. HP 4gb 2.0 work fine. Go Figure.

**Comment by LifesFailure** [comment]
Fat32. Honestly, I don't remember the brand. It was given to me when I worked IT for a school district. The words are all rubbed off. Sorry.

**Comment by rick2890** [comment]
Hi
It does matter the 64 gb San disk doesn't work only 8/32/16 gb work.

**Comment by rick2890** [comment]
SanDisk SDCZ50-016G-B35

**Comment by rick2890** [comment]
Get this usb SanDisk SDCZ50-016G-B35 
Delete the bleemsync folder once you have run the bleemsync.exe do it everytime

**Comment by aprizm** [comment]
I bought a Kingston-DataTraveler-100-G3  64GB and it works great but theres no light to confirmed but the one on the psc should be enough

**Comment by mtrivs** [comment]
I believe @pathartl created this spreadsheet of USB drives that are compatible with the PSC.

[https://docs.google.com/spreadsheets/d/1saluXC8jfWhOVT9-JXj1Kd62hL2WGtCX6zErY6AElco](https://docs.google.com/spreadsheets/d/1saluXC8jfWhOVT9-JXj1Kd62hL2WGtCX6zErY6AElco/edit#gid=0)

**Comment by acidrain97** [comment]
> I believe @pathartl created this spreadsheet of USB drives that are compatible with the PSC.
> 
> [https://docs.google.com/spreadsheets/d/1saluXC8jfWhOVT9-JXj1Kd62hL2WGtCX6zErY6AElco](https://docs.google.com/spreadsheets/d/1saluXC8jfWhOVT9-JXj1Kd62hL2WGtCX6zErY6AElco/edit#gid=0)

cool will check it out.

just wondering have you been able to get .PBP games working? My understanding is click on load CD Image and scroll down to a PBP or Bin file and the game should run. Doesn't Does anyone know how to get this to work?

**Comment by BekaMaster** [comment]
I'm using a SanDisk 128GB Cruzer Blade USB Flash Drive

**Comment by pathartl** [comment]
Closing. Spreadsheet is available, no need for an issue.

**Comment by Edjuh82** [comment]
It will work but it is on the limit of power. Having a powered usb hub will make it work for sure. Hell even a 256 gb of sandisk will work then. I use that one now.

**Comment by jlepthien** [comment]
Okay. I’ll try that. Doesn’t matter if 2.0 or 3.0? Never had a powered one for a long time...let’s see where I can find one quickly...

**Comment by jlepthien** [comment]
Hey guys. Just to confirm it all works now with a simple USB 2.0 powered HUB I bought for 15€. Thanks for the info...
