### ISSUE TITLE
Powers off when exiting emulation menu

### ISSUE THREAD

**Issue by panthercity** [pathartl/BleemSync#56]
BleemSync-0.3.1-win7-x86 The USB boots up fine and im able to select a game but when i choose to exit via the emulator menu the console powers off.

**Comment by safetychief8** [comment]
Same issue with 3.2.

**Comment by panthercity** [comment]
i noticed it started happening after 31 games i had 35 but then it started to shut down.....i removed the last 4 games and everything started working again.

**Comment by safetychief8** [comment]
Hopefully, they'll fix it next update.

**Comment by safetychief8** [comment]
I actually changed discs using the in game menu, but I’ll try the 4.0 update.

**Comment by Sloneborg** [comment]
I have the 4.1 update and it does the same thing to me. The games load fine but as soon as I go back to the main menu it shuts off.

**Comment by CannonZero** [comment]
Same issue with 4.1 and tried all versions of BS. Started after 30 titles and still doing it with 20 titles on a 32 lexar stick. Tried multiple 32 sticks, all doing the same thing. I wonder maybe is storage space issue or something.

**Comment by urko948** [comment]
Same here with 4.1. Some games on start shut down the whole system, while others work fine but crash on reset and shuts down. Does the same thing, too whenever I look at memory cards.

**Comment by safetychief8** [comment]
Deleting the pcsx files from all folders and manually copying and pasting the .pcsx file from the unzipped Bleemsync folders into all GameData folders corrected that problem. It stopped crashing after that.

**Comment by safetychief8** [comment]
I have over 80 games on mine

**Comment by safetychief8** [comment]
...I mean .pcsx

**Comment by safetychief8** [comment]
After that delete all folders from your usb except your games folder, recopy the virgin Bleemsync folders except the game folder back onto the drive them run the Bleemsync.exe file

**Comment by PattonPlays** [comment]
This is an issue with the emulator and not bleemsync.
