### ISSUE TITLE
Title name Title

### ISSUE THREAD

**Issue by zkf1976** [pathartl/BleemSync#57]
game.ini Title= only use English？how to use and show japanese name？or change font？thanks：）

**Comment by pathartl** [comment]
This may work out of the box. I believe Game.ini should support UTF-8. Can someone else test this?

**Comment by zkf1976** [comment]
I tried to use Japanese names in game. ini, but garbled code was displayed on the UI.

**Comment by FreudienSlip** [comment]
try English in the name, and Japanese in the developer line to label for now? maybe will load and then you can still have labeled? temp fix

**Comment by evilwraith** [comment]
It looks like the default font doesn't contain glyphs for Japanese characters. There are separate fonts for Japanese in there but I don't know if the interface would know to use them. For the record, I didn't see the TM glyph in there either.

**Comment by swingflip** [comment]
@pathartl please can you elaborate if this is a payload issue or not? Is this the fact the stock UI doesn't contain special characters for some languages and can't display the characters?

**Comment by evilwraith** [comment]
If it's using the Liberation fonts included in the source, it only supports English and Cyrillic. Newer versions support Greek and Hebrew but not Japanese.

A deeper dive does show it has the R and TM glyphs. I'll try to do a deeper, deeper dive tonight.

**Comment by swingflip** [comment]
OK, so the font on the UI doesn't support the extended character set. The only way we can fix this is by using an extended character set. (We use one for the (S)NESC and RetroArch. I can look to add an option to the payload and load in an extended character set to the stock UI
