### ISSUE TITLE
Configuration file not found.

### ISSUE THREAD

**Issue by mpalpha** [pathartl/BleemSync#6]
E:\Games\1\GameData>dir
 Volume in drive E is SONY
 Volume Serial Number is 9C82-09CF

 Directory of E:\Games\1\GameData

12/09/2018  02:50 PM    <DIR>          .
12/09/2018  02:50 PM    <DIR>          ..
12/09/2018  03:27 PM               100 Game.ini
09/01/2018  02:56 PM             6,829 pcsx.cfg
12/09/2018  02:17 PM                 0 SLUS-00548.lic
12/09/2018  03:13 PM                76 SLUS-00548.cue
12/09/2018  03:13 PM       528,049,872 SLUS-00548.bin
12/09/2018  03:26 PM           100,662 SLUS-00548.png
               6 File(s)    528,157,539 bytes
               2 Dir(s)  14,460,379,136 bytes free

E:\Games\1\GameData>E:\bleemsync\bleemsync
E:\bleemsync\..\Games\1

Unhandled Exception: System.IO.FileNotFoundException: Configuration file not found.
   at SharpConfig.Configuration.LoadFromFile(String filename, Encoding encoding)
   at BleemSync.Services.GameService.GetGameInfo(Int32 gameId) in C:\Users\Pat\source\repos\BleemSync\BleemSync.Services\GameService.cs:line 14
   at BleemSync.Program.Main(String[] args) in C:\Users\Pat\source\repos\BleemSync\BleemSync\Program.cs:line 36

**Comment by pathartl** [comment]
Not sure how I missed that. Should be fixed in 0.2.1

https://github.com/pathartl/BleemSync/releases/tag/0.2.1
