### ISSUE TITLE
about  change the BISO setting in pcsx.cfg

### ISSUE THREAD

**Issue by cashimi001** [pathartl/BleemSync#60]
sorry my bad english , I just want to change the bios file for different Game ,some game can working for romw.bin some game need special BIOS file.  i tryed Write the 'Bios = romw.bin' in pcsx.cfg but it is not working the game still running in romjp.bin .  i tryed change the bios in pcsx menue it is working then i saved it in the menue , but next time run this game it still use romjp.bin bios file. so can not be save
and bios setting not working in the pcsx.cfg . any help for me?  thank you so much!

**Comment by Macapichu** [comment]
I just delete romJP.bin, that’s work and the other games too.

**Comment by PattonPlays** [comment]
Hey @cashimi001 if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
