### ISSUE TITLE
Probs with 64gb & more?

### ISSUE THREAD

**Issue by Wulv257** [pathartl/BleemSync#61]
I have tried several Usbsticks & Micro SD cards. Everything works fine with my 16 & 2GB Usb Stick. If i try my 64Gb sticks or Micro SD card, it starts most of the first time, but hangs in the game selection when i choose a Game and I have to reinstall everything. The problem is only if I install several games. If I only copie 3 games everything works. If I take my 41 games each time it hangs, or the console goes out. Has anyone ever gotten a 64Gb or more stick/card running, or is there currently a limit?

**Comment by Edjuh82** [comment]
i use a sandisk usb 128 gb.

**Comment by Wulv257** [comment]
> i use a sandisk usb 128 gb.

https://www.saturn.de/de/product/_sandisk-cruzer-blade-1952413.html this Usb Stick?

**Comment by Edjuh82** [comment]
No this one.

https://www.saturn.de/de/product/_sandisk-ultra-1946708.html

**Comment by rontonomo** [comment]
> No this one.
> 
> https://www.saturn.de/de/product/_sandisk-ultra-1946708.html

if you don't mind me asking how is your card formatted and what process did you use because i have that same usb drive and it does not work

**Comment by Edjuh82** [comment]
> > No this one.
> > https://www.saturn.de/de/product/_sandisk-ultra-1946708.html
> 
> if you don't mind me asking how is your card formatted and what process did you use because i have that same usb drive and it does not work

Fat32 and named it SONY

**Comment by rontonomo** [comment]
> > > No this one.
> > > https://www.saturn.de/de/product/_sandisk-ultra-1946708.html
> > 
> > 
> > if you don't mind me asking how is your card formatted and what process did you use because i have that same usb drive and it does not work
> 
> Fat32 and named it SONY

i got mine to work but only if its plugged into a powed usb hub. is that how you have yours hooked up?

**Comment by Edjuh82** [comment]
> > > > No this one.
> > > > https://www.saturn.de/de/product/_sandisk-ultra-1946708.html
> > > 
> > > 
> > > if you don't mind me asking how is your card formatted and what process did you use because i have that same usb drive and it does not work
> > 
> > 
> > Fat32 and named it SONY
> 
> i got mine to work but only if its plugged into a powed usb hub. is that how you have yours hooked up?

I sticked mine just in the 2 USB port. Maybe it is the power adapter that you are using? That it doesn't give enough power to boot the usb?

**Comment by haihappenhuhaba** [comment]
My setup is and old 3.5“ external hardrive case with an 2.5“ 160gb hdd it’s working great. And I’d you want play the stock games. Just power off the external harddrive power off the console and there is no need to unplug the usb cable from the hdd. Other than with an usb Stick. It has to be an external hardrivecase with external power.

**Comment by jayphung90** [comment]
> > > > > No this one.
> > > > > https://www.saturn.de/de/product/_sandisk-ultra-1946708.html
> > > > 
> > > > 
> > > > if you don't mind me asking how is your card formatted and what process did you use because i have that same usb drive and it does not work
> > > 
> > > 
> > > Fat32 and named it SONY
> > 
> > 
> > i got mine to work but only if its plugged into a powed usb hub. is that how you have yours hooked up?
> 
> I sticked mine just in the 2 USB port. Maybe it is the power adapter that you are using? That it doesn't give enough power to boot the usb?

I had the same issue, but I used my iPad power brick and it worked!

**Comment by k-huntington** [comment]
having an issue too. just bought a Sandisk Cruzer Glide 128gb (SDCZ60-128G) thumb drive, and i formatted it to fat32 with GUIformat as suggested on the main page here, and the classic won't read off of it. 

i set up a 16gb card just fine, and cloned that to the 128gb card and it still won't load up. no blinking lights at startup, nothing. it just launches to the stock OS when i boot up the PSC. :( so the 16gb card works fine, but the 128 gb won't with the exact same contents.

am i missing something here???

**Comment by jayphung90** [comment]
> having an issue too. just bought a Sandisk Cruzer Glide 128gb (SDCZ60-128G) thumb drive, and i formatted it to fat32 with GUIformat as suggested on the main page here, and the classic won't read off of it.
> 
> i set up a 16gb card just fine, and cloned that to the 128gb card and it still won't load up. no blinking lights at startup, nothing. it just launches to the stock OS when i boot up the PSC. :( so the 16gb card works fine, but the 128 gb won't with the exact same contents.
> 
> am i missing something here???

I had the same issue, but I used my iPad power brick and it worked!

**Comment by k-huntington** [comment]
> 
> 
> > having an issue too. just bought a Sandisk Cruzer Glide 128gb (SDCZ60-128G) thumb drive, and i formatted it to fat32 with GUIformat as suggested on the main page here, and the classic won't read off of it.
> > i set up a 16gb card just fine, and cloned that to the 128gb card and it still won't load up. no blinking lights at startup, nothing. it just launches to the stock OS when i boot up the PSC. :( so the 16gb card works fine, but the 128 gb won't with the exact same contents.
> > am i missing something here???
> 
> I had the same issue, but I used my iPad power brick and it worked!

i tried a fast charging samsung brick, an ipad brick, an iphone brick, a thinkgeek "back to the future" 2.1a brick, nothing would get this dumb 128gb thumb drive to initialize. bummer.

**Comment by jayphung90** [comment]
> > > having an issue too. just bought a Sandisk Cruzer Glide 128gb (SDCZ60-128G) thumb drive, and i formatted it to fat32 with GUIformat as suggested on the main page here, and the classic won't read off of it.
> > > i set up a 16gb card just fine, and cloned that to the 128gb card and it still won't load up. no blinking lights at startup, nothing. it just launches to the stock OS when i boot up the PSC. :( so the 16gb card works fine, but the 128 gb won't with the exact same contents.
> > > am i missing something here???
> > 
> > 
> > I had the same issue, but I used my iPad power brick and it worked!
> 
> i tried a fast charging samsung brick, an ipad brick, an iphone brick, a thinkgeek "back to the future" 2.1a brick, nothing would get this dumb 128gb thumb drive to initialize. bummer.

I used easeUS to fat32 and it worked, try that

**Comment by k-huntington** [comment]
> 
> 
> > > > having an issue too. just bought a Sandisk Cruzer Glide 128gb (SDCZ60-128G) thumb drive, and i formatted it to fat32 with GUIformat as suggested on the main page here, and the classic won't read off of it.
> > > > i set up a 16gb card just fine, and cloned that to the 128gb card and it still won't load up. no blinking lights at startup, nothing. it just launches to the stock OS when i boot up the PSC. :( so the 16gb card works fine, but the 128 gb won't with the exact same contents.
> > > > am i missing something here???
> > > 
> > > 
> > > I had the same issue, but I used my iPad power brick and it worked!
> > 
> > 
> > i tried a fast charging samsung brick, an ipad brick, an iphone brick, a thinkgeek "back to the future" 2.1a brick, nothing would get this dumb 128gb thumb drive to initialize. bummer.
> 
> I used easeUS to fat32 and it worked, try that

still didnt work. i think we're just gonna have to defer on the side that this thumb drive simply is not supported. apparently thats a thing. cause i have 2 drives that work, but this one just wont. :(

**Comment by pathartl** [comment]
Closing as not relevant to development of BleemSync. Please refer to [the compatibility spreadsheet](https://docs.google.com/spreadsheets/d/1saluXC8jfWhOVT9-JXj1Kd62hL2WGtCX6zErY6AElco/edit?userstoinvite=pepelbaink@gmail.com&ts=5c16b568#gid=0)
