### ISSUE TITLE
Add more than 25 custom games

### ISSUE THREAD

**Issue by Marteen911** [pathartl/BleemSync#62]
Hi!

How can i add more than 25 custom games to the system?
I run the bleemsync.exe, and i have an error: Game.ini not found for game with id 26.
The game folders are ok, i use bleemsync 0.3.2.

**Comment by pathartl** [comment]
Sounds like you're missing Games/26/GameData/Game.ini

**Comment by Marteen911** [comment]
Game.ini in the folder.. that's why i dont know what is the problem.
