### ISSUE TITLE
Game list sorted by name

### ISSUE THREAD

**Issue by BekaMaster** [pathartl/BleemSync#65]
I'm using a 128Gb USB stick with 95 games, I REALLY need the sorting feature, pleeeeease!

**Comment by pathartl** [comment]
Looked a bit at this tonight. Confirmed it wasn't an actual system limitation, but we'll have to update BleemSync to reflect it.

Dev note: various calls for directories as int's are being done. Database migration for the regional.db may be needed to fix this.

**Comment by pathartl** [comment]
Confirmed, database migration not needed.

**Comment by BekaMaster** [comment]
Great!

**Comment by LifesFailure** [comment]
Could this be done upon database creation and assigning [key]s as an option to have the titles be ordered alphabetically and reassigned to the respected folder #s? 

ORDER BY GAMETITLE ASC

There was a tool I found that is supposed to do this and you run BleemSync after to create the DB. I just can't find it now at work. Will try to locate and link

**Comment by pathartl** [comment]
Got something in a branch I can test out later. It should make the sequential folders unnecessary.

**Comment by swingflip** [comment]
There is a toggable dynamic alphabetical ordering function in the payload to do this during boot time in 1.0

However the user should be able to do this within the UI anyway in 1.0 making the payload feature unrequired in certain cases.

Closing issue for now as fufilled in 1.0 as at the very least it's a feature of the payload.
