### ISSUE TITLE
Bleemsync doesn't generate "system" folder for me!

### ISSUE THREAD

**Issue by hamadoo14** [pathartl/BleemSync#66]
Bleemsync doesn't generate "system" folder for me, although I did everything correctly I'm sure of it.
Windows 7. 64 bit

**Comment by pathartl** [comment]
It's in the ZIP. You need to extract it.

**Comment by hamadoo14** [comment]
I did extract it and still won't generate.. I tried to put the contents in a usb and work from there and still same problem. I also tried older versions but no luck.
