### ISSUE TITLE
0.4.0 issue

### ISSUE THREAD

**Issue by rick2890** [pathartl/BleemSync#68]
@pathartl I Deleted the rom's with tracks since the read.me file said so. And my games are not showing on the system anymore just showing stock games now. What are the instructions for it to be successful ? Also, deleted the system\bleemsync folder as well, since it said so.

**Comment by alucard73** [comment]
same thing for me, I end up with my 20 games ps classic

**Comment by pathartl** [comment]
Please redownload. Had to make a quick update due to a missing edit to lolhack.sh.
