### ISSUE TITLE
Errors with new automatic game.ini and game.png fetching

### ISSUE THREAD

**Issue by UltimaN3rd** [pathartl/BleemSync#69]
I have 40 games. I renamed by game.ini and xxx.png files for the first 9 to test this automatic fetching and got this console output:

> ./BleemSync
> 
> Game.ini doesn't exist, grabbing from BleemSync Central
> Found serial SCUS-94251 from disc image file /home/nick/Downloads/bleemsyncfolder/BleemSync/../Games/1/GameData/SCUS-94251.bin
> 
> Game.ini doesn't exist, grabbing from BleemSync Central
> Found serial SCUS-94559 from disc image file /home/nick/Downloads/bleemsyncfolder/BleemSync/../Games/2/GameData/SCUS-94559.bin
> 
> Game.ini doesn't exist, grabbing from BleemSync Central
> Found serial SCUS-94426  from disc image file /home/nick/Downloads/bleemsyncfolder/BleemSync/../Games/3/GameData/SCUS-94426.bin
> Could not grab game info for serial SCUS-94426 
> Game.ini doesn't exist, grabbing from BleemSync Central
> Found serial SLUS-00530 from disc image file /home/nick/Downloads/bleemsyncfolder/BleemSync/../Games/4/GameData/Croc - Legend of the Gobbos.bin
> 
> Game.ini doesn't exist, grabbing from BleemSync Central
> Found serial SLUS-00634 from disc image file /home/nick/Downloads/bleemsyncfolder/BleemSync/../Games/5/GameData/SLUS-00634.bin
> 
> Game.ini doesn't exist, grabbing from BleemSync Central
> Found serial SLUS-01032 from disc image file /home/nick/Downloads/bleemsyncfolder/BleemSync/../Games/6/GameData/SLUS-01032.bin
> 
> Game.ini doesn't exist, grabbing from BleemSync Central
> Found serial SLUS-01193 from disc image file /home/nick/Downloads/bleemsyncfolder/BleemSync/../Games/7/GameData/SLUS-01193.bin
> 
> Game.ini doesn't exist, grabbing from BleemSync Central
> Found serial SLUS-01436 from disc image file /home/nick/Downloads/bleemsyncfolder/BleemSync/../Games/8/GameData/SLUS-01436.bin
> 
> Game.ini doesn't exist, grabbing from BleemSync Central
> Found serial SLUS-00890  from disc image file /home/nick/Downloads/bleemsyncfolder/BleemSync/../Games/9/GameData/Glover.bin
> Could not grab game info for serial SLUS-00890 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Added game [-2147482647] Cool Boarders 3 to the database
> Added game [-2147482646] Cool Boarders 4 to the database
> Added game [-2147482645] Croc - Legend of the Gobbos to the database
> Added game [-2147482644] Croc 2 to the database
> Added game [-2147482643] Digimon World to the database
> Added game [-2147482642] Digimon World 2 to the database
> Added game [-2147482641] Digimon World 3 to the database
> Added game [10] Grandia to the database
> Added game [11] Klonoa - Door to Phantomile to the database
> Added game [12] The Legend of Dragoon to the database
> Added game [13] Legend of Legaia to the database
> Added game [14] Legend of Mana to the database
> Added game [15] MediEvil to the database
> Added game [16] MediEvil 2 to the database
> Added game [17] Rayman to the database
> Added game [18] Rayman 2 - The Great Escape to the database
> Added game [19] Roll Away to the database
> Added game [20] Speed Punks to the database
> Added game [21] Suikoden to the database
> Added game [22] Suikoden II to the database
> Added game [23] Team Buddies to the database
> Added game [24] Tekken to the database
> Added game [25] Tekken 2 to the database
> Added game [26] Tekken 3 to the database
> Added game [27] Tenchu - Stealth Assassins to the database
> Added game [28] Tenchu 2 - Birth of the Stealth Assassins to the database
> Added game [29] Tomba! to the database
> Added game [30] Tomba! 2: The Evil Swine Returns to the database
> Added game [31] Tony Hawk's Pro Skater to the database
> Added game [32] Tony Hawk's Pro Skater 2 to the database
> Added game [33] Tony Hawk's Pro Skater 3 to the database
> Added game [34] Tony Hawk's Pro Skater 4 to the database
> Added game [35] Vagrant Story to the database
> Added game [36] Valkyrie Profile to the database
> Added game [37] Wild Arms to the database
> Added game [38] Wild Arms 2 to the database
> Added game [39] Xenogears to the database
> Added game [40] Yu-Gi-Oh! Forbidden Memories to the database
> System.InvalidOperationException: The instance of entity type 'Game' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property, Boolean setModified)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean setModified)
>    at Microsoft.EntityFrameworkCore.Update.ModificationCommand.PropagateResults(ValueBuffer valueBuffer)
>    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation(Int32 commandIndex, RelationalDataReader reader)
>    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
> Successfully inserted 40 games

Checking my Games folders, each game except number 9 got a Game.ini file which appears to be correct, and a xxx.png file which appears to be unnecessarily small. The PNGs are only about 20-30Kb each and of ~250x250 resolution.

I'm using Ubuntu 18.04LTS by the way.

**Comment by Sanandreas21** [comment]
The data may not be in the database. Try the following to get the correct info (is required to be done manually)

Google the following (remove quotations) "site:psxdatacenter.com SLES-00024" replacing SLES-00024 with the serial number of your game, game title will probably work too if you don't know the serial number. The first result should contain all the necessary info (including cover art) for that game e.g. https://psxdatacenter.com/games/P/T/SLES-00024.html

**Comment by UltimaN3rd** [comment]
The two games that failed (SCUS-94426 and SLUS-00890) both come up with that search, so I wonder why they didn't work automatically when BleemSync tried to fetch them.

**Comment by Sanandreas21** [comment]
They're probably not in the BleemSync database, this is just another resource I use to get the data needed for games.

**Comment by pathartl** [comment]
Please try [0.4.1](https://github.com/pathartl/BleemSync/releases/tag/0.4.1) and review the release notes. Hopefully this helps. It fixed 3 games for me that were not scanning in.
