### ISSUE TITLE
controller not working with SLUS-00548

### ISSUE THREAD

**Issue by mpalpha** [pathartl/BleemSync#7]
controller not working.
pcsx.cfg is unmodified.

could be related to 3rd party controller ref in the bleemsync included pcsx.cfg
https://github.com/pathartl/BleemSync/blob/f01416e2652e2cc5258f9c20bc8ac42a6b3fa3e0/BleemSync.Payload/Games/1/GameData/pcsx.cfg#L219

and 

https://github.com/pathartl/BleemSync/blob/f01416e2652e2cc5258f9c20bc8ac42a6b3fa3e0/BleemSync.Payload/Games/2/GameData/pcsx.cfg#L219

**Comment by pathartl** [comment]
Please try 0.2.2 https://github.com/pathartl/BleemSync/releases/tag/0.2.2

**Comment by mpalpha** [comment]
controls and sound are working in 0.2.2

emulator settings hotkey isn't.

**Comment by pathartl** [comment]
Closing this as the original issue is solved.

Emulator settings hotkey had to be removed. It was never working for me and caused controls to be completely unbound.
