### ISSUE TITLE
Enhancement - Create Log directory after running BleemSync.exe

### ISSUE THREAD

**Issue by LifesFailure** [pathartl/BleemSync#76]
It would be nice to be able to enable logging to be enabled/disabled through a config file GENERATE_LOGS =TRUE/FALSE. This could later easily be converted to a checkbox in a GUI if created.

Or to have a log created after running BleemSync that captures any error regarding building a GAME.ini, finding images, and the game folder output:

1 - Castlevania Symphony of the Night
2 - Tony Hawk's Pro Skater
3 - Tony Hawk's Pro Skater 2
4 - Silent Hill
5 - Xenogears
6 - ......

**Comment by pathartl** [comment]
Been thinking about this for a while. We need to integrate [NLog](https://nlog-project.org/)

**Comment by pathartl** [comment]
No longer applicable
