### ISSUE TITLE
Problem with auto scraping and generating .ini on some games.

### ISSUE THREAD

**Issue by LifesFailure** [pathartl/BleemSync#77]
I am having some issues scraping for some games using the auto scraping and .ini generator. Below is the output from running BleemSync.exe

====================

_**Game.ini doesn't exist, grabbing from BleemSync Central
Found serial SLUS-00067  from disc image file K:\BleemSync\..\Games\5\GameData\Castlevania - Symphony of the Night.bin
Could not grab game info for serial SLUS-00067
Game.ini doesn't exist, grabbing from BleemSync Central
Found serial SLUS-00027  from disc image file K:\BleemSync\..\Games\6\GameData\Blood Omen - Legacy of Kain.bin
Could not grab game info for serial SLUS-00027
Game.ini doesn't exist, grabbing from BleemSync Central
Found serial SLUS-00708  from disc image file K:\BleemSync\..\Games\7\GameData\Legacy of Kain - Soul Reaver (v1.1).bin
Could not grab game info for serial SLUS-00708
Game.ini doesn't exist, grabbing from BleemSync Central
Found serial SCUS-94900  from disc image file K:\BleemSync\..\Games\8\GameData\Crash Bandicoot (USA).bin
Could not grab game info for serial SCUS-94900
Game.ini doesn't exist, grabbing from BleemSync Central
Found serial SLUS-20238 from disc image file K:\BleemSync\..\Games\9\GameData\Crash Bandicoot - The Wrath of Cortex (USA).bin
Could not grab game info for serial SLUS-20238
Game.ini doesn't exist, grabbing from BleemSync Central
Found serial SLUS-00684  from disc image file K:\BleemSync\..\Games\10\GameData\Jackie Chan Stuntmaster.bin
Could not grab game info for serial SLUS-00684
Game.ini doesn't exist, grabbing from BleemSync Central
Game.ini doesn't exist, grabbing from BleemSync Central
Added game [1] Tony Hawk's Pro Skater 2 to the database
Added game [2] Tomb Raider II - Starring Lara Croft to the database
Added game [3] Xenogears to the database
Added game [4] Silent Hill to the database**_

=================================

I have verified the folder structure to increment by 1 number. Each folder has GameData folder as the previous games. Tried removing all data and adding again. The issues are with the particular games. 

I have loaded up several others without issue. Also have added Castlevania SOTN as the 3rd game and added Silent Hill after to see if there was a hiccup in the ordering. It did not create any info for Castlevania, but still added info for Silent Hill.

--All .bin and .cue are verified to be good. This is used as my backup game collection in LaunchBox as well.

Please let me know if I can be of more assistance, or any suggestion is appreciated.

**Comment by cszhe** [comment]
Same here. It works for some games but not for all. Wonder how can we contribute to make the database complete.

```
Game.ini doesn't exist, grabbing from BleemSync Central
Found serial SLUS-01041 from disc image file /Users/zhe203/Desktop/BleemSync-0.4.0-osx-x64/BleemSync/../Games/12/GameData/Chrono Cross (Disc 1).bin
Could not grab game info for serial SLUS-01041
Game.ini doesn't exist, grabbing from BleemSync Central
Found serial SLUS-00892 from disc image file /Users/zhe203/Desktop/BleemSync-0.4.0-osx-x64/BleemSync/../Games/13/GameData/Final Fantasy VIII (Disc 1).bin
Could not grab game info for serial SLUS-00892
Game.ini doesn't exist, grabbing from BleemSync Central
Found serial SLUS-01042 from disc image file /Users/zhe203/Desktop/BleemSync-0.4.0-osx-x64/BleemSync/../Games/14/GameData/Parasite Eve II (Disc 1).bin
Could not grab game info for serial SLUS-01042
```

**Comment by pathartl** [comment]
Please try [0.4.1](https://github.com/pathartl/BleemSync/releases/tag/0.4.1) and review the release notes. Hopefully this helps. It fixed 3 games for me that were not scanning in.
