### ISSUE TITLE
Build 0.2.1 - no sound or controls in any game

### ISSUE THREAD

**Issue by manchos2** [pathartl/BleemSync#8]
Deleted everything from my USB except game folder, added all the new 0.2.1 files, then updated my game folder to the new structure.

When I turn on the system, the Sony jingle works. Then there's control but no sound on the main UI menu. Then on loading a game, no sound or controls.

Copy pasted all my pcsx.cfgs in GameData from the ones in your zip. Also tried Initialising Console too, same result.

(I don't have any of the .lic files in the game folder like in your zip file. Not sure what they are or if they're needed)

EDIT: Someone suggested to leave the menu open for about a minute then sounds will appear, but I had no luck with that.

**Comment by manchos2** [comment]
I removed the 'export PCSX_ESC_KEY=2' line from lolhack.sh and controls worked.

Still no sound tho

**Comment by mpalpha** [comment]
this didn't fix my sound.
