### ISSUE TITLE
Multiplayer Games - Just a thought...

### ISSUE THREAD

**Issue by abelogan** [pathartl/BleemSync#82]
I was just wondering if plugging the USB drive into one of these would work, and therefore open up the second controller port for 2-player gaming?

https://www.amazon.com/Yonisun-Micro-Samsung-Phones-Tablets/dp/B00JCZ2FQQ/ref=pd_lpo_vtph_147_bs_t_1/147-4773830-0946112?_encoding=UTF8&psc=1&refRID=XW6WTYE68RM36TQ1ZBF1

**Comment by haihappenhuhaba** [comment]
I tried it out. And this thing does not work with the Playststion Classic. The port on the back is only for power supply. I have one of these for my firetvstick!

**Comment by pathartl** [comment]
No. USB OTG is not yet ready/confirmed for the PlayStation Classic. For now, a powered USB hub must be used in one of the two controller ports.
