### ISSUE TITLE
Black screen after loading 10+ games on ps classic! Please Help!!!!

### ISSUE THREAD

**Issue by cjw19920** [pathartl/BleemSync#83]

**Comment by jayphung90** [comment]
Try a different power brick, I used my iPad one and it worked.

**Comment by cjw19920** [comment]
I tried that still having no luck. The more games you put on does it take longer to load??

**Comment by safetychief8** [comment]
I have 80 so far on mine, when the same issue happened to me, I deleted all the folders except the game folder with my game files on the USB drive and I copied all the unzipped Bleemsync folders, except the Game folder and used the Bleemsync.exe file. Changing games must be done thru the in game menu.

**Comment by cjw19920** [comment]
This does not make sense to me! I’ve got mine to work now so I’m not going to start playing around with it no more unless I need to change games

Sent from my iPhone

On 18 Dec 2018, at 14:52, safetychief8 <notifications@github.com<mailto:notifications@github.com>> wrote:


I have 80 so far on mine, when the same issue happened to me, I deleted all the folders except the game folder with my game files on the USB drive and I copied all the unzipped Bleemsync folders, except the Game folder and used the Bleemsync.exe file. Changing games must be done thru the in game menu.

**Comment by muskieratboi** [comment]
what exactly did you do to "make it work"?

**Comment by cjw19920** [comment]
I skipped back a few versions

Sent from my iPhone

On 18 Dec 2018, at 15:51, muskieratboi <notifications@github.com<mailto:notifications@github.com>> wrote:


what exactly did you do to "make it work"?

**Comment by DefKorns** [comment]
Marked as closed due to inactivity.
If more support need on your issue please join us at the ModMyClassic Discord server.  http://discord.gg/96DKEdd
