### ISSUE TITLE
Strange spacing of words on Playstion loading screen when launching game. Causes the game not to load and console to freeze.

### ISSUE THREAD

**Issue by apocalypticness** [pathartl/BleemSync#84]
Fresh install of 0.40. Have about 30+ games. Many of them are not working. I will try to start up a game and the black Playstation loading screen will appear, but the text will not be in line or spaced out correctly like when a working title starts loading. It looks something like: Lic  ensed By Sony Com puter  Entertainm    ent  Amer ica

Nothing will happen past this point and console must be restarted.

I have tried switching power bricks. I have the Sandisk 32GB (It was on the approved list).

**Comment by juicypop** [comment]
That's a bad dumb of your Rom. I had this issue too when I tried different patches for a protected game. Once I applied the correct patch the spacings where normal and the game just ran fine ;)

**Comment by apocalypticness** [comment]
Awesome. Thanks. This worked!
