### ISSUE TITLE
Game won't load/boot and I get this message ''The game closed because an error has occurred. If the problem Persists, select [Settings] [Restore Default Settings] [Initialize Console]...

### ISSUE THREAD

**Issue by Matamorte** [pathartl/BleemSync#86]
I would like to make it work. I think it's my USB stick but I'm not sure. I have tried multiple games and I keep having this message. Also, when the system boot I get the health message in Japanese and I don't know why. Thanks in advance!

Best regards,
Max

**Comment by muskieratboi** [comment]
Double check your file and directory structure, and try again.

**Comment by pathartl** [comment]
Make sure you're on 0.4.1. If a game is crashing and you're seeing that screen, it's most likely a bad disc image or incompatibility with the emulator.
