### ISSUE TITLE
Running under Linux 64

### ISSUE THREAD

**Issue by KafuruIGuess** [pathartl/BleemSync#87]
When running BleemAync on Linux (Ubuntu 18.04.1 LTS AMD 64 to be exact) the program doesn't launch natively, requiring to go into the properties of the program and enabling "allow executing file as program"which then has it "running" but there is no actual indication that it starts.

all be it this isnt an pertinent issue but it came to my attention when formatting a drive to ext4 and trying to rerun BleemSync

**Comment by pathartl** [comment]
Cross-platform (non-Windows) is still experimental. Sounds like you're launching through the UI. Try `cd`ing into the BleemSync directly and running it there. `chmod +x BleemSync` may be needed.

**Comment by KafuruIGuess** [comment]
Running through terminal worked to show what it had done
