### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by pathartl** [pathartl/BleemSync#89]
Having a GUI is a pretty high priority on our list. Making an issue to keep track of it.

**Comment by JonathanRowley** [comment]
What does the native implementation use?

**Comment by pathartl** [comment]
The one that runs on the system on boot? .NET Core compiled for Linux ARM. Getting a basic UI hosted on-system with .NET Core MVC should be trivial.

**Comment by JonathanRowley** [comment]
I was wondering what the original UI was built with? But are you suggesting a full replacement UI? Potentially an Electron app?

**Comment by pathartl** [comment]
Sorry, not sure if that was clear. BleemSync as a game management tool will transform into a web app. The main system UI will not be touched.

**Comment by pathartl** [comment]
Closed with 1.0.0
