### ISSUE TITLE
blank screen#

### ISSUE THREAD

**Issue by Badabingsta** [pathartl/BleemSync#90]
afternoon guys can someone help i just get a blank screen after i plug my usb then it switches off?

**Comment by cjw19920** [comment]
I had this issue then reverted back to older version. Also try and avoid downloading games that have different versions. I believe sometimes if you have the wrong version it will be a corrupt file and will make your PS fail to load the USB drive

**Comment by Badabingsta** [comment]
I will give that a go I think it was when I added an Italian game called "Quiz Show", so I will remove and see what happens. Thank you for the tip I will post later and advise.
