### ISSUE TITLE
Games will not boot

### ISSUE THREAD

**Issue by Hellohi1995** [pathartl/BleemSync#93]
BleemSync will boot and games will show up properly in menu, but when I try to run a game the system freezes momentarily and then acts as though nothing happens. 

I have tried BleemSync 0.4.0 and 0.4.1. 

I have tried multiple USB flash drives. One of my drives would not boot, three of them boot but get this error. I just purchased a SanDisk Cruzer Glide 64GB in hopes of getting the games to boot. 

Has anyone experienced similar issues?

**Comment by Sanandreas21** [comment]
I had a similar issue and it was an error with the .cue file. In the end I re-downloaded all the games and setup the cue files correctly using the original .bin filenames.

**Comment by muskieratboi** [comment]
Please make sure that the .cue file is correctly built for the .bin file. 

.cue files are structures thusly:

FILE "filename.bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

Open the .cue file in an advanced text editor like notepad++ or the like, and make sure that the filename inside the quotation marks matches that of the .bin file exactly. (be aware this only works for single track games, some games may be multitrack, and should be checked using specialised tools.)

**Comment by Hellohi1995** [comment]
I just double checked my files, and I'm not sure where I am going wrong.

I am using the existing file structure. My cue and bin files both have matching names. The cue file references the bin file. 

I have tried it with multiple different games (bins and cues) as well.

**Comment by haihappenhuhaba** [comment]
Than check your game.ini files. look at the file the discs section needs to be on the bottom. so when you have the same game.ini from bleemsyncs earlier versions that it could be. my problem was solved since bleemsync 0.40. so every game started now properly from the ui!

**Comment by djnavcr** [comment]
In my case I have a lot of games that do not boot, for example crash bandicoot works for me but teken 3 is not working , when I press the X nothing happen , do you think is something with the bin ?

**Comment by PattonPlays** [comment]
Hey @Hellohi1995 if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
