### ISSUE TITLE
Original PS Dual Shock/Analog Controller with a USB Adapter

### ISSUE THREAD

**Issue by safetychief8** [pathartl/BleemSync#94]
Has anyone tried to use the original PS dual shock or analog controller on the PS Classic, with a USB controller adapter?

**Comment by rochev22** [comment]
Also interested in this feature. It is possible to have a vibration with Dualshock 1??

**Comment by pathartl** [comment]
Not a focus of BleemSync at this time. There's much more base work that needs to be done.
