### ISSUE TITLE
8BitDo Wireless Adapter Preorders/USB Hack

### ISSUE THREAD

**Issue by safetychief8** [pathartl/BleemSync#95]
8 Bit Do is taking preorders on Amazon for a wireless adapter for $19.99, to use PS3/4 wireless controllers. Hopefully, it'll be compatible with the dual USB controller hack.

**Comment by pathartl** [comment]
This is not an issue and has nothing to do with BleemSync. Please leave discussion like this to other social channels.

**Comment by safetychief8** [comment]
No problem Pat, I meant no harm, I'll remove this post.
