### ISSUE TITLE
BleemSync title limitation + crash

### ISSUE THREAD

**Issue by khenzel** [pathartl/BleemSync#97]
I have been working on adding the entire PS1 library to my console via a 1tb hard drive and found that once i exceed @300 titles my system fails to boot. Is there a known cutoff for how many titles this console hack method can support?

(yes i know 3.0 is not recommended, yada yada, but this drive works perfectly when i have < 200 titles)

Are there any tricks coming that reduce the amount of titles that display on the wheel when the system boots?

This seems like a pretty huge limitation.

**Comment by khenzel** [comment]
I would also like to know what the max recommended title limit is while this issue is being worked through... would be a great thing to add to the readme release notes!

**Comment by pathartl** [comment]
Your 300 is the highest count of games I've seen so far. We've confirmed around 100 titles works fine. Not sure if there's a limit or what that limit could be

**Comment by khenzel** [comment]
Confirming, I had 359 titles added to my DB, and it caused the system to crash.

I deleted 59 titles capping off at 300. Re-built my DB and tried again. This time my system boots normally.

It seems for now 300 titles is the max that can be allowed on the wheel.

Any plans on creating folders with 300 title sub-menus? This would be AMAZING if so. I'm dreaming of a classic console with the full ps1 library! :)

**Comment by pathartl** [comment]
cyanic over in the Discord figured out how to do folders. It's definitely something we'd like to look into once we verify it's stable.

Huge kudos to him, he's been doing an awesome job tearing down the UI

**Comment by khenzel** [comment]
can i get a discord invite link? i'd love to join you over there.

I noted too that 300 titles is a bit unstable... such issues as crashing when hitting reset out of a game (presumably during save state generation) happen with the UI crowded up with too many titles. 

300 MAY boot, but it takes a toll on the rest of the UI apparently.

**Comment by pathartl** [comment]
Closing this in favor of #99

**Comment by pathartl** [comment]
[Discord link](https://discord.gg/mteuJtk)
