### ISSUE TITLE
Connecting a drive with high contents causes a very long black screen bootup

### ISSUE THREAD

**Issue by khenzel** [pathartl/BleemSync#98]
I had my 1tb drive with 750gb of roms in a random root folder. This caused BleemSync to hang on the black screen (before health and safety warning) for about 115 seconds. Can you correct the boot up behavior to not scan the entire drive contents before boot, or is this a system limitation? 

This is relevant as this is the cause for slower boots. I.E. lets say i have 150 games. The console will first scan the drive (black screen time bucket A - taking x seconds), then it will hit the health and safety screen where it will read/cache the game list menu (time bucket B taking x seconds). Only the game render read/cache is really necessary... time bucket A is totally useless and un-necessary, unless of course it is a console system limitation.

**Comment by pathartl** [comment]
BleemSync is set to scan on each boot. If this is causing undesired boot times, you can delete the System/BleemSync folder to disable it.

**Comment by khenzel** [comment]
That's not it actually, i did that long ago. Sorry let me enlarge on what i encountered:

First test:
1tb drive inserted. 750gb of games in random root folder - boot = 115 seconds on black screen
Second test:
i moved the random root folder with games (being totally un-used by BleemSync) off to my PC HD, tested again:
this time, black screen boot time was reduced to about 10 seconds.

Assumption::
The system scan is taking time to do a full DIR of the USB contents before releasing to the game scan

**Comment by pathartl** [comment]
Hm, could be the loads of overmounting it'd be doing.

We're looking at possibly moving away from overmounting with a new payload in 0.5.0 which might fix this.

**Comment by YoshiNurijumi** [comment]
I can confirm.

I am using a 128gig 2.0 USB Stick that is just for my PS1 games. I have 85 folders (games) and it takes a while to load up.

I am testing games as far as I have gotten, Bust a Groove and Dragonball GT are just stuck at the main PSC game selection screen and I can not move anything. Dont know if its a bug or the games just dont work....but I am trying to compile a list of working and non working games.

**Comment by joshcasas** [comment]
I'm also having the some really slow boot up problem as khenzel posted in the very first post on this page.

**Comment by swingflip** [comment]
This is no longer an issue with 1.0 as the boot routine and handling of games has completely changed.

Closing as no longer an issue with 1.0
