### ISSUE TITLE
Add folders to UI

### ISSUE THREAD

**Issue by pathartl** [pathartl/BleemSync#99]
Current wheel is limited to ~300 titles. Adding folders would let us expand that a bit. Ref #97

**Comment by swingflip** [comment]
Will be aimed for 1.1 payload

**Comment by swingflip** [comment]
Added to to-do for 1.1

**Comment by GMMan** [comment]
Reference implementation, needs a few kinks worked out and we'll want to figure out what we want with the intercept script first: https://github.com/GMMan/psc_folders

**Comment by pathartl** [comment]
I want to start working on this feature. The UI has hidden support for organizing game nodes into folders. In the UI's database, the GameManagerNodes table allows nodes to assign other nodes as parents. In the implementation with jstree, only nodes of type `folder` may contain child nodes.

I believe all of the database generation for folders should be done by the UI's code as it should be a change in the `GameManagerService` implementation in the PSC extension, and thus other extensions for other systems.

As for integrating with the intercept for the PSC, I think it would make sense to use the node ID's as the filename for the databases generated. This is mostly me just thinking out loud, but the databases directory would look like:

```
databases/
    1.folder.db
    23.folder.db
    32.folder.db
```

Inside of the PSC's ui_menu DB, the basename for each folder would be `{id}.folder.db`, the intercept script would parse this, know to load a separate UI, and load it out of the databases folder.

**Comment by GMMan** [comment]
Under this system, I suppose all game folders (/gaadata type stuff) will be linked at the start, and the only thing that really changes is which DB is being used? Also, are folders nestable inside each other? Where are stock games placed? Is there a stack of sorts for navigating between folder levels?

**Comment by pathartl** [comment]
Being linked from the start shouldn't present an issue as we're using unique ID's from the BS UI database. Correct, the only change would be which DB is being used.

Folders are nestable inside each other inside of the UI.

The stock games are an interesting thing to consider. I think we should undo the payload functionality that merges the databases together and opt for a feature in the UI to add entries for the stock games. How to handle these at this moment isn't super clear to me, as well as how it will fare in the future with the ability to add/remove games to the internal storage. Do we reserve the id's 1-20 for built in games? SQLite is pretty lenient on the use of uniques/keys, so if we needed to write a migration to pad every game by 20, that wouldn't be an issue.

> Is there a stack of sorts for navigating between folder levels?

I'm not sure what you mean by this. Like breadcrumbs?

**Comment by pathartl** [comment]
> Inside of the PSC's ui_menu DB, the basename for each folder would be `{id}.folder.db`, the intercept script would parse this, know to load a separate UI, and load it out of the databases folder.

I forgot how the payload worked for a second. Maybe we just set the basename to "folder" for folders and have the folders inside the games path?

```
games/
    32/folder.db
    43/folder.db
    44/SLUS-00860.cue
    ...
```

**Comment by GMMan** [comment]
How about this?

```
games/
    32/folder.db
    32/folder.png
```
The parent of the folder will have that folder as a "game", with its disc ID as "folder". Basically what you said, just with the addition of the cover for it.

> I'm not sure what you mean by this. Like breadcrumbs?
Sure. There'd be an artificial "Up" folder added into subfolders.

**Comment by pathartl** [comment]
Hm I didn't even think about individual folder icons. I would rather opt to not have it customizable at first as it could create some interesting UI/UX challenges. Or I guess we could just overmount a default one on boot if folder.db exists in a directory, but folder.png does not.

**Comment by GMMan** [comment]
Let's consider the root level its own folder. That way we can just link the previous level as a regular folder but with a different label, and we don't have to have separate logic for dealing with going back to the root and can use the same logic to load the root when we boot.

**Comment by pathartl** [comment]
I have yet to put the integration with the database backend in, but this is what the UI looks like utilizing some built in jstree functionality:
https://i.imgur.com/NxSohUb.gifv

**Comment by kickasskc** [comment]
Love that this is currently in progress pathartl,
Sorting games into different folders either through bleemsync on the console or the UI is/would be useful in organizing bigger libraries.

The bigger issue of the Stock Carousel limiting the amount of games/artwork shown to around 300 because of a limited cache(or ram or w/e) would not be much of an issue if the Stock Carousel could be set to display only the folders that organize the games.

I have seen a video or 2 of users doing this with their own modifications to bleemsync, but this would be a wonderful feature to have integrated for all to enjoy, particularly for those who want to have the entire ps1 library on an external hdd via otg.

Honestly though great work and thanks immensly for everything. Bleemsync has turned the PSC into the ultimate emulation device!

**Comment by outlandernwah** [comment]
> Love that this is currently in progress pathartl,
> Sorting games into different folders either through bleemsync on the console or the UI is/would be useful in organizing bigger libraries.
> 
> The bigger issue of the Stock Carousel limiting the amount of games/artwork shown to around 300 because of a limited cache(or ram or w/e) would not be much of an issue if the Stock Carousel could be set to display only the folders that organize the games.
> 
> I have seen a video or 2 of users doing this with their own modifications to bleemsync, but this would be a wonderful feature to have integrated for all to enjoy, particularly for those who want to have the entire ps1 library on an external hdd via otg.
> 
> Honestly though great work and thanks immensly for everything. Bleemsync has turned the PSC into the ultimate emulation device!

Hi there! Is there a workaround for this? I have the entire NTSC library. (~1600 games) They're just in a root folder called 'roms'. I've even tried with Retroarch but I can't for some reason get the damn thing to recognize any games (.bin/.cue all of them). Any good tutorial or is it a bug? But each one is playable if I grab them thru File Explorer.

**Comment by kickasskc** [comment]
> Hi there! Is there a workaround for this? I have the entire NTSC library. (~1600 games) They're just in a root folder called 'roms'. I've even tried with Retroarch but I can't for some reason get the damn thing to recognize any games (.bin/.cue all of them). Any good tutorial or is it a bug? But each one is playable if I grab them thru File Explorer.

Hey,
If you are using bleemsync 1.2 then all you need to do is put your bin/cue files or PBP files in a folder called "transfer" on the root you your drive. That is how bleemsync organizes them and puts them in the stock systom carousel. You can also use the bleemsync UI via your internet browser to add/remove bleemsync games.

The issue is that if you have artwork then the psc will only load 200-300 before it crashes.
You might as well wait until the next update(1.3 or whatever) to add these games to bleemsync because they are updating the folder support amd you should be able to organize all the games into folders on the main carousel to reduce the artwork load and prevent crashing.

**Comment by outlandernwah** [comment]
Was this ever solved? I ended up just using RetroBoot and/or SNES NES mini

**Comment by pathartl** [comment]
I believe BleemSync 1.2 has some sort of folder support and Project Eris will support it. The issue has been closed as future versions of BleemSync will be refocusing its efforts. Please read the readme for more information.

**Comment by outlandernwah** [comment]
Awesome. Thanks for the update
